### ISSUE TITLE
Command line installation

### ISSUE THREAD

**Issue by mihha** [photoprism/photoprism#1013]
Hi,

I admire your application and would really love to use it

There is just one thing I would appreciate if possible

Would it be possible to provide non-docker installation instructions? I already have DB server, proxy etc and would love to use PhotoPrism without needing to install docker

I am aware that there is probably a way to install it by reading docker-compose file but I am not that good and I never succeeded in doing so

Thank you in advance!

**Comment by andrewlow** [comment]
I'm just a user/fan of the project, but I wanted to reply so you didn't feel ignored.

Given the small team building this project, and the additional complexity that a non-docker/container based deploy would cause for the team. I don't think that it's possible to satisfy your request.

Docker is a great technology to learn - it would be well worth your time to set up and experiment to learn more.

If you wanted to persist - it appears photoprism is a single binary inside of the container. 
```
$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
photopr+     1  0.0  0.0   3980  2300 ?        Ss   Feb11   0:00 bash /entrypoint.sh photoprism start
photopr+     9  0.0  1.0 1753312 170072 ?      Sl   Feb11   0:26 photoprism start
photopr+    21  0.0  0.0   4244  3640 pts/0    Ss   14:06   0:00 bash
photopr+    30  0.0  0.0   5900  2968 pts/0    R+   14:06   0:00 ps aux
```

To successfully run NOT in a container, you're going to need to extract some data from the container - or figure out where those artifacts came from and copy them to the right structure.

```
$ ls -l 
total 36
drwxrwxrwx  1 photoprism photoprism  4096 Feb 11 09:31 assets
drwxrwxrwx  1 photoprism photoprism  4096 Feb 11 09:31 bin
drwxrwxr-x  2 photoprism photoprism 20480 Feb  2 21:21 import
drwxrwxr-x 12 photoprism photoprism  4096 Jan 31 14:39 originals
drwxrwxr-x  6 photoprism photoprism  4096 Feb 11 14:47 storage
```

You can see the `import` `originals` `storage` mounts. These are the data file trees

`bin` contains just the photoprism binary.
`assets` appears to be a bunch of stuff for the web UI - you'll need this full tree. I will guess this is https://github.com/photoprism/photoprism/tree/develop/assets

If you really want to swim upstream and avoid docker - maybe following the build script will show you how to create the photoprism binary.

Let me finish by **strongly advising against doing this**. I present this information as a path to learning more about photoprism, not as a recommendation that this is a sensible way to run the code. Containers are a really great way to manage deployments / dependencies.

**Comment by thomaseizinger** [comment]
I am maintaining my own set of PKGBUILD files that I use to install and run photoprism on my raspberry: https://github.com/thomaseizinger/pkgbuilds

The `build()` and `package()` functions here should give you a rough idea of what is required to install it: https://github.com/thomaseizinger/pkgbuilds/blob/bbcd86787ee2a6130021468badd83e50f408d774/photoprism/PKGBUILD#L33-L65

If you are running Arch or Manjaro, you are also welcome to use the scripts. I do want to say that I am only maintaining them for my own purpose so use at your own risk :)

The reason I am doing this is because I like to manage my services on my raspberry using systemd. I actually have set service dependencies on mount points and some other things to avoid writing to the internal SD card in case my hard drive is not mounted. I guess I could also make the same thing work through docker but I took it as an opportunity to learn more about systemd and making PKGBUILD files :)

**Comment by lastzero** [comment]
The easiest way to use PhotoPrism is via Docker:

https://docs.photoprism.org/getting-started/docker-compose/

You just need to copy the example config and run `docker-compose up`. Installing and configuring all dependencies is much more work which is also why we can't provide packages for different Linux distributions yet. Even finding a working FFmpeg version is a nightmare by itself: https://github.com/photoprism/photoprism/issues/703#issuecomment-780714622
