### ISSUE TITLE
How to disable review feature?

### ISSUE THREAD

**Issue by GraysonCAdams** [photoprism/photoprism#1057]
The docs say you can disable it in Settings, but I see no way of doing that?

https://docs.photoprism.org/user-guide/organize/review/

**Comment by GraysonCAdams** [comment]
I have 8k photos pending review, is there a SQL query I can run to batch approve them all? Doing so through the UI is painstakingly slow, even with a batch selection it takes about 1 second per image.

**Comment by GraysonCAdams** [comment]
Had Settings turned off via env. variable, therefore couldn't find it through the UI.

**Comment by lucaspar** [comment]
This feature is confusing. This weekend I spent over an hour trying to figure out why the new pictures were not showing up in the main search, but were everywhere else. It turns out they just lacked my "approval".

Do you remember which env setting you changed? I can't find anything in the [config options](https://docs.photoprism.app/getting-started/config-options/#image-quality).

**Comment by lastzero** [comment]
@lucaspar It's much easier than that:

https://docs.photoprism.app/user-guide/settings/library/#quality-filter

Next time, please do not use GitHub Issues for support requests, but GitHub Discussions. Thank you! :)

**Comment by hulloanson** [comment]
For people running into the same problem, it is the `PHOTOPRISM_EXPERIMENTAL` environment variable. It has to be set to `true`.

TBH, it was not that easy...

**Comment by lastzero** [comment]
@hulloanson You just need to disable the Quality Filter on the Advanced Settings page (as documented):
https://demo.photoprism.app/library/settings/media
