### ISSUE TITLE
Some videos do not get thumbnail during first indexing

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#1148]
**Current behaviour:**
 Some videos did not get a preview thumbnail during indexing. They play normal.
When deleting those videos and adding them again --> they get a thumbnail. 
Another observation: Videos without thumbnail show up in review. When they are approved they appear in Videos. After a rescan the videos that still have no thumbnail but have been approved previously appear in the review section again.

*Acceptance Criteria:*
* Find out why the indexer does not create thumbnails for some videos on the first run

**Comment by lastzero** [comment]
Requires further investigation to provide a fix (if necessary). Could be due to many reasons, some of which are beyond our control. Thumbs could have been fixed after upgrading to a new PhotoPrism version that includes a newer `ffmpeg` version. Could be file system issues, etc. Or maybe they were previously stacked with another file that had problems?

**Comment by inakrin** [comment]
I'm experiencing the same issue. Most of the videos are shot with a Gopro camera if it matters.

**Comment by lastzero** [comment]
Does the issue still occur with our latest preview build? Many parts of the indexing and thumbnail creation process have been improved, so the problem MAY be fixed.

**Comment by lastzero** [comment]
Is this still happening? Otherwise, I would suggest closing this issue. Many details have been changed in the indexer since this problem was reported.

**Comment by lastzero** [comment]
Oh, I've asked this before. In that case, I'll close it for now.
