### ISSUE TITLE
Bug?: Unkown format (detect colors) on import

### ISSUE THREAD

**Issue by Observe-1** [photoprism/photoprism#1256]
Hello,

Firstly love your app and am actively reccomending it... seriously love it... (might even learn go at some point and help out some).

Just wondering if anyone could give me a hand figuring out what these import errors are. I can't seem to find anyone else referring to "(detect colors)" which is a bit of a weird error. The photos are JPEGs, taken on a nikon d3400 (there are other photos which imported fine from that camera on my instance) and aren't corrupted or anything and don't see any reason why they wouldn't be imported... (I can provide many examples of photos which have had this if desiered).

Also is there an easy way to only re-index part of your libary (once this is solved) as mine is fairly large... (~100k photos) 

![image](https://user-images.githubusercontent.com/30234130/116828591-7f5aca80-ab97-11eb-911b-fa0b8267c530.png)

**Comment by ayvazjet** [comment]
Windows 10 için Posta ile gönderildi Kimden: LouisGönderilme: 3 Mayıs 2021 Pazartesi 00:46Kime: photoprism/photoprismKonu: [photoprism/photoprism] Unkown format (detect colors) on import (#1256) Hello,Firstly love your app and am actively reccomending it... seriously love it... (might even learn go at some point and help out some).Just wondering if anyone could give me a hand figuring out what these import errors are. I can't seem to find anyone else referring to "(detect colors)" which is a bit of a weird error. The photos are JPEGs, taken on a nikon d3400 (there are other photos which imported fine from that camera on my instance) and aren't corrupted or anything and don't see any reason why they wouldn't be imported...Also is there an easy way to only re-index part of your libary (once this is solved) as mine is fairly large... (~100k photos)—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lastzero** [comment]
You can limit reindexing to selected folders if you use the folder dropdown on the Index page in Library.

Typically this error means the file can be decoded by the JPEG decoder that comes with Go. Some JPEG implementations may be able to ignore or fix the error. We also had users that thought their files are JPEG, but they were TIFF or PNG instead.

If you think this is a bug, you may send a file sample to hello@photoprism.app so that we can test it.

**Comment by lastzero** [comment]
I'll close this as we didn't receive feedback for more than 20 days.
