### ISSUE TITLE
Test Failed at MediaFile.Jpeg()

### ISSUE THREAD

**Issue by stobita** [photoprism/photoprism#126]
I ran Golang tests on docker, on develop branch.

```
docker-compose up -d
docker-compose exec photoprism make all
docker-compose exec photoprism make test
```

Then this error occured.(excerpt)

```
FAIL | --- FAIL: TestMediaFile_Jpeg (0.01s)
FAIL |     --- FAIL: TestMediaFile_Jpeg//IMG_4120.AAE (0.00s)
     |         mediafile_test.go:738:
     |                  Error Trace:    mediafile_test.go:738

Error:          Expected nil, but got: &photoprism.MediaFile{filename:"/go/src/github.com/photoprism/photoprism/assets/resources/examples/IMG_4120.jpg", dateCreated:time.Time{wall:0x0, ext:0, loc:(*time.Location)(n
il)}, timeZone:"", hash:"", fileType:"unknown", mimeType:"", perceptualHash:"", width:0, height:0, exifData:(*photoprism.Exif)(nil), location:(*models.Location)(nil)}
```

I think that there is a process of replacing the extension in the MediaFile.Jpeg(),  which is related.

**Comment by lastzero** [comment]
Are you using a case sensitive file system?

Michael

On 18. Jul 2019, at 14:53, Soukichi Tobita <notifications@github.com> wrote:

I ran Golang tests on docker, on develop branch.

docker-compose up -d
docker-compose exec photoprism make all
docker-compose exec photoprism make test

Then this error occured.(excerpt)

FAIL | --- FAIL: TestMediaFile_Jpeg (0.01s)
FAIL |     --- FAIL: TestMediaFile_Jpeg//IMG_4120.AAE (0.00s)
     |         mediafile_test.go:738:
     |                  Error Trace:    mediafile_test.go:738

Error:          Expected nil, but got:
&photoprism.MediaFile{filename:"/go/src/github.com/photoprism/photoprism/assets/resources/examples/IMG_4120.jpg",
dateCreated:time.Time{wall:0x0, ext:0, loc:(*time.Location)(n
il)}, timeZone:"", hash:"", fileType:"unknown", mimeType:"",
perceptualHash:"", width:0, height:0,
exifData:(*photoprism.Exif)(nil), location:(*models.Location)(nil)}

I think that there is a process of replacing the extension in the
MediaFile.Jpeg(), which is related.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/photoprism/photoprism/issues/126?email_source=notifications&email_token=AACJU5UIQ2BAI5OAV34VLVLQABRTBA5CNFSM4IE2NPBKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G773PEQ>,
or mute the thread

**Comment by stobita** [comment]
I use Docker on Mac. And when I checked, it was case-insensitive file system.
Is this a cause?

**Comment by lastzero** [comment]
Thank you for reporting this! I just removed the test as the behavior may be different in fact, depeding on the filesystem in use. Close this issue if it works for you :)

**Comment by stobita** [comment]
OK!
Thank you for your response.
I will close it.
