### ISSUE TITLE
Cannot Move More Than 999 Items

### ISSUE THREAD

**Issue by simoncoul** [photoprism/photoprism#1268]
Had ~1800 photos/videos that I wanted to more to an album. I selected all item and the selected counter showed 999. I assumed the the counter just maxed out, but when I went back I saw I still had ~800 photos that were not moved to the album and required me to select the remaining photos and move them again.

**Comment by lastzero** [comment]
You can't add more than 999 individuals pictures at once. Do it in batches if you need such big albums. You can add complete albums, moments, states, and labels to other albums though.

**Comment by simoncoul** [comment]
Is this limitation within the documentation? 1000 photos is not very many when sorting through a weeks worth of vacation photos or dumping photos from and SLR after a session.

**Comment by ayvazjet** [comment]
Windows 10 için Posta ile gönderildi Kimden: simoncoulGönderilme: 5 Mayıs 2021 Çarşamba 19:36Kime: photoprism/photoprismBilgi: SubscribedKonu: [photoprism/photoprism] Cannot Move More Than 999 Items (#1268) Had ~1800 photos/videos that I wanted to more to an album. I selected all item and the selected counter showed 999. I assumed the the counter just maxed out, but when I went back I saw I still had ~800 photos that were not moved to the album and required me to select the remaining photos and move them again.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by graciousgrey** [comment]
No it is not documented yet, good point we will add it to the docs. We did it like this for performance reasons.  It is nothing we have time to improve the next months.

**Comment by lastzero** [comment]
You can upload directly to albums or put all files from a session into a specific folder. This way, you don't have to manually select thousands of files every time.

**Comment by joachimtingvold** [comment]
I experienced the same as OP (only being able to add 999 photos to album). Maybe one solution would be a feature to "add all photos in current filter/query to an album". So if you do a search for specific photos (as simple or complex as you want), and then you could just choose "add current search to album" (rather than having to select all images).

None of the options that's suggested here would be viable for me (as it pertains to certain search filters, and the photos are not organized by folder or similar). I'll probably work around it using the API, but it's somewhat cumbersome just to be able to add 999+ photos to an album in the long run...

Not sure if this warrants re-opening this issue to address it in a different way? (@lastzero).

**Comment by lastzero** [comment]
Yes, a dynamic album based on search filters might be the better fit. There should be an issue for this already and in fact the folder / state / month albums are built like this.

**Comment by graciousgrey** [comment]
Here's the issue for conditional albums: https://github.com/photoprism/photoprism/issues/1431
