### ISSUE TITLE
seccomp and apparmor

### ISSUE THREAD

**Issue by IshFx** [photoprism/photoprism#1269]
Hello,

I didn't find any answer in the documentation to my question : 
Why does photoprism need **seccomp** and **apparmor** to be **unconfined** ?

Does is use ALL the syscalls (likely not) ?
Does it need complete rwx access to all files/network ?

Thanks in advance.

**Comment by lastzero** [comment]
No, it doesn't need all. Some users reported issues though and were not able to configure their kernel security properly. You're welcome to contribute docs, test different configurations, and help with answering support requests so that all users can enjoy the benefits of strong kernel security for their personal home server.

**Comment by IshFx** [comment]
Alright, thanks ! I'll run some tests with docker's default security profile and see which part of photoprism breaks.
In the meantime, i think the issue can be closed.

**Comment by alexislefebvre** [comment]
I run PhotoPrism without `security_opt` on Debian 10 and I don't have any issue (I installed it before that option was added). Please reopen this issue so that we can keep track of it.

Maybe these lines should be commented with an explanation: https://github.com/photoprism/photoprism/blob/2fb7a4d7ea151d86ca6bb2af48c8c03a8c3bfa0e/docker/examples/docker-compose.yml#L40-L42

**Comment by lastzero** [comment]
Should we move this to our docs repo? It's really not a feature of PhotoPrism nor do I think the average home user needs enterprise grade Linux Kernel security. Most users don't even know how file system permissions work. It's an advanced topic for those who want / need it.
