### ISSUE TITLE
Imported RAW files from Lightroom generate small, blank sidecar files

### ISSUE THREAD

**Issue by mrdrblu** [photoprism/photoprism#1283]
Hello! Recently got my own instance up and running and everything is working great except for this small issue. Started to move over edited RAW files from my Lightroom Cloud. Most of these files moved over fine but a few seemed to error out when generating the sidecar files and now display as gray or black boxes and the sidecar files are only a few kb each. If I unstack the RAW file from it's accompanying XMP file it generates a new sidecar image fine and the RAW files themselves are not corrupted in any way. 

Obviously the immediate solution would be to unstack all the RAW files or upload my own accompanying JPEGs but I am wondering if there is an edit from lightroom that causes the sidecar generation to error out so I can avoid this when moving the rest of my images over to my new installation and hopefully preserve edits. There were no messages in the library import log or the docker logs that seemed to indicate why this might have been happening

![pp issue](https://user-images.githubusercontent.com/83914258/117657042-a1041500-b188-11eb-96cf-50992ac04b3c.PNG)

**Comment by graciousgrey** [comment]
Could you send us a pair of raw + sidecar that shows this behaviour and a pair that can be imported without issues to hello@photoprism.app?

**Comment by mrdrblu** [comment]
Sent

**Comment by graciousgrey** [comment]
The problem is that darktable could not interpret the following cropping information from some xmp files:
`crs:CropTop="0.078"
   crs:CropLeft="0"
   crs:CropBottom="0.922"
   crs:CropRight="1"
   crs:CropAngle="0"
   crs:CropConstrainToWarp="0"`


The following should solve this:
- Disable darktable in settings (RawTherapee will be used then)
- Delete the black and grey jpgs
- Run convert command

**Comment by mrdrblu** [comment]
The above solution works!
