### ISSUE TITLE
Cloudron Support

### ISSUE THREAD

**Issue by moonmeister** [photoprism/photoprism#1284]
Okay, so I've spent a lot of time staring at docker builds and have one working for cloudron...well running. I ran into a couple issues and found temporary work arounds but their hacky and manual for now and permanent solutions should be found.

I started by copying the existing photoprism docker file and modified it to work on cloudron. This meant changing the base image, and modifying a couple other things. 

1.  My first major issue was realizing the build was happening on Ubuntu 20.10 and CGO was in use and thus when trying to run `photoprism` their was an error dynamically linking `glibc` (version mismatch). My temporary hack was to rebuild the development image on 20.04. ~~**Is there a better way than creating a dedicated build image for Cloudron purposes?**~~ See Below
2. Last night everything was building fine. This morning during the build failed durring the `dep-js` command. It was throwing lots of errors about `npm audit fix`. Removing this from the `dep-js` command resolved the build failure. **I'm guessing that command is there for a good reason, any thoughts on why this randomly started failing?**
3. Currently I'm configuring PhotoPrism via env vars. It appears in the documentation it can be done with a config file, but I'm not actually seeing documentation on what that config file would look like. **Can I get some direction here?**

Here's my working branch: https://github.com/moonmeister/photoprism/tree/feat/cloudron-image

The image I created is available at `moonmeister/cloudron-photoprism:0.1.3`

**Comment by moonmeister** [comment]
Addressing 1. above:

After doing some reading I realized I could use build arguments in the `Dockerfile` to modify 
the base image and use the existing development `Dockerfile` to build my focal based one. This solves that problem. 

Okay, So now that I have a good solution i see 2 paths forward. 

When building the Cloudron image of this we generate the focal based development bundle, we build PhotoPrism for focal, and then build the Cloudron specific image. 3 Cloudron specific steps. 

OR PhotoPrism decides it's worth while to always build an focal/LTS version of it's production docker image and then the Cloudron specific build can just copy the build artifacts out of that image. 1 Cloudron specific step. 

I don't think I particularly care 1 way or the other, it's up to your preferences. Let me know your thoughts. Thanks

**Comment by lastzero** [comment]
* We had to upgrade our Docker images to Ubuntu 20.10 to fix issues with FFmpeg and Darktable as updated packages were not available for  20.04. So when downgrading, those bugs will be there again.
* As you already noticed, it's a two stage build with a development base image and a production image that uses the base image for compiling / building.
* The error coming from dep-js / npm was fixed with a workaround: https://github.com/photoprism/photoprism/commit/5641203d1b0e1877c07b2cf44b759053bc4c08c0
* Instead of using the env variables, you may create a [config/options.yml](https://github.com/photoprism/photoprism/blob/develop/internal/config/testdata/config.yml) file containing your config values. Run `./photoprism config | grep config-file` to see the absolute file name.
* The YAML variable names can be found in https://github.com/photoprism/photoprism/blob/develop/internal/config/options.go. When you change options on the Advanced Settings UI, the the `options.yml]` will be written automatically using the right variable names. Note that the config file overwrites the env variables, so most users shouldn't use both at the same time as it may cause confusion.

Hope this helps!

**Comment by moonmeister** [comment]
Thanks!! 

Not sure if it's going to be possible to get a 20.10 Bose image for cloudron bit I'll look into it. 

If I can't, I guess I would have to do the work to compile/install those updated versions of FFmpeg and Darktable on 20.04 for cloudron. 

Thanks!

**Comment by lastzero** [comment]
I was trying to compile FFmpeg but gave up eventually due to the many dependencies for different codecs.

**Comment by moonmeister** [comment]
> I was trying to compile FFmpeg but gave up eventually due to the many dependencies for different codecs. 

Good to know!

**Comment by moonmeister** [comment]
Forgive me my ignorance. Is it possible to statically compile photoprism so the underling on doesn't matter?

**Comment by lastzero** [comment]
Yes, but a) that requires statically linkable libraries which you need to compile (may take weeks to figure out how) and b) this has software license implications you need to consult a lawyer for

**Comment by moonmeister** [comment]
*Do open source they said, it'll be fun* <= lots of satire and eye rolling. 

Lol, good to know.

**Comment by lastzero** [comment]
Note that we've upgraded our base image to Ubuntu 21.04 and applied a security patch for Exiftool on top of it.

**Comment by graciousgrey** [comment]
Any open questions left here? Or can we close this issue? :)

**Comment by moonmeister** [comment]
One last one, is there a plan to standardize on an LTS or at least support the LTS in addition to the latest Ubuntu release?

**Comment by lastzero** [comment]
We'd love to use LTS, and did so originally. It just wasn't possible to get bugs and security issues fixed in time, like the recent exiftool vulnerability. Wish Ubuntu would provide fixes faster for their LTS release.

**Comment by moonmeister** [comment]
Okay, Thanks all!
