### ISSUE TITLE
Incomplete Getting Started Information

### ISSUE THREAD

**Issue by oitconz** [photoprism/photoprism#1331]
Hi, 
I decided to give Photo Prism a run when looking for an alternative to CopperMine. I went the getting started page (  https://docs.photoprism.org/getting-started/ ) and started following the links on a brand new Ubuntu 20.4 LTS image. Other than apt-get update and upgrade it was bog standard. 

I went through the setup steps piece by piece and ran into several problems. 

1 - Lots of links to //photoprism/ ... in the yml file. If photoprism isn't in the hosts file as 127.0.0.1 photoprism this leads to failures. The yml file should probably be using localhost or 127.0.0.1:2432 to avoid issues caused by incorrect / impossible DNS resolution. MariaDB the same. 
 
2 - No where in the getting started steps does it say you need to install MariaDB using Docker-compose, the initial commands required to run it or links on how to install it. I just about went mad until I realised there was a gaping hole where MariaDB should be. So now I'm researching how to install mariadb using docker-compose (not docker) and figure out exactly what is required to get the DB it needs setup and running.  There is no info on this in the docs site.

As a getting started for an expert computer user, who had never used docker as he normally works on bare metal machines and using VM, I can say the getting started makes a ton of assumptions about what a user should know.  Even the requirements dont mention mariadb / mysql installed as a docker-compose image.   I meet all the requirements in the getting started but they are totally inadequate without having other dockers set up with DB etc in them. 

For a docker expert this product might work. For everyone else - its a dead end and huge frustration. Look at the questions out on the net with folks running into all sorts of issues trying to get started - and most are probably DNS (because the yml doesnt use localhost) and database docker issues. 

An update of a step by step, from the start, with localhost and no assumptions about mariadb and photoprism needing to resolve is probably needed.

HTH
Shane

**Comment by alexislefebvre** [comment]
Did you followed [this guide](https://docs.photoprism.org/getting-started/docker-compose/)? 

The [current default file](https://github.com/photoprism/photoprism/blob/2fb7a4d7ea151d86ca6bb2af48c8c03a8c3bfa0e/docker/examples/docker-compose.yml) is configured with MariaDB. Did you use another `docker-compose.yml` file?

**Comment by oitconz** [comment]
1 - Yes I followed that guide.
>. I went the getting started page ( https://docs.photoprism.org/getting-started/ ) and started following the links on a brand new Ubuntu 20.4 LTS image. 

2 - I used the default.yml file

I ended up with no MariaDB installed in docker.

**Comment by oitconz** [comment]
Look at line 61 of the docker yml file. you use a host name that needs DNS resolution for the connect string: 

PHOTOPRISM_DATABASE_SERVER: "**mariadb**:3306"     # MariaDB database server (hostname:port)

**Comment by alexislefebvre** [comment]
I don't understand how you couldn't have MariaDB if you use the file that use it. Please share your full `docker-compose.yml` (without the passwords).

Using a hostname is the common way to connect 2 services of a `docker-compose` stack, here the `photoprism` container will use the database from the `mariadb` container.

**Comment by lastzero** [comment]
@oitconz Please follow these instructions to install Docker and make sure to also install `docker-compose` via `sudo apt-get install docker-compose`:

https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04

If you do so, all you need is to download our docker-compose.yml example file from https://dl.photoprism.org/docker/ and run `docker-compose up` as shown in our docs. It's much easier than installing all dependencies manually and keeping them updated in case of bugs or security issues. If PhotoPrism can't connect to MariaDB, it's not related to the DNS as it should work out of the box. More likely the storage path is not writable so that mariadb fails to start.

If you're a developers and really want to install all dependencies on your own and compile them, check out our Developer Guide and run the instructions in our Dockerfile(s) manually: https://docs.photoprism.org/developer-guide/setup/
