### ISSUE TITLE
Suggestion: Add devDependency to minimize bundle size and increase performance

### ISSUE THREAD

**Issue by aldrinjenson** [photoprism/photoprism#1342]
Hey, the demo site appeared to be a bit laggy in my PC. Just took a look at the [package.json](https://github.com/photoprism/photoprism/blob/develop/frontend/package.json) and found that there was no devDependency section. 
Not sure if this was overlooked by some accident or if there's some other good reason, but currently AFAIU, all the packages for linting, bundling, formatting etc get loaded into the client in production. 

Making a devDependency key-value item in the package.json and moving the packages for webpack, babel, postCss, Sass, prettier and eslint(atleast) could give a noticable decrease in bundle size and hence an increase in performance I think. 
Not a Vue developer, so can't really test this right now but here are some references which may be useful:
https://medium.com/@stalonadsl948/dependencies-vs-devdependencies-926e096a3dee
https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file

If I'm missing something here, or if there's some good reason do let me know. Thanks
Btw, this is a great project. Best Google Photos alternative I could find. Kudos! :100:

**Comment by lastzero** [comment]
The production app.js should not contain any development tools as we're using webpack for building and don't include files directly from npm.

There's an issue for code splitting to reduce download size, but we're currently working on face detection and don't have time & resources for merging & testing so this has to wait sadly, see #841.

Download size should be acceptable on modern computers with fast internet. It's not optimized yet for older mobile phones and slow connections. Also keep in mind many people are testing our demo right now, so that might also be a reason.
