### ISSUE TITLE
Import: Syncthing's .stignore is deleted on import

### ISSUE THREAD

**Issue by HaroldDLeon** [photoprism/photoprism#1348]
Follow-up discussion from #1319 : 

When importing, Photoprism will delete the ```.stignore``` file from the folder, even if it's included on ```.ppignore```.

**Comment by AudunVN** [comment]
Can reproduce this on build `210523-b1856b9d`, looks like dotfiles are quietly deleted even if included in `.ppignore`. Below is a copy of the log from an import where the files were deleted.

> 2021-06-03 22:00:26 INFO Import completed in 7 s
> 2021-06-03 22:00:19 INFO import: ignored "phone/folder.ico"
> 2021-06-03 22:00:19 INFO import: ignored "phone/desktop.ini"
> 2021-06-03 22:00:19 INFO import: ignored "phone/OpenCamera/ppkeep"
> 2021-06-03 22:00:19 INFO import: ignored "phone/100ANDRO/ppkeep"
> 2021-06-03 22:00:19 INFO import: ignored "laptop/folder.ico"
> 2021-06-03 22:00:19 INFO import: ignored "laptop/desktop.ini"
> 2021-06-03 22:00:19 INFO import: ignored "drive/folder.ico"
> 2021-06-03 22:00:19 INFO import: ignored "drive/desktop.ini"
> 2021-06-03 22:00:19 INFO import: ignored "desktop/folder.ico"
> 2021-06-03 22:00:19 INFO import: ignored "desktop/desktop.ini"
> 2021-06-03 22:00:19 INFO Moving files from import

My `.ppignore` files contain

> \# ignore syncthing folders and files
> .stfolder
> .stversions
> .stignore
> 
> \# ignore folder metadata
> desktop.ini
> folder.ico
> 
> \# others
> ppkeep

and seems to be working fine except for `.stignore` being deleted.

In my case I have `.stignore` configured precisely since I don't want the ignored `desktop.ini` and `folder.ico` files mentioned in the import log to be there in the first place, as they're not much use on a headless Linux-based server and even less useful for Photoprism.

**Comment by alexislefebvre** [comment]
I think `.ppignore` is only used when indexing directories, not importing them. Maybe this part of the doc should be updated: https://docs.photoprism.org/user-guide/library/indexing/#ignoring-directories-and-files

**Comment by lastzero** [comment]
Should also work in import, maybe it's on the wrong directory level. If you import from a sub folder, the patent folders might not be checked. Can also be a bug, didn't have time to look at this in detail.

**Comment by AudunVN** [comment]
I think `.ppignore` not having an effect may not be the most important thing here. Dotfiles (and/or hidden files) being quietly deleted would come as a surprise after reading [the documentation](https://docs.photoprism.org/user-guide/library/import-vs-index/), as one of the listed advantages of importing instead of indexing is

> Unsupported files stay untouched in the import directory

which would make users expect that the unsupported file `.stignore` shouldn't be affected at all, regardless of whether a `.ppignore` file is set up. Not sure if this is a documentation or code issue, though.

**Comment by lastzero** [comment]
You're welcome to add a note to our docs. Most modern operating systems use hidden files to store folder metadata, so in practice deleting empty folder would never work and would likewise leads to complaints and bug reports.

**Comment by AudunVN** [comment]
Yep, I very much understand - bit confusing if seemingly empty folders are left behind on import if the user doesn't know about the hidden files. I'll see if I can add a note to the docs about all hidden files being deleted on import.

**Comment by HaroldDLeon** [comment]
> Should also work in import, maybe it's on the wrong directory level. If you import from a sub folder, the patent folders might not be checked. Can also be a bug, didn't have time to look at this in detail.

My folder structure looks like this:
```
Imports/
├─ DCIM/
│  ├─ .ppignore
│  ├─ .stignore
│  ├─ .stfolder/
│  ├─ .stversions/
├─ .ppignore
├─ .stignore
```
With ```.ppignore``` having only one line, which is ignored:
```
.stignore
```

Also tested adding other dotfiles to the folder and to .ppignore, but they were also deleted on Import.

**Comment by lastzero** [comment]
Did you try DCIM/.stignore?

**Comment by HaroldDLeon** [comment]
Yes. On import, the folder structure from above comment would change to:
```
Imports/
├─ DCIM/
│  ├─ .ppignore
│  ├─ .stfolder/
│  ├─ .stversions/
├─ .ppignore
```

**Comment by lastzero** [comment]
We can have a look after our vacation, in about two weeks. It's probably easy to fix.
