### ISSUE TITLE
Library count dropped, lost pictures, videos

### ISSUE THREAD

**Issue by varora1406** [photoprism/photoprism#1363]
I have self hosted photoprism.
I uploaded around 40,000 - 50,000 items
Last night it was uploading 10,000 more and suddenly overall count dropped to 19,000

Some of them went to "Review" section ~6,000
Some of them showing corrupted
But rest just vanished, how?

and what all details can I post here, so that it gets checked?

Current situation - 
![image](https://user-images.githubusercontent.com/24986539/121132636-0104de80-c84f-11eb-979c-6d43c0929873.png)

**Comment by lastzero** [comment]
Did you check the logs?

Maybe a storage or permission issue? Maybe some files could not be found or read?

**Comment by varora1406** [comment]
logs I see empty now, as my container I restart it many times
Notification for hidden folder is  - 
![image](https://user-images.githubusercontent.com/24986539/121397963-7c12e580-c972-11eb-9e34-bbc02fef8689.png)

**Comment by lastzero** [comment]
Please check your Docker logs as the PhotoPrism UI will only show logs since the last restart and you've mentioned that your container restarts frequently. You may find those in the admin UI of your NAS (if you use one) or you may open a terminal and then run this in the folder where your `docker-compose.yml` is (shows the last 50 log lines):

```
docker-compose logs --tail=50
```

When PhotoPrism restarts while indexing, this is often because there is not enough physical memory and no swap configured. This will kill the process when there are usage spikes. See our docs for recommended settings:

https://docs.photoprism.org/getting-started/docker-compose/

You may also limit the number of workers by setting PHOTOPRISM_WORKERS to a value less than the number of logical CPU cores in docker-compose.yml
