### ISSUE TITLE
Community and Pro Editions

### ISSUE THREAD

**Issue by SimonMGS** [photoprism/photoprism#1389]
I'd just like to check what the intentions are for the future differences between editions. In the past, I've been stung by committing to an open source solution, only for things to change, and the Community Edition to become crippleware in favour of the Pro edition. Are there any intentions to place restrictions on the Community Edition, or gate features for the pro version?

**Comment by lastzero** [comment]
The upcoming Pro version will be for commercial users with a focus on general Digital Asset Management rather than personal photo management. It may scale better in large cloud installations. Note that we're also running a backend and pay for maps to work, so we offer subscriptions for the community edition as well to cover our expenses. If you're a code contributor, we won't ask for anything. Hope this works for you.

**Comment by lastzero** [comment]
@SimonMGS Just wondering if you enjoy our crippleware so far or if you've found something better?
