### ISSUE TITLE
Map in "Places" displays Hebrew in left-to-right order and not right-to-left

### ISSUE THREAD

**Issue by shayaknyc** [photoprism/photoprism#1391]
Recently installed photoprism via docker-compose in a debian host environment - working great and it's been slowly indexing the photos. I have many photos geotagged in Israel, and all the Hebrew names of cities, etc are displayed with the Hebrew letters in left-to-right order, and not the proper right-to-left. For example, Petah Tikva is displayed in English properly, but the name in Hebrew underneath is displaying as:
הווקת חתפ

Instead of:
פתח תקווה

See screenshot:
![image](https://user-images.githubusercontent.com/13590551/123355365-8832a180-d533-11eb-8380-5a65bf7404b3.png)

Tried changing the different map types but it's all pulling from the same API. Weirdly, if you load up OSM directly, on their site it's displaying the proper right-to-left Hebrew names:

![image](https://user-images.githubusercontent.com/13590551/123355542-df387680-d533-11eb-9621-94a578f90c0e.png)
https://www.openstreetmap.org/#map=15/32.0173/34.7597

Wondering what could be the cause of this bizarre display. I can confirm that the Arabic is properly displaying right-to-left, so not really sure why Hebrew is displaying in reverse....

Any ideas?

**Comment by graciousgrey** [comment]
@haimkastner do you have an idea on how to fix this? :)

**Comment by haimkastner** [comment]
I checked this issue, and it's reproduced even if the browser and the machine interfaces are in Hebrew.

Seems to be a wrong configuration in the map component loading, I will dig into it to understand the issue root cause.

**Comment by dror3go** [comment]
This seems to be an issue in an underlying tiles service rather than PhotoPrism itself, isn't it?
I did find some related issues - however those are pretty old issues dated back to ~2017:
https://blog.mapbox.com/improving-arabic-and-hebrew-text-in-map-labels-fd184cf5ebd1
https://github.com/openmaptiles/openmaptiles/issues/171
https://github.com/maptiler/tileserver-gl/issues/112

**Comment by haimkastner** [comment]
Please review the fix on PR  #1393 

Seems that an RTL plugin is required in order to support RTL.

See the [RTL documentation of Mapbox](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/)

After adding it, the plugin is loaded by lazy only when Hebrew is shown on the map.

As you can see in my environment:

![image](https://user-images.githubusercontent.com/28386247/123698786-2fcb0f00-d867-11eb-9153-43adcaa733cb.png)

**Comment by lastzero** [comment]
Our development preview and demo should be updated. Is this fixed for you there?

**Comment by haimkastner** [comment]
Yes, the fix is there, and it looks good.

**Comment by lastzero** [comment]
Excellent, thanks for testing 👍
