### ISSUE TITLE
ERRO media: failed creating thumbnail

### ISSUE THREAD

**Issue by marecabo** [photoprism/photoprism#1407]
First, thanks for this awesome photo organizing app!

Some pictures (panoramas taken with a Samsung Galaxy S8 straight out of camera) unfortunately do not get indexed due to the following errors:

## Log

```log
ERRO media: failed creating thumbnail for 20210622_210415.jpg (EOF)
ERRO resample: EOF in 20210622_210415.jpg
INFO index: updated main jpg file “gallery/***/20210622_210041.jpg”
ERRO index: failed creating thumbnails for 20210622_210041.jpg (EOF)
ERRO media: EOF in 20210622_210041.jpg
ERRO index: media: failed creating thumbnail for 20210622_210415.jpg (EOF) in “gallery/***/20210622_210415.jpg” (detect colors)
ERRO media: failed creating thumbnail for 20210622_210415.jpg (EOF)
ERRO resample: EOF in 20210622_210415.jpg
WARN metadata: scan-data is unbounded; EOI not encountered before EOF in 20210622_210415.jpg (parse jpeg)
ERRO media: failed creating thumbnail for 20210622_210041.jpg (EOF)
ERRO resample: EOF in 20210622_210041.jpg
ERRO media: failed creating thumbnail for 20210622_210041.jpg (EOF)
ERRO resample: EOF in 20210622_210041.jpg
ERRO index: media: failed creating thumbnail for 20210622_210041.jpg (EOF) in “gallery/***/20210622_210041.jpg” (detect colors)
ERRO media: failed creating thumbnail for 20210622_210041.jpg (EOF)
ERRO resample: EOF in 20210622_210041.jpg
WARN metadata: scan-data is unbounded; EOI not encountered before EOF in 20210622_210041.jpg (parse jpeg)
```

Would it help you to have a look at some affected files?

## System
- Synology DS920+ @ Intel J4125, 20 GB RAM
- Linux DiskStation 4.4.59+ #25556 SMP PREEMPT Thu Mar 18 13:00:34 CST 2021 x86_64 GNU/Linux synology_geminilake_920+
- Docker version 20.10.3, build b35e731
- PhotoPrism latest Docker image from 2021-05-23 18:44:02

**Comment by lastzero** [comment]
Log output suggests it may be related to https://github.com/golang/go/issues/45902

**Comment by lastzero** [comment]
Can you verify your files are fully standards compliant, and not "broken" in any way? See comments in the golang issue referenced above.

**Comment by marecabo** [comment]
With [GraphicsMagick ](http://www.graphicsmagick.org/identify.html) and `gm identify -verbose 20210622_210415.jpg` from this https://github.com/golang/go/issues/45902#issuecomment-830653606, it returns 

```log
[..]
gm identify: Invalid SOS parameters for sequential JPEG (20210622_210415.jpg).
```

for both images in the end. :/

Is there a way to be more tolerant regarding such images, as any desktop image viewer or browser can show them without complaints?

**Comment by marecabo** [comment]
As a workaround: [ImageMagick](https://imagemagick.org) is able to resave these corrupted images with `magick mogrify -format jpg *.jpg`.

```console
user@machine:~$ magick mogrify -format jpg *.jpg
mogrify: Invalid SOS parameters for sequential JPEG `20210622_210041.jpg' @ warning/jpeg.c/JPEGWarningHandler/402.
mogrify: Premature end of JPEG file `20210622_210041.jpg' @ warning/jpeg.c/JPEGWarningHandler/402.
mogrify: Corrupt JPEG data: 64 extraneous bytes before marker 0xd9 `20210622_210041.jpg' @ warning/jpeg.c/JPEGWarningHandler/402.
mogrify: Invalid SOS parameters for sequential JPEG `20210622_210415.jpg' @ warning/jpeg.c/JPEGWarningHandler/402.
mogrify: Premature end of JPEG file `20210622_210415.jpg' @ warning/jpeg.c/JPEGWarningHandler/402.
mogrify: Corrupt JPEG data: 65 extraneous bytes before marker 0xd9 `20210622_210415.jpg' @ warning/jpeg.c/JPEGWarningHandler/402.
```

They then get indexed successfully by PhotoPrism and pictures appear to not have any visual differences.

**Comment by lastzero** [comment]
We didn't implement the JPEG standard ourselves in Go, Google did it. Ask them. See linked issue.

**Comment by GordonFreemanK** [comment]
In case someone else finds this thread by googling it like me. I had the exact same issue with panoramas and the Galaxy S8, it seems the S8 camera app saves invalid panorama files. I didn't try magick, but I got my images fixed with an open source application, [JPEGSnoop](https://github.com/ImpulseAdventure/JPEGsnoop). Just drag and drop a picture on the app, then menu Tools > Export JPEG and check the _Missing EOI: Force EOI_ option.

**Comment by maxime1992** [comment]
@marecabo have you found a way to run the command you shared but only modify files that have an error?

I've tried to run it on 2 files, one that is fine, and a second one that has the issue with `mogrify -format jpg *.jpg`

I've checked the md5 sum of both files before and after and it turns out that even the one with no error has a new md5 sum.

I'd like to preserve the images that don't need any change as is and fix the ones that need to be fixed of course.

From the logs:

```
md5sum *.jpg                       SIGINT(2) ↵
b799a22438b4b893798967593077b0a8  20220605_153151.jpg
75171ad4f47a883b97e73bced03a29c7  20220605_153254.jpg
 ~/Documents/perso/phone/test  mogrify -format jpg *.jpg                    ✔
mogrify-im6.q16: Invalid SOS parameters for sequential JPEG `20220605_153254.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
mogrify-im6.q16: Premature end of JPEG file `20220605_153254.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
mogrify-im6.q16: Corrupt JPEG data: 71 extraneous bytes before marker 0xd9 `20220605_153254.jpg' @ warning/jpeg.c/JPEGWarningHandler/389.
 ~/Documents/perso/phone/test  md5sum *.jpg                                 ✔
2773c640ab6236f55f2c7bbb59926cc9  20220605_153151.jpg
c102df43946222048b3083891df84c77  20220605_153254.jpg
```

we can see that there was only warnings for the damaged one even though the md5 hash changed for the other one as well. Any idea? I'd just like to be able to run this on thousands of pictures before uploading them to my photoprism instance

**Comment by maxime1992** [comment]
> We didn't implement the JPEG standard ourselves in Go, Google did it. Ask them. See linked issue.

@lastzero do you think you may implement this fix while waiting for it to be fixed upstream ? https://github.com/golang/go/issues/45902#issuecomment-1475552124

Seems like a 2 lines fix that would really be helpful. When uploading hundreds of pictures from trips I don't get any errors but silently all the panorama I've got are not processed and I'm only aware if i take a look into the logs. And to fix it myself it's pretty painful honnestly. Either have to spot them 1 by 1 and do it manually with a software on windows... Or by using image magick but I cannot run it in bulk blindly as it modifies files that are ok as well. So really a painful process and afraid to forget checking the logs for files that'd be missed. 

If the fix is applicable as easily as the one in the link above, it'd be a much apmreciated fix 🙏. If not I understand you've got other priorities :)

**Comment by lastzero** [comment]
Did you try our latest release? It includes improvements for this.

**Comment by maxime1992** [comment]
I did yesterday indeed as I thought there was fixes for this but it looks like I still have the issue. I tried with 230502-c405f6eff

Is that the one you're refering to ?

I still had this error

import: failed creating thumbnails for 2022/06/20220605_133307_83B2ACD0.jpg (EOF while decoding)

**Comment by maxime1992** [comment]
To [answer myself](https://github.com/photoprism/photoprism/issues/1407#issuecomment-1532123705), based on [this](https://github.com/photoprism/photoprism/issues/2463#issue-1284315053) I've been able to come up with the following command to find all the files which have an issue:

```
ls *.jpg | xargs -n1 /bin/gm identify -verbose | grep "Invalid SOS parameters"
```

And then, based on [this comment](https://github.com/photoprism/photoprism/issues/1407#issuecomment-873398316) you can run `mogrify -format jpg your-file.jpg` to fix only the ones which have an issue. I didn't want to run only `mogrify -format jpg *.jpg` as it was modifying pictures without issues as well.

Finally, for anyone reading this and interested in a fix, I've [opened a dedicated issue](https://github.com/photoprism/photoprism/issues/3363) so that we may not have to do this prior to uploading pictures.
