### ISSUE TITLE
photoprism exited with code 1

### ISSUE THREAD

**Issue by idefy** [photoprism/photoprism#1420]
I am trying to deploy photoprism with docker-compose on a Rapsberry Pi 4. I restarted from scratch several times, but I always hit this error.

> Creating photoprism ... done
> Creating mariadb    ... done
> Attaching to mariadb, photoprism
> mariadb       | standard_init_linux.go:228: exec user process caused: exec format error
> photoprism    | standard_init_linux.go:228: exec user process caused: exec format error
> photoprism exited with code 1

I've followed all steps here: https://docs.photoprism.org/getting-started/raspberry-pi/
I am still a novice in Linux, so it might be a right access or something else, but it's hard to figure out with this error.
I've tried looking on the web but no luck.
Any indication what is wrong ? What should I do to debug ?

The docker-compose.yml is pretty much as is except for the passwords and the  photo file path.

**Comment by lastzero** [comment]
Are you sure you've downloaded the `docker-compose.yml` config example from here?

https://dl.photoprism.org/docker/arm64/

It's important to use Docker images built for the Raspberry (ARM), for example:

```
mariadb:
    image: arm64v8/mariadb:10.5
```

**Comment by idefy** [comment]
Yes this is the one I downloaded : https://dl.photoprism.org/docker/arm64/docker-compose.yml

**Comment by lastzero** [comment]
Then it shouldn't show "exec format error" except you're running a 32 bit OS on your Raspberry Pi 4 (which has a 64 bit CPU).

You need to boot your Raspberry Pi 3 / 4 with the parameter "arm_64bit=1" in config.txt in order to use the image. Alternatively, you may run the image on UbuntuDockerPi (https://github.com/guysoft/UbuntuDockerPi). It's a 64bit Ubuntu Server with Docker pre-installed.

**Comment by idefy** [comment]
yes, that must be it, I checked and it is in 32bit. Thanks. Will do this.
