### ISSUE TITLE
Allow archiving photos on Album page

### ISSUE THREAD

**Issue by Extarys** [photoprism/photoprism#1433]
**Background:**
I imported a bunch of photos, folder by folder, creating an album for those folders to help me sort through them and use the album name as a note (location, date, event name). Once batch editing will be available I'll be able to easily edit all the pictures in the album.
But I noticed that I can only archive photos in the "Search" page, not when I view photos from the "Album" page. So I need to track down the photo in Search, archive it, go back to the Album I was in if I can't find any other in that area/date I need to archive, find another photo I don't need/like and repeat the process.

**Wish**
I would like the ability to archive photos from any page, not just the Search page.

**Comment by graciousgrey** [comment]
We do not provide the archive option in the context menu within albums intentionally because one might easily confuse it with the remove option which is red as well. Additionally too many options in the context menu are hard to display on small screens.

What you can do is search all photos of an album using `album:uid` as search term. 
Assumed your album has the url https://demo.photoprism.org/albums/aqoweu7vjjr0qxzz/berlin --> Searching for `album:aqoweu7vjjr0qxzz` will show you all photos of this album within search where you can archive photos.

Alternatively you might select all photos you want to archive within the album and then go to search (your selection will not disappear when you switch between sections) and then archive them.

**Comment by Extarys** [comment]
> Alternatively you might select all photos you want to archive within the album and then go to search (your selection will not disappear when you switch between sections) and then archive them.

Thank you very much! <3 This is the easiest way.
