### ISSUE TITLE
Labels on the images

### ISSUE THREAD

**Issue by monotok** [photoprism/photoprism#1445]
Hello,

I have been trying out a few different self hosted photo managers and so far I really like photoprism. One thing I liked with photonix is the images show rectangles around different objects that were detected in the image. It seemed pretty good and you could click off the image and it would disappear. 

Screenshot from their demo site.

![image](https://user-images.githubusercontent.com/9199049/126867257-4316ec73-377e-41c7-a285-a2896e2b96d0.png)

Do you think this is something that might be added?

Thanks very much.

**Comment by lastzero** [comment]
We can build this too, but using a model seemingly built for autonomous vehicles doesn't add much value to a photography app in my opinion - other than it looks cool as a proof of concept. How many and what types of objects does this support? All the examples I've seen so far are some form of vehicle... 

While we love to get feature requests, there are a ton of other features on our roadmap already that probably add more value for most users. So even if we do it, it has to wait until next year.

**Comment by monotok** [comment]
I assumed this would be a low priority as there would be many more important features. From what I can tell when photonix scanned my whole library (28k) it would do this for anything it could detect; eg the labels that get detected in photoprism. As far as I am aware they both use tensorflow. 
So for example, it would draw things like; women, man, clothing, wheel, rocks etc. It also does this for face recognition (yellow box).

I guess apart from being pretty cool; it allows you to see the labels without going to the edit tab.

**Comment by lastzero** [comment]
TensorFlow is just a general ML library, the models are vastly different in many aspects. While we use an "image classification" model, photonix uses an "object detection" model - which are typically trained with less labels for a more specific use case, like for autonomous vehicles (which also need to recognize people and rocks, so that cars don't crash into them). Adding support for additional models is something we will look into next year.

see https://www.tensorflow.org/lite/examples/image_classification/overview#uses-and-limitations

**Comment by monotok** [comment]
Arh, that makes sense. Thanks for clearing that up!
