### ISSUE TITLE
Calendar: Automatically hide months without (visible) pictures

### ISSUE THREAD

**Issue by SiJiL82** [photoprism/photoprism#1456]
After importing all my photos into PhotoPrism, I then archived some off that I didn't want included.
This has left some calendar months as having no non-archived photos in, and therefore show up just as black icons in the calendar view.
Reindexing the collection (or just the individual folder) doesn't remove these folders, leaving the calendar view looking less than pleasant.
Is there a way to force these to be hidden if there are no non-archived photos in that month?
![image](https://user-images.githubusercontent.com/65114782/128061840-05d9d343-a266-4782-9d47-b708635f226e.png)

**Comment by lastzero** [comment]
No, as the archive is for "deleted" pictures. Would be strange if they still show up. Private pictures won't be used as well as that may leak them unintentionally.

**Comment by SiJiL82** [comment]
I'm not sure what you mean by "Would be strange if they still show up" - the pictures don't show up, I don't want them to show up either?
I'm happy that folders are empty, what I'm after is to not make that folder show up at all, as if I'd never had any photos taken in October 2012.

**Comment by lastzero** [comment]
Sorry, I understood your problem was the "missing" preview image. Maybe we should exclude such months then - actually thought that is already the case. There might be a reason the implementation is like that. Already late over here and we're technically still on vacation. Taking a look later this week!

**Comment by SiJiL82** [comment]
Cool, thanks!

**Comment by abhilesh** [comment]
Just adding in, same thing happens when folders are auto-created under 'Places'/'States', 'Labels' and 'Moments'.
Sometimes the folders are auto-created based on incorrect tags, I manually edit the photos to correct the tags, the photos now move to the desired location but leave a blank folder with the incorrect tag.

Maybe hide/remove folders with zero elements?

**Comment by SiJiL82** [comment]
Happy to test this if needed - is there a way I can pull a docker image with the change in?

**Comment by graciousgrey** [comment]
Our preview images includes the changes. Alternatively you can test on our demo: https://demo.photoprism.org/browse
