### ISSUE TITLE
Fixed Search Bar

### ISSUE THREAD

**Issue by FeninSam** [photoprism/photoprism#146]
It would be awesome if the searchbar at the top is fixed so that it is always accessible even when scrolled down to the bottom.

![image](https://user-images.githubusercontent.com/28538716/66421549-b1d92b80-ea25-11e9-8a4c-e9e66316758d.png)

![image](https://user-images.githubusercontent.com/28538716/66421608-c9181900-ea25-11e9-802d-dcc0abf4dda2.png)

**Comment by Kudjo-Grand** [comment]
+1

**Comment by toasti2000** [comment]
+1

**Comment by lastzero** [comment]
We tested the app with fixed toolbar, but it wasted too much space on mobile devices - especially with additional search options. If you have a good solution for this, let us know.

**Comment by Kudjo-Grand** [comment]
Is there a way we could make it a toggle the user can select? Or maybe easy to "minimize" or "tuck away" to the side so it can get out of the way on screens that are too small?

**Comment by lastzero** [comment]
@Kudjo-Grand Yes, probably, but it takes a lot of time (days) to experiment with various concepts, users and devices. We don't want to be impolite, but users who want us to do this should seriously consider a donation or do this work themselves and send a pull request.

As it is right now, you really don't want to fix the toolbar and search form at the top and you also don't want the search form to scroll underneath a fixed toolbar. Note that we already close the extended search form on mobile devices on change so that the user saves a click.

![Screenshot 2019-12-30 at 10 37 47](https://user-images.githubusercontent.com/301686/71576338-9f383500-2af0-11ea-8b52-604575122109.png)

**Comment by lastzero** [comment]
The app bar is fixed now (on mobile):

![Screenshot 2020-06-24 at 16 41 03](https://user-images.githubusercontent.com/301686/85577456-880a7800-b639-11ea-95b4-6a06b0f88fe7.png)

In addition, there is a "scroll to top" button that saves time when going back to the search form.

The search form itself is not fixed as it would conflict with displaying search results:

![mobile](https://user-images.githubusercontent.com/301686/85577214-5691ac80-b639-11ea-955a-0cf6946ec3b3.jpg)

Let me know if this works for you :)
