### ISSUE TITLE
Question: Non-Docker Install instructions?

### ISSUE THREAD

**Issue by ekianjo** [photoprism/photoprism#1494]
Just a short question, is it possible to provide a non-docker setup guide?

**Comment by lastzero** [comment]
These would be our developer instructions:

  https://docs.photoprism.org/developer-guide/setup/

The basic strategy is to manually run the commands in our Dockerfiles. This will build a binary, even works on OS X and FreeBSD.

Note you'll need a long list of dependencies to use PhotoPrism with all features - and those will have security issues by design (darktable, exiftool,...). Many file parsers do, especially when written in C. It's not a secret, just check previously discovered bugs. Keep that in mind when running these types of apps without container. Docker is just a specific solution to separate them from your host OS, also one with a low performance impact e.g. compared to VMs.

We plan to provide packages for common Linux distributions. Currently not enough resources to test & maintain them properly, especially when Docker seems best for what we do for the reason mentioned above.
