### ISSUE TITLE
Face detection connects 2 different people

### ISSUE THREAD

**Issue by fonz-zz** [photoprism/photoprism#1497]
Hi,

I`m running the latest preview build to check out the face detection feature.  The issue I came across is that there are 2 people who are concidered the same.  If I change the name of the face detected it gets changed everywhere, also where the name was correct.

So I assume that in the background the AI thinks that these are the same faces.  I`m aware that this is just a preview build and not final but I would like to know what the plans are to deal with such situation in the final release?  Will there be a way to seperate these people and re-train the AI to avoid it to be a continous maual labour?  

I ran the same set on [photoview](https://github.com/photoview/photoview) out of curiosity and the 2 people in question get detected correctly as 2 seperate people. So it`s not that these are identical twins :-D Both are women with longer brown hair, but that is where the simularity ends.

**Comment by lastzero** [comment]
Facial recognition is still under development. Face "collisions" are getting marked to improve matching in the future. Also we improve clustering in general, e.g. by only using high quality face crops. This needs experimenting with lots of samples to find ideal parameters, and thus time.

Please don't report bad performance or recognizing the wrong person as bug at this point. Only actual errors, warning logs, or application crashes please! 👍

**Comment by fonz-zz** [comment]
sorry, didn`t mean to create a bug ticket, just wanted to give some feedback.  Thanks for the info

**Comment by lastzero** [comment]
You're welcome to use the chat for that! :)

**Comment by sassa4ras** [comment]
Rather than make a new thread I thought I would resurrect this, so apologies in advance if it would be better to raise this elsewhere:

I have twins who are near (but not completely) identical and thus pose a problem for ML algos. I have to do a lot of manual correction until the algorithm sorts them correctly (ie with Google Photos). With PhotoPrism, this was all going swimmingly until randomly it decided they were one and the same. Now, all 1000+ photos are tagged as only one person. Strangely, even when I remove and rename it will randomly drop my corrections and again cluster them together as one.

This seems like a bug. Even if the algorithm can't discriminate as you say because this takes fine tuning, it shouldn't reclassify those I have already tagged manually. That's incredibly frustrating. Shouldn't a manual tag override? 

Thanks in advance!

**Comment by lastzero** [comment]
@sassa4ras Indeed. If the embeddings (a numeric vector describing a face) of two faces are nearly identical, the existing assignments to the unique subject identifier are removed from the image marker (but the name you entered manually may still be in the database). This is to avoid unresolvable conflicts in case of accidental inconsistencies, e.g. due to a typo or other error.

An alternative would be to accept the conflict and disable automatic recognition for the affected faces. Users who don't have identical twins might not prefer that, though, so we need time to think about a strategy that works for everyone.

**Do you have any idea how the software could figure out if the conflict is intentional (because the faces really look the same) or due to a user/software error?**

**Comment by sassa4ras** [comment]
> **Do you have any idea how the software could figure out if the conflict is intentional (because the faces really look the same) or due to a user/software error?**

I think it may be a combination. The faces are clearly distinct enough that Google Photos, after some training, now correctly sorts the twins with near 100% accuracy. PhotoPrism did not suggest them as detected faces and I had to manually train a large set of around 75 before it started to automatically tag adjacent matches. I understand that it struggles with children due to models used, so this did not concern me. 

The only time the collision occurred was when I did accidentally tag one as the other (even parents do occasionally get confused). So, I presume the software then decided that the two separate tags were actually one and the same. After fixing that tag, one child disappeared but the association clearly remained somewhere in the database. What I mean, is that manually tagging other new photos now occasionally causes her to be restored as a separate person and all previously tagged photos are restored. Eventually though it collapses them into one person again, sometimes even when both are present in the same photo. 

Does that make sense?

**Comment by lastzero** [comment]
> The faces are clearly distinct enough that Google Photos,...

Fair enough. It's just that we don't have a team working full-time on facial recognition like Google, which is one of the most valuable companies in the world. Also, we don't have the source code of Google Photos or your photos to compare.

So I'm trying to figure out how to help you with what we have at hand...
 
> The only time the collision occurred was when I did accidentally tag one as the other (even parents do occasionally get confused). So, I presume the software then decided that the two separate tags were actually one and the same. After fixing that tag, one child disappeared but the association clearly remained somewhere in the database. What I mean, is that manually tagging other new photos now occasionally causes her to be restored as a separate person and all previously tagged photos are restored. Eventually though it collapses them into one person again, sometimes even when both are present in the same photo.

That's good to know, and we're trying to improve on that. However, when I look at what has happened, I'm not too surprised that this has never happened in all the months of testing we've done. That means without proper test images, it will also be time consuming and difficult to improve this. We could, for example, as a first step, create artificial images with artificial faces that fit the purpose. Or we could just develop something, release it, and see what happens.

**Comment by sassa4ras** [comment]
> Fair enough. It's just that we don't have a team working full-time on facial recognition like Google, which is one of the most valuable companies in the world. Also, we don't have the source code of Google Photos or your photos to compare.
>
> So I'm trying to figure out how to help you with what we have at hand...

Don't mistake what I'm saying. I totally understand the difference in resources and have no false notion about that. Simply that it is possible for both humans (me) and ML (Google) to tell them apart.

> That's good to know, and we're trying to improve on that. However, when I look at what has happened, I'm not too surprised that this has never happened in all the months of testing we've done. That means without proper test images, it will also be time consuming and difficult to improve this. We could, for example, as a first step, create artificial images with artificial faces that fit the purpose. Or we could just develop something, release it, and see what happens.

Totally. I understand that my case is a total fringe scenario. What I can't seem to understand is why it tries so hard to collapse them into one person. At a bare minimum, I would prefer that it doesn't *change* the tags that I apply. While time consuming, at least manually tagging them would allow me to index them accurately. 

Separately, how many images are necessary to train a model with reasonable fidelity?  I wouldn't mind feeding a few hundred of each of my children if that was able to improve the reliability in a scenario such as mine. Like most parents with a smart phone, I have more than a few photographs of my children.
