### ISSUE TITLE
Google PageSpeed Insights has some easy suggestions for page load times

### ISSUE THREAD

**Issue by kylrth** [photoprism/photoprism#1532]
My friends complained about slow load times, so I put a [shared album page](https://photos.kylrth.com/s/1js6edc2ik/aqzje5138jto05lu) through Google's [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/). Especially on mobile, it suggests I could drop as much as a third of my page load time just by enabling compression on the CSS and JavaScript files. It also complained that the site didn't provide cache times for the static supporting files. It seems like those two things would be easy to fix and make things a lot faster.

Feel free to run the page tester on my shared album if you want to see the other suggestions.

**Comment by lastzero** [comment]
The CSS / JS files are a bit large and should be split (known issue). However, they should be "compressed" already plus you can enable gzip compression via config option: `PHOTOPRISM_HTTP_COMPRESSION: "gzip"`

Browsers cache static content without providing explicit cache times. When people are loading the page for the first time, a cache doesn't help anyway. There's two JS files we explicitly don't cache as it is a best practice for progressive web apps. I've noticed the CDN provider we use for our demo adds additional cache headers, which may prevent caching under certain conditions (don't have time to investigate this in detail as I have a full todo list - let us know if it causes issues, so that the demo feels too slow for you).

**Comment by lastzero** [comment]
JS file is cached, also the page was loading super fast for me:

![cache-works](https://user-images.githubusercontent.com/301686/133735148-a3099348-1ead-4b7d-9579-172f4aa97d17.png)

**Comment by lastzero** [comment]
See:

**Demo: Server is slow #1351**

**Comment by srett** [comment]
With explicit (long) cache times the browser would keep it for much longer, surviving browser restarts, not just on a reload. On that same note, I was thinking about using a reverse proxy on a VPS with a fast connection to my PhotoPrism instance at home, so it could cache static content, or even transcoded and downscaled images, if appropriate caching directives are present in the headers. Then I could just set an upper limit for cache size on the VPS and have a fast(er) PhotoPrism experience on the go, while still having the actual instance running at home.

**Comment by lastzero** [comment]
Very long cache times for static frontend assents seem less of an advantage in practice once we release more often (again) as files will frequently change anyway. Image & video caching may be constrained by a general browser size limit rather than expiration as well.

We've spent a fair amount of time on performance improvements this year already will continue to do so once facial recognition is done.

**Comment by srett** [comment]
True, image & video caching would specifically only make sense with caching proxies like I envisioned, not for browsers.
