### ISSUE TITLE
People: Hide and Reveal Recognized People on Overview Page

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#1554]
**As user, I want to be able to hide a person on the people view, so that it is less crowded.**

Acceptance Criteria:
* The user MUST be able to hide a person from the people view e.g. using the context menu
* There MUST be a third tab "Hidden", hidden (and excluded) people are listed there
* The user MUST be able to undo hide

**Comment by lastzero** [comment]
Started a new Development Preview build for testing: https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by kvalev** [comment]
I have a minor usability suggestion for hiding faces. Instead of using the X in the top right corner, have a new option in the clipboard when face(s) are selected. For me personally it is more intuitive (and this is where I looked first). Initially I didn't even bother hovering over the X (which would have shown the tooltip), as I assumed that it will discard the recognized cluster.

**Comment by lastzero** [comment]
Thanks for the hint! We just released, so it's too late this time :)
