### ISSUE TITLE
Monitor Library folder for changes and Re-Index when changed

### ISSUE THREAD

**Issue by ajb3932** [photoprism/photoprism#1615]
If this or a way to do this already exists then I'm sorry, I am new to PhotoPrism!

I would like to just auto index new pictures by monitoring the originals folder and when a new picture is added run the index.

**Comment by lastzero** [comment]
This is available when using WebDAV to modify, add or remove pictures. Due to the nature of media files, it's a personal choice of each user how to keep the index updated otherwise. Indexing while files are being modified, added, or removed may lead to a long list of issues. Photos for example often have sidecar files. So we are not talking about single files but groups of files. When you index before a group of related files has be completely created or transfered, you'll get a wrong impression. In addition, media files can be very large, so the transfer may take hours. You may not want to index during that time, unless you're OK to risk it and are aware of the tradeoffs. Not that the filesystem is controlled by your server and you, it's not part of our app and not in our control. PhotoPrism has a better control over its WebDAV interface.

**Comment by lastzero** [comment]
Having said that, here is a scheduler example that will frequently index your pictures in the background: https://dl.photoprism.org/docker/scheduler/

**Comment by lastzero** [comment]
Note we've spent the last few days to improve our docs for you, the option to use a scheduler is now explicitly mentioned: https://docs.photoprism.org/getting-started/docker-compose/#step-3-index-your-library

**Comment by ajb3932** [comment]
Thanks for your useful comments. I will have a think about the infrastructure and how I want to move forward. 👍
