### ISSUE TITLE
UX: Fix cropping of navigation counters in Firefox

### ISSUE THREAD

**Issue by SiJiL82** [photoprism/photoprism#1616]
The Search and Places counts on the menu bar get cut off when displaying certain numbers:
![image](https://user-images.githubusercontent.com/65114782/136917175-f317552d-4cf2-4d22-bda3-7ea5dfacd2fb.png)

**Comment by graciousgrey** [comment]
On which browser do you observe this? And what kind of device?

**Comment by SiJiL82** [comment]
Firefox 93 on Windows 10

**Comment by SiJiL82** [comment]
Changing:
```
.v-list__group__header .v-list__group__header__append-icon, .v-list__group__header .v-list__group__header__prepend-icon {
	padding: 0 16px;
	-webkit-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
	user-select: none;
}
```
To:
```
.v-list__group__header .v-list__group__header__append-icon, .v-list__group__header .v-list__group__header__prepend-icon {
	padding: 0 14px 0 16px;
	-webkit-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
	user-select: none;
}
```
fixes it and still looks almost identical.

**Comment by lastzero** [comment]
Guess the real issue here is the inline scrollbar that shouldn't be there. Compare it with other browsers.

@moximoti Might be related to the CSS we've added for the user info at the bottom... what do you think?

**Comment by lastzero** [comment]
I can also see it with Firefox on macOS, although there is still enough space for me with 99999 pictures. Probably an issue with the scrollbar we've added for small screens. Since the space will run out anyway when somebody has like 9999999999999 pictures, we may want to shorten this e.g. "793.8k" instead of "793812" similar to what GitHub does with stars?

**Comment by SiJiL82** [comment]
Can confirm that on my same PC there is no scroll bar in Edge or Chrome, and the count text displays fine:
![image](https://user-images.githubusercontent.com/65114782/136987308-cc833fff-0601-45b7-91d0-48e03659784a.png)

And also that the scroll bar is there in Firefox but doesn't actually have anything to scroll:
![image](https://user-images.githubusercontent.com/65114782/136987238-602a9c29-7b06-4597-9f76-52b6e36c515a.png)

**Comment by SiJiL82** [comment]
The title's been changed to "Shorten large counts" but just shortening the count text won't fix the same thing happening for Places which is getting cut off with a count of 88.

**Comment by lastzero** [comment]
You're right, we'll take care of all this 👍

**Comment by moximoti** [comment]
> @moximoti Might be related to the CSS we've added for the user info at the bottom... what do you think?

We've less space through the scrollbar, indeed. But the problem lies in hardcoded pixel widths here: https://github.com/photoprism/photoprism/blob/5f931aba187e8c21b132ea4ec53fb3d389b3e8d2/frontend/src/css/navigation.css#L11-L18
We can get around this using flexbox here as well. 

Anyway, I love the idea to shorten counts additionally, as mentioned by @lastzero above.

**Comment by lastzero** [comment]
@moximoti You're welcome to implement your suggestions when you have a bit of time :)

**Comment by lastzero** [comment]
@graciousgrey Can you create a new idea for "shortening large counts the in the navigation"? The current fix should work for now, so there is no need to implement it short-term.

**Comment by graciousgrey** [comment]
https://github.com/photoprism/photoprism/issues/1639
