### ISSUE TITLE
Search: show number of results after query

### ISSUE THREAD

**Issue by spiezmaestro** [photoprism/photoprism#1646]
Tried to find my issue/idea, but did not find anything. It is not exactly #1582.

When I search (for example "face:new year:2012" and there are more than 50 results, the UI always just comes back with "more than 50 pictures found". I would like to get at least the number of results (maybe at the top of the screen), so I can determine if I want to make a more distinct search.

**Comment by lastzero** [comment]
- In practice this often means literally counting all results for each request, which can be a huge overhead compared to just fetching the first X results (there are shortcuts with indexes, but I don't want to go into specifics here).
- Also we fetch files from the database, but the frontend displays stacks of files by default. So the numbers wouldn't match what the user sees.
- Then the count sometimes changes every second, for example while indexing. So the numbers would be wrong. 
- The numbers can also be wrong because of database specifics e.g. if you fetch the count as part of the main query or in the separate query. If you do a separate query, the index may have changed in the meantime, so count and actual results don't match.
- A query might execute slightly different for just fetching the count and thus lead to a different result. I've seen it all.

I could go on like this, but I guess you get the point. We've chosen to go for simplicity & performance and don't show potentially wrong numbers, also because this has often led to bug reports in the past (on other pages) as most users are not aware the number is not 100% precise due to many reasons of which I've tried to outline a few above.

**Comment by lastzero** [comment]
Once we added support for Solr or Elasticsearch, this will be much easier to implement BTW. What I wrote above relates to the current SQL-based search.

**Comment by spiezmaestro** [comment]
Thanks, seems like a thought over approach.

**Comment by lastzero** [comment]
I'll close this as we'll implement it anyway when possible.
