### ISSUE TITLE
Remote Sync:  should have a more informative progress indicator.

### ISSUE THREAD

**Issue by LexiconCode** [photoprism/photoprism#1738]
**Is your feature request related to a problem? Please describe.**

Remote Sync should have a more informative progress indicator. It's progress bar only indicates that the webpage is responsive. 

![image](https://user-images.githubusercontent.com/24551569/142484836-34ce630a-283e-4a83-9e34-2d460c69e1b4.png)

**Describe the solution you'd like**

An enhancement would be to include file names being processed or a percentage of total total progress. Perhaps indicating uploading or downloading as well during the sync process.

**Additional context**

Total progress might be a little more difficult depending on how the backend (WebDAV, and so on) works. However filename should be low hanging fruit in this context.

**Comment by graciousgrey** [comment]
This is not meant to be a progress bar for the remote sync. It just shows that PhotoPrism is looking what folders exist remote.
It wouldn't add much value to add a progress bar in this dialog, as most of the time it won't be open when syncing happens in the background.

In case you have debug mode (https://docs.photoprism.org/user-guide/settings/advanced/#debug-logs) enabled you should see logs about syncing within the logs section (https://demo.photoprism.org/library/logs). Let us know if you miss information within these logs. Otherwise we can close this issue.

**Comment by LexiconCode** [comment]
Thanks for the clarification!  I will close for now and reopen if there's any other information to add.
