### ISSUE TITLE
Config: Change worker limit above physical CPU core count

### ISSUE THREAD

**Issue by hendrikcech** [photoprism/photoprism#1759]
**What does not work as expected?**

The number of worker threads that is used for, e.g., indexing, is determined by `func (c *Config) Workers() int` in [internal/config/config.go](https://github.com/photoprism/photoprism/blob/9da2e92fb603057cf7e2e596391e88db161d2bbc/internal/config/config.go#L458). The function works such that the number of workers may never be greater than the number of physical CPU cores (line 478).

While this seems to make sense on first sight, I would argue that it does not for the case of indexing. At least on my machine, the performance of indexing seems to be limited by disk I/O and not by the CPU. During indexing, the I/O rate of photoprism is only around 10-15 MB/s while the utilization of the two CPU cores hovers between 50-90%.

I would like to experiment with increasing the number of workers as this could improve the performance of indexing: more workers might lead to a higher I/O rate.

**What behavior do you expect?**

Change the referenced code in `config.go` such that the configured amount of workers is actually respected. 

**What version you are using?**

I'm looking at the latest commit (9da2e92fb60305) and run Photoprism on a server with 8 GB of RAM, a dual-core Intel CPU and spinning disks. 

Thanks for all your work!

**Comment by lastzero** [comment]
That's unusual, users reported the exact opposite in the past which is why constraints and defaults are as they are:

- https://github.com/photoprism/photoprism/issues/165
- https://github.com/photoprism/photoprism/issues/291
- https://github.com/photoprism/photoprism/issues/294
- https://github.com/photoprism/photoprism/issues/1390
- https://github.com/photoprism/photoprism/issues/835
- https://github.com/photoprism/photoprism/issues/1172

While we could allow this in combination with the `PHOTOPRISM_UNSAFE` flag, it looks like I/O seems the primary issue here. Unclear if it would really help or cause other issues then. Constraints work as designed, so not a bug from my point of view.

When we have a bit of time, we may relax constraints if `PHOTOPRISM_UNSAFE`  is set. Are you a sponsor?

**Comment by hendrikcech** [comment]
Thanks for collecting the related issues, I was unable to find similar reports. I'm not a sponsor.

If I have a bit of time, I will change the code locally to see if it makes a difference. I will close this issue for now and report back if I come up with meaningful findings.
