### ISSUE TITLE
  How can I build a development environment on my local Mac?

### ISSUE THREAD

**Issue by pengshuangbao** [photoprism/photoprism#176]
How can I build a development environment on my local Mac? GoLand app and vscode are installed locally. Thank you very much.

**Comment by lastzero** [comment]
Hello @pengshuangbao, did you read our [Developer Guide](https://github.com/photoprism/photoprism/wiki/Getting-Started)?

It's actually quite simple if you use Docker - and you should use Docker, so that you have the same environment as other developers. Otherwise you don't really know if your code works.

**Comment by pengshuangbao** [comment]
Yes, I just saw it. I'll try it now. Thank you very much!

**Comment by oziee** [comment]
on my mac i just type in `make` and it makes the app and works fine

**Comment by lastzero** [comment]
Well, you need to have Make, Go, NodeJS, NPM and TensorFlow for C 1.14 installed

**Comment by lastzero** [comment]
Closing this since there was no more feedback. Do the thumbs now work for you @oziee?
