### ISSUE TITLE
Support for Apple Live Photos

### ISSUE THREAD

**Issue by ryandeussing** [photoprism/photoprism#177]
Apple Live Photos is a sneaky little feature that has gotten under my family's skin and they now do not want to live without it. They expect to be able to see Live Photo animations and toggle them in some way.

Including support for Live Photos would remove a possible friction point in getting Apple customers to embrace photoprism.

**Comment by lastzero** [comment]
Can you figure out (google) what format this actually is and how we can read it?

**Comment by lastzero** [comment]
Seems like we need to add support for videos in general first as a live photo [technically](https://www.blackbagtech.com/blog/confirm-apple-live-photos/) is a regular photo plus a video file:

> Live Photos are generally made up of a .jpg image combined with a .mov video file. When using an iPhone 7 and above, and the user has set their device to take high-efficiency HEIC/HEVC pictures and videos (Settings➔Camera➔Formats); Live Photos will be saved with an .HEIC picture but still retain a .mov file for the video portion.

I didn't take many live photos and now primarily use a Huawei P30 because of its superior camera. Can somebody provide one or two small test files (with reduced resolution if possible)? See https://dl.photoprism.org/samples/.

**Comment by iicky** [comment]
@lastzero Here are two sample Live Photos with both the `.heic` and the `.mov` files from my iPhone X.

[iPhone X Live Photo Samples.zip](https://github.com/photoprism/photoprism/files/4048676/iPhone.X.Live.Photo.Samples.zip)

**Comment by lastzero** [comment]
Excellent, thank you very much!

**Comment by lastzero** [comment]
@iicky Uploaded to https://dl.photoprism.org/samples/iPhone%20X/ - hope that's ok for you!

**Comment by iicky** [comment]
@lastzero Yep, no problem - made sure there was no personal info on them. Happy to help.

**Comment by alxjsn** [comment]
Continuing the conversation from #17 here

1. Some live photos are still appear as videos. That probably has to do with the length detection. According to [Take and edit Live Photos](https://support.apple.com/en-us/HT207310), the length of a live photo can be up to 3 seconds long, so maybe that should be extended and/or check if the video was shot on an iPhone.

2. I think it would be good to hide live photos from the videos section completely, or at least to have an option to control this behavior. Thoughts?

3. As for how to handle UI for live photos. Instead of showing a play button, how about when it's detected as a live photo we show a different icon in the corner that says live photo? That way when you click on a photo normally it's a still and when clicking the small live photo icon it opens up the video. The main thing I want is to be able to distinguish between videos and live photos since the majority of the time I want to see a live photo as a still.

On the topic of how to detect whether it's a live photo maybe we should check for either all or one of the following:

1. Video is associated with photo
2. Video is max 3 seconds
3. The device is an iPhone

**Comment by lastzero** [comment]
Just noticed that iPhone X uses hvc1 instead of avc1 for Live Photos, so we can't play them without transcoding:

![Screenshot 2020-05-18 at 13 29 28](https://user-images.githubusercontent.com/301686/82208339-a333ea80-990b-11ea-8674-63aa608d9140.png)

**Comment by lastzero** [comment]
Build status: https://travis-ci.org/github/photoprism/photoprism/builds/689610465

Please re-index all files so that updated media type information is available. Sorry for the inconvenience.

**Comment by lastzero** [comment]
FYI: Newer live photos that are not MP4 are not supported yet. Not sure when and why Apple changed the codec.

**Comment by elboletaire** [comment]
AFAIK, the HEVC format is the video format directly related to HEIF (the .heic pictures' format). I guess their motivation was, not only to match codecs, but also due to the high compression ratio that HEVC offers vs the h264/mp4 one.

BTW can't wait to have this fully functional in photoprism. I also do take and store my pictures in heic format since it was first released, and I stumbled upon this issue due to the already mentioned problem with the current format.

**Comment by lastzero** [comment]
@elboletaire In order to show HEIF images in a browser, we have to convert them to JPEG. While HEIF may need less storage on a phone, most users will need more on their NAS / home computer as photos have to be kept it in two formats instead of one. Not a big issue as disks are cheap, but "advantage" is always relative and depends on the use case.

We plan to add support for additional codes after our first release, so that it doesn't get delayed even more :)

**Comment by elboletaire** [comment]
Yeah I know that. Happens exactly the same with videos in HEVC: if you wanna stream them, you gotta transcode them to formats supported by your browser.

I'm not really sure browsers will soon support hevc format, though... I'm afraid some browsers won't ever adopt it, due to its patents. We should really be moving to AV1 instead (which [is already supported in most mainstream browsers](https://caniuse.com/#feat=av1)), but most video-encoding programs don't support it, and they just added hevc support recently.. so I guess it will be a really slow movement, like many others in these lands.

Getting back to photoprism, I'd love being able to select between converting stuff and transcoding it by default. Even though disks are cheap, I'd prefer transcoding images every time I visit them with my browser instead of saving copies (obviously I'm not talking about thumbnails but the full-sized image). But I guess that should be a new issue :)

**Comment by lastzero** [comment]
> But I guess that should be a new issue :)

Yes, please :D

On the fly resampling is somewhat slow / demanding for CPUs when using high quality / photographic filters like Lanczos or Blackman, which I would absolutely recommend if you love your photos (makes a HUGE difference to me):

https://github.com/photoprism/photoprism/wiki/Thumbnails#lanczos

**Comment by jscmidt** [comment]
How can I upload Live Photos in Safari on iOS? When selecting Live Photos only the image part is uploaded, without the video.

**Comment by graciousgrey** [comment]
@jscmidt It looks like Apple only uploads the jpeg part of the live photo. I don't know if we can solve this in PhotoPrism or if there are settings that change this behavior. In any case, sync apps like PhotoSync can sync Live Photos without any problems. For further questions please use [Github Discussions](https://github.com/photoprism/photoprism/discussions). Thank you :)
