### ISSUE TITLE
WebDAV: Reset error flags/counters after transient failures

### ISSUE THREAD

**Issue by daniel-callejas-sevilla** [photoprism/photoprism#1781]
WebDAV sync (from a Nextcloud source towards PhotoPrism) gets permanently blocked once a file download fails more than three times. There is no way to have it resume (even when removing the offending file from the Nextcloud source). Once this "failed more than 3 times" state is reached, Photoprism will not attempt any further WebDAV exchange even after restarts. Disabling the sync in settings and enabling it back again does not help.

Additionally, this "will not try ever again" mode is fully invisible in the UI and info logs, and can only be detected with debug logs. The info logs give the impression that the sync is starting.

Workaround: delete the whole WebDAV server from settings and add it back again. Synchronization then resumes normally.

Expected behavior: Photoprism continues to attempt synchronization forever. If a specific file fails to be retrieved more than _X_ times, the user is informed, and Photoprism continues to attempt synchronization anyway, at the scheduled interval (PHOTOPRISM_WAKEUP_INTERVAL).

Offending log lines:
```
photoprism_1  | time="2021-11-29T21:53:07Z" level=info msg="sync: downloading from Owncloud"
photoprism_1  | time="2021-11-29T21:53:07Z" level=debug msg="sync: downloading /photoprism_root/telephone_dani/NextcloudInstantUpload/DCIM/2019/12/VID_20191224_010317.mp4 failed more than 3 times"
```
(That specific file failed to download hours earlier due to a transient issue with my Nextcloud server. That file was then removed from the Nextcloud source and did not exist anymore at the logged timestamp.)

Edit: Running PhotoPrism® 211010-83b4f783-Linux-x86_64

**Comment by lastzero** [comment]
Thanks for your report!

**Comment by lastzero** [comment]
Have you considered mounting the files directly, without WebDAV?

**Comment by daniel-callejas-sevilla** [comment]
> Have you considered mounting the files directly, without WebDAV?

Not possible in my setup. Only possible access is through WebDAV.

**Comment by lastzero** [comment]
The proper solution to your problem seems mounting your Nextcloud files with `davfs` then:

- https://manpages.ubuntu.com/manpages/impish/man8/mount.davfs.8.html

It's [included in our Docker image](https://github.com/photoprism/photoprism/blob/develop/docker/photoprism/Dockerfile#L39).

Consistency, availability, and partition tolerance are hard problems in computer science we can't simply solve as a reaction to your issues (wish we could, but no... there's tradeoffs everywhere):

- https://en.wikipedia.org/wiki/CAP_theorem

If you know how to use SQL, you can manually reset the error counter in the related database table columns. It's also possible to write a script for that.

We may eventually improve our WebDAV client implementation and add more UI tools for your convenience, but that's out of scope near term looking at all the other feature requests. Maybe Nextcloud can sync its files with PhotoPrism instead? Or you could switch to PhotoPrism with all your photos. The WebDAV server is much faster than Nextcloud, which makes syncing your phone a breeze.

See also:
- #1785
