### ISSUE TITLE
Docker: Provide 32-bit ARMv7 Build

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#1815]
The build for  `photoprism/photoprism:armv7`  is currently failing due to an issue in the network stack. We are working on a solution.

You can use the previous multi-arch image `photoprism/photoprism:20211203` meanwhile.

**Comment by lastzero** [comment]
Seems to be fixed with these changes:
- https://github.com/photoprism/photoprism/discussions/1813#discussioncomment-1811417

ARMv7 image is now built on ARM64 hardware. Build previously failed when using the qemu emulator on our regular AMD / Intel servers. We still don't know what is causing this.

**Comment by zierbeek** [comment]
something that could help? I know on mealie we are also running into errors with build for arm v7

Arm/v7 Support
Mealie will no longer build in CI/CD due to a issue with the rust compiler on 32 bit devices. You can reference this issue on the matrix-org/synapse Github page that are facing a similar issue. You may still be able to build the docker image you-self.

https://github.com/matrix-org/synapse/issues/9403

**Comment by lastzero** [comment]
Problem could as well be something like that in `golang.org/x/crypto`... just [came in](https://cs.opensource.google/go/x/crypto/+/e495a2d5b3d3be43468d0ebb413f46eeaedf7eb3:cryptobyte/asn1.go;dlc=4570a0811e8b3d7c89573c13d00777b1f8b01a54):

![32bit](https://user-images.githubusercontent.com/301686/146384927-2e609bc7-92a9-42ff-83ca-35b3a00e3c7e.png)
