### ISSUE TITLE
Idea: Extract subject from relative path to create albums

### ISSUE THREAD

**Issue by kmcs** [photoprism/photoprism#184]
Lovely project!
I currently organized my photo collections with folders like the following:
/[year]/[subject]/[image].jpg
example:
/2019/Berlin Holiday/IMG12412.JPG

It would be nice if I cloud define an regular expression to extract such information like subject from the path and automatically create albums, categories or labels with that subjects while indexing the images.

Maybe someone can point me to right location in the source code to implement that feature?
Thanks,
Timo

**Comment by lastzero** [comment]
Filenames and directories are something we want to experiment with more, it's somewhat difficult to use classifications or other information as filename because

a) You must be sure file names are unique, otherwise you'll get conflicts.

b) Information, such as subjects, might change. Then you need to move files around which might confuse other software that still knows the old location.

**Comment by lastzero** [comment]
Would be easy to do this as an export, e.g. as zip file for sharing, though.

**Comment by kmcs** [comment]
I don't know if you got my idea right.
I mapped my Image folder to the prism docker container and started the Index command. After that i wan't to see some where in the frontend as label, category or album the information from the image path.
My solution thoughts are:
extract a string from the image file path with an regex and use this string as a new Album Name, create album If not exists, add the Image to the album. remove from old album if it was already indexed. Do this while indexing.
Thanks

**Comment by lastzero** [comment]
I see... we already index the filename and path, just don't do anything with that information because we had other priorities like geodata, performance,... but we'll get to that.

A relatively simple solution would be to use strings in dir / file names for full-text search or as labels, in your example:

1. 2019 -> Would be ignored because it's a number
2. Berlin Holiday -> Could be indexed as label "Berlin Holiday" or the words "Berlin" and "Holiday"
3. IMG -> Would be ignored because it's in the stop words list
4. JPG -> Would also be ignored because it's in the stop words list

A more complex solution would be to allow user defined regular expressions or guessing if the word is a place, a time or a person and then categorize it accordingly.

**Comment by lastzero** [comment]
Added indexing of non-canonical file names and paths, see https://github.com/photoprism/photoprism/commit/1c592464bf618f3846ef1d153dcaeef938803ea6

**Comment by lastzero** [comment]
Would it make sense to extract keywords from the file / path and put them in a "keywords" field where the user can see and edit it? Obviously it doesn't make sense to edit the original (or even the current) filename after import, especially when PhotoPrism doesn't have write permissions. That means the user currently can not modify / remove those keywords.

**Comment by guysoft** [comment]
I would suggest adding some plugin or tool that interacts with the API.
You tell it to iterate over all the images you want, and it looks at the folder path, and then updates the date according to any rule you want.

**Comment by lastzero** [comment]
You could use full-text search and add the results to an album, unless you want every folder 1:1 as album.

**Comment by lastzero** [comment]
Any more feedback, opinions or bugs related to this?

Might be done given the fact we now extract keywords and dates from file and path names. There are separate issues for automatic album creation and browsing by folder name.

**Comment by lastzero** [comment]
You can now filter by directory like `path:/`, `path:2019*` or `path:2019/05`

Shall we add "folder" as an alias for "path"?

Filtering by name is also possible: `name:IMG_*`

To use multiple values, separate the strings like `path:2019,2020` or  `name:IMG_123,IMG_124`.
You can't combine wildcards with multiple search strings yet.

**Comment by lastzero** [comment]
Closing this since we received no more feedback.
