### ISSUE TITLE
Security: Changing password doesn't invalidate existing auth tokens

### ISSUE THREAD

**Issue by mcginty** [photoprism/photoprism#1935]
First - great project, thank you so much for this.

I launched a new instance of PhotoPrism with an admin password that I also gave to a friend, but then I changed the password, expecting that this would not only stop them from logging in, but that they would no longer continue to be logged in. Instead, they remained logged in and authenticated as an admin.

The expected behavior for me would be that changing the password would invalidate all previous auth tokens (besides, perhaps, the session that is doing the resetting).

An alternative would be to have a checkbox to log all other sessions out when resetting the password.

**Comment by lastzero** [comment]
1. You're right, the tokens do expire, but they don't automatically become invalid - in part because the account isn't meant to be shared unless you trust the people and don't want to revoke access.
2. This is a known limitation. We are sorry if this was not communicated clearly enough, and we welcome improvements to the documentation.
3. You can manually delete the `sessions.json` file in the storage / config folder to reset all sessions.
4. We are currently implementing full multi-user support, which will be released as soon as we deem it safe and stable (see [public roadmap](https://github.com/photoprism/photoprism/projects/5)).

**Comment by mcginty** [comment]
@lastzero I'd argue that if one changes a password it might be because it leaked in some way that an attacker might have used to gain access, thus invalidating the existing tokens would make sense, regardless of if the account is meant to be shared or not.

It's a feature of authentication that would also apply to the upcoming multi-user support, but isn't mitigated by having multiple users since their password changes might also happen with the intention of locking out those who may have gotten unauthorized access.

**Comment by lastzero** [comment]
As I've said, you can already do this manually. Give us a bit of time to work on the new features. I'm celebrating my birthday this weekend and won't be working. Everyone is invited to help us and sponsor us.

**Comment by FlorianCassayre** [comment]
The manual solution seems good enough for now, thanks for pointing it out.
I was afraid that the tokens were stateless, which would have made impossible the revocation of an existing session.

**Comment by lastzero** [comment]
Note that this is solved and should work automatically with the upcoming release. It is also explicitly mentioned in the change password dialog.
