### ISSUE TITLE
Logs constantly showing "has ambiguous subject" and "failed removing merged clusters for subject" errors?

### ISSUE THREAD

**Issue by drinn** [photoprism/photoprism#1975]
I just installed photoprism yesterday. Things appear to be working OK. I started playing around with the "People" section today and the interface seems rather slow when trying to correct/add/remove people from photos.

Looking at the logs, I'm seeing constant messages of:

level=warning msg="faces: XICN364AMGJKJX6F4LI6OOIM62GPF47V has ambiguous subject jr67tqm1c9kczt98"
level=warning msg="faces: failed removing merged clusters for subject jr67tqm1c9kczt98"
level=warning msg="faces: YU3BK2KL7M5ZU7CP5NHXZLU7JT3HMIO2 has ambiguous subject jr67tqm1c9kczt98"
level=warning msg="faces: failed removing merged clusters for subject jr67tqm1c9kczt98"

The part preceding the "has ambiguous subject" changes occassionally, but the subject target of "jr67tqm1c9kczt98" always appears to be consistent. I'm not sure if the UI is slow in trying to deal with these errors all the time or what the cause might be? Any ideas?

**Comment by graciousgrey** [comment]
Is your indexer still running?

**Comment by drinn** [comment]
It's not searching for new files in my library if that is what you mean? After the initial index finished, I was trying to correct the faces that it identified incorrectly or not at all. And that's when I noticed photoprism would hang sometimes when modifying entries. Checking the logs during these periods of slowing down is when I noticed those warnings.

**Comment by lastzero** [comment]
Did you try running the "faces audit --fix" command in a terminal yet?

```
docker-compose exec photoprism photoprism faces audit -f
```

**Comment by lastzero** [comment]
As you can see here, this is just a warning that no face embeddings can be removed because very similar faces match different people:

https://github.com/photoprism/photoprism/blob/58a5f940694446958e5cd4b869bea1d2bf9aaf98/internal/query/faces.go#L160


What faces and people could that be? We do not know.

- Maybe you use different names for the same person? This could trigger such a warning.
- Without seeing the actual images and associated data, it's fruitless guesswork and mainly a case for technical support, for which GitHub Issues is the wrong place.
