### ISSUE TITLE
Raspberry Pi: Document setup steps for PhotoPrismPi  and ensure image stays updated

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#2275]
**As an inexperienced Raspberry Pi 4 user, I would like to have a foolproof way to run PhotoPrism on my device without having to figure out any details.**

PhotoPrismPi is a ready-to-use SD card image for the Raspberry PI 4. Running this is often much easier than getting Docker & PhotoPrism to work on Raspberry Pi OS (Raspbian). For all the the reasons, see:
- https://docs.photoprism.app/getting-started/raspberry-pi/#raspberry-pi-os

It would be good to mention this in our official docs so potential users can find it. Also, it would be great to set up a GitHub action to update the base image from time to time to keep the number of security issues low and the Linux/Docker base version compatible. Even a simple shell script that we can run automatically would suffice if it is tested and works reliably.

*Getting Started Guide > Raspberry Pi*
- https://docs.photoprism.app/getting-started/raspberry-pi/

*SD Card Image Repo*
- https://github.com/guysoft/PhotoPrismPi

**Comment by GideonStowell** [comment]
I find myself with some time to contribute. Point me to any additional documentation and I would happily take a crack at this.

**Comment by GideonStowell** [comment]
@lastzero I have made some changes in the docs repo but don't have permissions to push my branch to origin. If you allow that for me I can create PR with my changes.

**Comment by graciousgrey** [comment]
@GideonStowell there should be no permissions needed to create a pull request :)

**Comment by GideonStowell** [comment]
@graciousgrey I'm talking about permissions to push a feature branch. 

```
# photoprism-docs/docs on feature/photoprismpi-documentation 
> git push --set-upstream origin feature/photoprismpi-documentation
ERROR: Permission to photoprism/photoprism-docs.git denied to GideonStowell.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by heikomat** [comment]
@GideonStowell  as @graciousgrey said, there is no need for any permissions at all to create a PR.
To create a PR you must
1. fork the repository
2. clone the fork
3. create a new branch on your fork (optional)
4. Do the changes you want to do
5. Push your changes to your fork

After these steps, Github will allow you to open a new Pull Request with the upstream photoprism repo as base, and the branch on your forked repo as the branch to merge.

Giving people direct push-access to the photoprism repos would most likely result in chaos, because everyone could just push whatever they wanted.

**Comment by GideonStowell** [comment]
Thanks, it wasn't clear to me that was the suggested workflow before. Make sense now.

**Comment by GideonStowell** [comment]
After reviewing the work completed are there any objections to closing this issue?
