### ISSUE TITLE
Docker: Do not CHOWN Originals Directory

### ISSUE THREAD

**Issue by BonzTM** [photoprism/photoprism#2369]
**Is your feature request related to a problem? Please describe.**

The Originals directory is mapped from an external location through container volume mounts.  The path to originals is `/photoprism/originals`.  The `endpoint-init.sh` script chowns the originals directory, causing my external mounted originals folder to have incorrect permissions and problems.

https://github.com/photoprism/photoprism/blob/develop/scripts/dist/entrypoint-init.sh#L20

**Describe the solution you'd like**

Exclude `/photoprism/originals` from `endpoint-init.sh` script or default originals to a different path that isn't affected.

**Describe alternatives you've considered**

I have considered `PHOTOPRISM_DISABLE_CHOWN="true"`, but this would cause all other paths to be unaffected by the chown.

**Comment by lastzero** [comment]
Does adding `PHOTOPRISM_DISABLE_CHOWN: "false"` to your `docker-compose.yml` work for you? As an advanced user, running chown/chmod automatically isn't really needed.

We expected that some users would have problems, hence the notes in the logs. However, others do not know how to execute these commands themselves, since they have no experience with terminals. Of course, the originals MUST be readable by PhotoPrism, so we cannot remove (only) this path. You could use a custom init script if you need similar functionality, but limited to specific paths.

**Comment by BonzTM** [comment]
`PHOTOPRISM_DISABLE_CHOWN="true"` is supposed to disable permission updates.  `false` would be considered default setting in that case.  Photoprism is not supposed to ever modify the originals folder, yet it's taking control and changing the owner of the shared directory.  

Strangely enough, setting `PHOTOPRISM_DISABLE_CHOWN="true"` or `false` continues to modify the ownership of my pathing regardless of setting.  I am running `preview` build in OpenShift with `originals` mapped into the pod via CephFS.

I could customize my init script, but I think being explicit on every path we agree on touching is the best course for everybody, or else having a path outside of `/photoprism` for `originals`

```sh
home directory: /photoprism
assets path...: /opt/photoprism/assets
storage path..: /photoprism/storage
config path...: default
cache path....: default
backup path...: /photoprism/storage/backups
import path...: /photoprism/import
originals path: /photoprism/originals   <--- this probably should either be out of scope of chown, or out of path
```

**Comment by lastzero** [comment]
Sorry, of course I meant true. It's not PhotoPrism, it's the Docker image and it's because it reduces the number of unpaid support requests which is a good enough reason to update permissions, not file contents. A version for professional users would not include this. 

Did you properly restart the container so config changes were applied? Not much experience with your tech stack. If there's a bug with the init script so the variable is ignored, a PR with a fix would be much appreciated 👍

**Comment by BonzTM** [comment]
> Sorry, of course I meant true. It's not PhotoPrism, it's the Docker image and it's because it reduces the number of unpaid support requests which is a good enough reason to update permissions, not file contents. A version for professional users would not include this.
> 
> Did you properly restart the container so config changes were applied? Not much experience with your tech stack. If there's a bug with the init script so the variable is ignored, a PR with a fix would be much appreciated 👍

I'm sorry, the variable issue was my own fault.  The variables are working correctly

I have submitted a PR with some very light changes.  Feel free to toss, or change as desired.
https://github.com/photoprism/photoprism/pull/2371

**Comment by BonzTM** [comment]
@lastzero implemented skipping CHOWN of original directories with
https://github.com/photoprism/photoprism/commit/f06d768e78298763246ec853c019da4bc2960e50
