### ISSUE TITLE
Go: Sporadic database errors while testing

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#237]
When running Go unit tests, e.g. via `make test-go` in a terminal, we sometimes get database errors because tables don't exist:

![Screenshot 2020-01-30 at 01 52 56](https://user-images.githubusercontent.com/301686/73410790-8c896980-4303-11ea-950f-c201d0603328.png)

Background: In order to have the database in a defined state, we remove all tables and re-create them:

https://github.com/photoprism/photoprism/blob/develop/internal/config/db.go#L153

This might be a timing issue with MariaDB... maybe because db tables are still being created in the background while tests are already running, but that's just an idea. Most of the time it works perfectly, especially on Travis CI there are no issues. So it could be linked to a slow filesystem, maybe only happens in a Mac.

If you have an idea or have the same issue, let us know! Pull requests to fix this are also welcome ;)

**Comment by FrouxBY** [comment]
I have the same issue (Docker in WSL2) and have started to investigate, I do have
`photoprism-db_1  | 2020-02-05 23:58:37 44 [Warning] Aborted connection 44 to db: 'photoprism' user: 'photoprism' host: '172.21.0.3' (Got an error reading communication packets)`
 whenever the test fail with some table that does not exist.

 Issue happens when I run `make go-test`, `go test ./internal/...` but never when running  `go test ./internal/api`. with the 2nd command, the test begins with the api folder, exactly as the third so I am not sure what is happening there.

Have someone try something like https://medium.com/@jarifibrahim/using-gorm-hooks-to-clean-up-test-fixtures-in-golang-99b0fcb04354 to avoid dropping the table?

If not, I will try this week and see if give more consistency in the test

**Comment by FrouxBY** [comment]
After further investigation I have understood the issue,

By default, `go test` will run test in parallel with all the available core (default max is 8).
This means that multiple packages can be test at the same time, and accessing simultaneously to the database, making trouble while setting up the test database.

I gues the CI use only 1 or 2 core, so this does not happened, but on your mac or in my machine (8 core), this may happen often.

The solution can be to run the test using `go test --parallel=1` flag which force go to use only 1 core for the tests, therefore to test one package at a time.

As it can be useful to take advantage of the parallelism on some other query, maybe it can be possible to separate test that requires to be tested on there own and those that can be run in parallel.
another solution is to use separate databases (photoprism-test-api, photoprism-test-query, ...) so that tests does not mess up together

what do you think ?

**Comment by lastzero** [comment]
Or we initialize the tests before running tests, which would also be faster. Thank you! Need to think about it...

**Comment by lastzero** [comment]
Quick fix would be to limit test workers to 1 for now. Should do that ASAP.
