### ISSUE TITLE
Docs: Why is the number of photos you can select limited?

### ISSUE THREAD

**Issue by lettore** [photoprism/photoprism#2393]
Hello,
I'm not sure why but an Album is actually limited to max 999 pictures.
There is a workaround to increase this limit?

**Comment by lettore** [comment]
Well it's not true that an Album can't contain more than 999 but this is the limit when you select items in WebUi.
It will be possible to add pictures to albums by setting a start and end date, if I remember correctly Piwigo had such feature.
Scrolling hundreds of pictures is very slow and when selecting hundreds of pictures the browser freezes.

**Comment by lastzero** [comment]
**I should note that part of the original concept was to help our users reduce the number of photos they actively keep for the rest of their lives, and become more conscious about their quality and relevance. For example, by only adding pictures to albums that are worth keeping, looking at again, or sharing with others.**

Not only is it impossible to select/add more than 999 items at once (an already very high number), but it is also meant to influence ("nudge") decision making. So I'm glad you asked. You can learn more on these slides:

https://dl.photoprism.app/assets/slides/Personal%20Photo%20Management%20and%20Preservation.pdf

In practice, most users will never be able to enjoy such large albums or full photo collections with, say, more than 100,000 images (to be very optimistic), hence the archive feature and limitations.

Of course, we understand that some people just like to have a huge collection and very large albums, as this is standard almost everywhere else, or use albums only as a workaround to tag photos until real taxonomies are implemented. We also understand that professional use cases can be very different.

That said, it seems more useful to discuss this in [*GitHub Discussions*](https://github.com/photoprism/photoprism/discussions) rather than in *Issues*?

**Comment by lastzero** [comment]
Besides, I should add, this also simplifies UI design and limits the number of crazy edge cases we have to test before each release.

**Comment by lettore** [comment]
I'm sure you will not happy if your Windows/Linux system will say "you can't select more than 999 files because I want you to delete what for you is not important".
Besides jokes, I saw that the UI hangs selecting so many items, so it's quite obvious that it's a coding problem to handle such situations. I understand you're not into resolving that because you think one should keep albums/selection small.
As I said before, scrolling the UI down looking for the picture I need is really slow and tedious.
Now the Calendar page is divided into months, it's possible to add also days so the page will be loaded with fewer pictures?
This can be really useful because I can select directly the days I want and add them to the album without selecting the single photos.
I think it will be easy to implement and it doesn't go in contrast with your opinion about selecting many items.

**Comment by lastzero** [comment]
This is being worked on, see GitHub Issues and existing pull requests. Based on your reactions to my detailed response, which by the way took some time to write, it may be best to use other software while you wait for a release that meets your needs. Feel free to continue the discussion on [GitHub Discussions](https://github.com/photoprism/photoprism/discussions) if you have further questions and comments.

Since sustained funding is key to quickly releasing new features, we also encourage you to support our mission by [signing up as a sponsor](https://photoprism.app/membership). Ultimately, it's what's best for the product and the community. Thank you!
