### ISSUE TITLE
Assign or create album at the time of upload

### ISSUE THREAD

**Issue by tmb80c** [photoprism/photoprism#246]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/photoprism/photoprism/issues/246)

Users who organized their photos already in albums on the filesystem might want to upload the pictures directly into a photoprism Album. Would it be possible to add an Album selector to the upload window? A not that bad work around at the moment is to upload pictures from an album and go to recently imported, select all and move them into a new photoprism album. This works when the last photo in a series is known.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- $50.00 have been anonymously funded.
### Submitted pull Requests
- [#345 Feature/246](https://issuehunt.io/r/photoprism/photoprism/pull/345)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/photoprism/photoprism/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by lastzero** [comment]
The directory name is indexed, not sure if you can actively search it already, but would just be a very small change.

Of course we can also create albums for uploads. The questions is when we do our first release and what must be in there. I'm sure the ideas never stop :)

**Comment by lastzero** [comment]
See also: **Add file browser to Web UI #201**

This would enable the user the create albums from existing folders (just like you can now create albums from labels via action menu)

**Comment by jimmcslim** [comment]
I'm just trying this out now... I have organised photos in the following directory hierarchies;

For general, non-event or trip specific photos:
/yyyy/yyyy.mm.MMMM - e.g. /2020/2020.02.February

For event- or trip-specific photos
/yyyy/yyyy.MM.EventName - e.g. /2020/2020.02.Holiday in Paris

It would be great if Photoprism could automatically create albums 2020.02.February and 2020.02.Holiday in Paris, reflecting the content of those directories.

**Comment by lastzero** [comment]
> I should add that these photos are effectively in the /photoprism/originals folder by way of a Docker volume mount, so the indexing process would be what picks this up? It would also be good if these automatically created 'albums from a folder' should be rendered maybe in a different colour, or different icon, etc - and that it should not be possible to delete them from the albums view?

Seems like you'd be mostly happy with a filebrowser, see #201?

We probably won't create albums while indexing, but do this later when everything is indexed so that we can recognize useful clusters / groups of photos that the user would expect as an album. For example, it doesn't make sense to create albums with just one photo when everything is stored in separate folders, or albums that contain all photos because the user didn't use subdirectories.

**Comment by jimmcslim** [comment]
> Seems like you'd be mostly happy with a filebrowser, see #201?

If the filebrowser functionality is going to be an item in the left-hand side navbar, and it would otherwise have the same look and feel as Photos, Labels, Places, etc, then that would be fine.

I can see that it would be nice to have some way of picking a particular photo that acts as the thumbnail for a folder, or even generate a collage/index sheet to use as the thumbnail for a folder (this could be nice for albums as well... but if a user has control over selecting the thumbnail for a folder/album then they can do the work to create a collage themselves, e.g. through a product like Posterino on Mac).

**Comment by spruceb** [comment]
Just want to weigh in that some simple form of this feature is necessary for me to be able to actually start using this software. Without the ability to do some form of organized import, I'll have no starting point/no ability to carry on the sorting I've done in the past, and just be left with a massive blob of (labeled, but still unorganized) images. Currently I see it's not in the MVP milestone, and I'm a little confused as to why. Maybe I handle my photos very differently from others?

**Comment by pKai3** [comment]
Hi! Sorry if I'm missing something but I am wondering why this feature of assigning to an album does not seem to exist when adding photos via the "Import" scheme. I generally use the "upload" scheme when I need direct album assignment at the time of addition to the library, but in this case I have a few hundred gigabytes of photos already on my media server which I need to directly add to an album. 

I need to use the import mode, not index, because the photos have a messy name structure and I am trying to streamline my whole library into your standard format. 

Thanks!

**Comment by pKai3** [comment]
and / or - perhaps even more useful - would be the ability to select batches of images by import/upload session (perhaps a new tab with a list of "albums" containing the images from each import/upload session). This would allow users to more easily correct for errors associated with a given import (e.g. imported incorrect set of photos), and would also allow them to batch add a given import to a given album. A useful associated feature would be a search filter for import date (or added date) which does not seem to be searchable at the moment. Happy to split these into different issues if there is any interest from the devs. Thanks again!

**Comment by graciousgrey** [comment]
Thank you for your feedback! There is no option to do this yet. 
However, you can go to the search and sort by "recently added" to see all photos in the order they were added to the library.

Another option would be to add the files in folders to the import folder. You can then search for this path. For example, if you add photos in a folder called "my-album" to the import folder and import them, you can find all these files by searching for `original: "my-album*"`.
