### ISSUE TITLE
UX: Optimization of the image size displayed in the Photo Viewer

### ISSUE THREAD

**Issue by lakimens** [photoprism/photoprism#2484]
Currently, the size of images displayed on my screen (1920x1080) is either fit_720 or fit_1280. However, comparing the quality difference with fit_2560 or fit_4096, the difference is night and day.

I think it would be nice if we can force the image size being returned. It's a dirty (easy) solution to getting quality of image previews equal to that of Google Photos.

**Comment by lastzero** [comment]
Equal to Google Photos? That's an insult 😹

I recommend trying fullscreen mode, as then the viewport will exactly match the thumbnail. The ideal size is calculated based on the viewport size and pixel density:

https://github.com/photoprism/photoprism/blob/06fe7b7e0ef8f01e7953dfa65486740f9a6c3b15/frontend/src/common/viewer.js#L176

If you find a glitch and know how to fix it, feel free to send a pull request. Shrinking large images (like 4096px down to 1920px what you suggest) is generally not a good idea.... Not only does it waste bandwidth, but the result is also of poor quality. More information of this can be found in our FAQ and in the Advanced Settings docs:

- https://docs.photoprism.app/user-guide/settings/advanced/#images

**Comment by lastzero** [comment]
Does it get better when the browser window uses the full width of 1920 pixels so that the image resolution matches your screen? If not, there may be something wrong with how the browser reports the screen or window size.

In any case, it would be helpful to know what operating system and browser you are using, as indicated in our bug report template: https://photoprism.app/kb/reporting-bugs

I'll move this to discussions for now. If it turns out that we need to improve something, feel free to send a bug report or even better a pull request with a fix! Thank you 🙏
