### ISSUE TITLE
Test PhotoPrismPi on a Raspberry Pi 4

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#249]
See https://github.com/guysoft/PhotoPrismPi

**Comment by dennorske** [comment]
I do have a Pi 4 with 4 GB of ram available and I will test this out by Monday. 
Is there anything in particular you want us to test? Or just to see if we get set up to run?

**Comment by lastzero** [comment]
Just in general: Performance and user experience. You're welcome to report bugs if you find any. Thank you :)

**Comment by dennorske** [comment]
so performance and user experience is undeniably really great out of the box. Everything sat itself up to photoprismpi.local on my network, i logged straight in and it felt really responsive now at a first try.

It says it is possible to index USB media but I tried a few times and it did not work for me. Anything in particular that has to be done, aside from what is said in the readme on that repo?

**Comment by dennorske** [comment]
okay so I rebooted the raspberry and the external drive was detected. If this is expected, let me know

**Comment by dennorske** [comment]
![image](https://user-images.githubusercontent.com/3287543/74589789-b384b280-5008-11ea-9c9b-bea5774d1e9a.png)

Manually uploading does not work it seems. My idea is that the folders are created by docker compose, and the user running inside the container doesn't have access to create the path.

I have tested raspberry quite much now, and it seems to be working pretty well. Only thing is that photoprism spins up too many workers when you import photos, and the load average on the device becomes really high. Browsing photoprism while this happens, is impossible and I managed to crash photoprism once because of this, and had to reboot my Pi to get back.

**Comment by lastzero** [comment]
You can limit the number of workers using the workers config option. Make sure folders belong to user ID 1000 or change permissions. Need to improve this!

**Comment by crypdick** [comment]
@lastzero I'm getting `2020-02-17T00:25:02.747830372Z time="2020-02-17T00:25:02Z" level=error msg="can't create \"/home/photoprism/Pictures/Originals\": please check configuration and permissions"`. I've tried to `chown 1000 Originals` and `chown 777 Originals` without success.

**Comment by guysoft** [comment]
Hey, tested here and seems all is in order, released version 0.1.0 https://github.com/guysoft/PhotoPrismPi/releases/tag/0.1.0 

If there are any changes, it will be version 0.2.0 :)

**Comment by guysoft** [comment]
@dennorske Can you open an issue and explain in detail how you got that upload error?
It might be a simple chmod that fixes it.
