### ISSUE TITLE
Persistent Database with docker-compose.yml

### ISSUE THREAD

**Issue by garrettdowd** [photoprism/photoprism#254]
The current docker-compose.yml uses named volumes for database and cache storage. Is there a way to change this to a bind mount so that the data persists when I remove the container (docker-compose down)

This is mentioned in the [docs](https://docs.photoprism.org/en/latest/getting-started/faq/) for a regular docker invocation (which also doesn't work for me), but it does mention how to alter the docker-compose file. 

When I edit the docker-compose.yml and change the named volume `photoprism-database` to a bind mount, Photoprism does not start.

**Comment by aaronkjones** [comment]
It should work and does work for me using a bind mount.

Something like:

`- ./photoprism-db:/home/photoprism/.local/share/photoprism/resources/database`

**Comment by lastzero** [comment]
See default `docker-compose.yml` file for reference:

https://github.com/photoprism/photoprism/blob/develop/docker/photoprism/docker-compose.yml

```
- "photoprism-database:/photoprism/database" # keep database files
```

You can also use a local directory instead of a docker volume.

Note that the path will change from 

`/home/photoprism/.local/share/photoprism/resources/database` 

to 

`/photoprism/database` 

when we push to `master` next time (this week).
