### ISSUE TITLE
Import: Hard linking instead of move/copy

### ISSUE THREAD

**Issue by brainwad** [photoprism/photoprism#2543]
When importing, there is currently the choice to move files from the import folder to the originals folder, which avoids wasting space but destroys the file structure of the import folder, which might confuse other programs (e.g. file syncing tools). Or you can copy the photos from import to originals, but this doubles the space required to store the photos. Or you can skip importing entirely and just index instead, but then they miss out on the renaming and deduplication that you get when importing.

A third option, on file systems that support it (including common ones like NTFS, Ext4, APFS, but notably excluding FAT), would be to create hard links in the originals folder. This would enable the import directory's file structure to be preserved without taking up extra space. Go natively supports hard links: https://pkg.go.dev/os#Link. For file systems that don't support hard links, the best fallback would probably be copy.

It would probably be best to present this as a new, third option to users: some users might want the file duplication brought by copy (so they can edit the copies without affecting the source files in the import folder).

**Comment by centralhardware** [comment]
by default import folder located inside docker container, and all data will be erased at every container recreate. so photoprism must prevent this case.

**Comment by brainwad** [comment]
Yes, it would require that the import and originals directories were mounted on the same docker volume*, I think, because hard links don't work across different file systems and from the point of view of the docker container each docker volume is a unique file system.

\* Or neither to be on a volume, but then you would lose all your data every time the container restarts.

**Comment by lastzero** [comment]
The main use case for importing is adding files from removable media and web uploads (creating hardlinks would work against that).

Note that the same original file name (in the import folder) may exist multiple times, since cameras usually name images like IMG_1234 and then start again with IMG_0001 and so on. In contrast, the file paths in the original folder must be unique, otherwise the files would be overwritten.

That said, PhotoPrism saves the original file name (from the import folder) in its index, so you can always create hardlinks, softlinks, or zip archives based on that if needed.

A script to do this might fit nicely in the contrib repo if someone contributes it: https://github.com/photoprism/photoprism-contrib

**Comment by m00nwtchr** [comment]
@lastzero 
> The main use case for importing is adding files from removable media and web uploads (creating hardlinks would work against that).

Just give the option to choose between copy, move, and hardlink as 3 options
(You can't make hardlinks between filesystems anyway, so that use case isn't affected at all either way)

**Comment by lastzero** [comment]
We already offer the option to either copy or move... and offering "hardlinks" as an option in the UI seems odd when most users don't even know what that is and not all file systems support it (so it would probably require capability detection involving all source and destination folders, which again can be arbitrarily mounted and nested).
