### ISSUE TITLE
Allow searching by photo parameters with OR conditionals

### ISSUE THREAD

**Issue by FoxxMD** [photoprism/photoprism#266]
It looks like [search functionality](https://github.com/photoprism/photoprism/blob/develop/internal/query/photo.go#L200) for photos uses **and** for every parameter. Which means that if I wanted to search for term X on title, description, and notes and get **any** photos that include that term in those parameters I can't do it in one query.

I know it could potentially complicate searching in general but right now the current search approach really limits what results I can get. I think an easily attainable fix for this would be keeping all terms defaulted to **and** but allow specifying which terms should be **or** conditionals using a querystring key IE
```
?or=title,description,notes
```

**Comment by lastzero** [comment]
You're right. Need to implement this.

**Comment by lastzero** [comment]
This commit is a first step for improving our query parser so that additional search terms are not ignored. When you previously searched for "cat dog", you only found dog pictures. Now, you find cat AND dog pictures (so it's an OR search).

Since there are many other tasks on our todo, I can't continue right here, right now. We'll revisit this later when there is time. It's not overly complicated, but needs to be tested well as it's easy to introduce bugs. Pull requests are also welcome if they are well tested.
