### ISSUE TITLE
Docs: Step by step setup instructions for Synology (using mariadb)

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#2668]
Acceptance Criteria:

- https://github.com/photoprism/photoprism-docs/issues/124

**Comment by Tirallala** [comment]
Hi, I've never done it before, but I think I can contribute. Which format would be useful (html, doc, pdf)? I could document how I do it which is probably not a best practice. Is there somebody who could do a check on the content of the steps I'm documenting?

**Comment by lastzero** [comment]
Markdown is best, either by simply clicking the edit button in our docs, reading the README.md file in our docs repo, or just sending a text file via email.

**Comment by MontereyRedheaded** [comment]
I literally just took a stab at this in the past two days and will share the details of where I ran into trouble which should help. I don't have the availability to make it pretty right now, but perhaps this can help @Tirallala 

For reference, my Synology DSM version: 7.1.1-42962 Update 2

Foreword:

- A. Pure Docker w/ SQLite - First I tried installing this using the Synology GUI and Pure Docker. The limitations due to SQLite turned out to be unbearable because I could not use the GUI at all during import.
- B. Pure Docker w/ MariaDB - Next to keep things in the Synology GUI I tried to replicate the docker-compose YAML using docker images and the Synology GUI. I got a ways in but ran into issues that caused me to switch over to docker-compose; maybe you'll sort them out. 
- C. Docker Compose - Using the command line, you can use docker-compose to load the photoprism YAML. Ultimately I settled on this because it was the simplest and quickest way to get things going. [This article](https://linuxhint.com/docker-compose-with-synology/) was a great reference for that implementation.

### B. Pure Docker w/ MariaDB
These are the items that don't seem to be supported by the Synology GUI and will have to be manually modified via SSH'ing into the Synology after the fact:

- mariadb container execution command with arguments
- mariadb container security options seccomp:unconfined, apparmor:unconfined [see this](https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239)


1. Log in to DSM > Package Center > search for Docker  > Install
2. Open Docker > Registry > search photoprism > double-click photoprism/photoprism
3. Image (tab on left) > double click photoprism
4. Next > check enable auto-start, click advanced settings, add environmental variable for admin password, set database driver to mysql, fill in database server mariadb:3306, description,  author, database password > Next > Add local port 2342 instead of auto if you want, Next
5. add folders from synology to photoprism > uncheck "run"
6. **MariaDB container**: Docker > registry > search mariadb > double click mariadb > Latest or 10.9, they are the same
7. Image > double click mariadb > Next > check enable auto restart, click advanced settings, add the missing environmental variables from the photoprism [docker-compose YAML](https://dl.photoprism.app/docker/docker-compose.yml) under mariadb (below). 
```      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "insecure"
      MARIADB_ROOT_PASSWORD: "insecure" 
```

8. Under Execution Command: This is where I ran into issues. The docker-compose.yaml wants us to use this cmd for mariadb: `mysqld --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120`  I tried using that, but when you get to the end to save the container, it throws an error: "Unable to perform this operation, possibly because the network connection is unstable or the system is busy. Please try again later." You can make this error go away by simply putting nothing or "mysqld" in the command field on the Execution Command tab. Even a single argument seems to cause the above error. We will need to manually edit the command by SSH'ing into the Synology after the fact. I hit Save on this screen > Next > set local port 3306 to container port 3306 > Next > added folder to link Synology folder to maria db, Next > un-check "Run this container" > Save.

9. Enable SSH on your Synology if it's not on already ([here's an article](https://linuxhint.com/enable-ssh-access-synology-nas/)). 
I did the following research but did not implement the next steps because I chose to use docker-compose instead. 
Before the mariadb container runs we can manually edit the docker config. I don't know where Synology installed docker, but in theory the config files for the containers may be in a location like this:
`docker/containers/<container id>/config.v2.json`

Once the config files are found, we can edit the mariadb container to add the values we need. I can show you what these values look like in the config because I ran docker-compose and inspected the docker config there of a running, working mariadb instance (paired with photoprism):

![mariadb_cmd](https://user-images.githubusercontent.com/94807434/200193435-e9132f44-377f-4d32-9ab6-ff54b3413c3e.png)
![mariadb_sec](https://user-images.githubusercontent.com/94807434/200193437-311d04e7-e8b6-42c8-86dc-d82973e0de41.png)

Theoretically after you SSH into your Synology and modify those docker configs to have the correct cmd and security options, my hope was that we could startup the mariadb container, let it do its thing, confirm all is good, and boot the photoprism container up. If you run into issues double check network connectivity between the two containers. 

10. I also had to allow the port for photoprism through my firewall. Not everyone has it enabled. Control Panel > Security > Firewall (tab) > Edit Rules (button) > Create > Select from a list of built-in applications, Select > select the one with port 2342 (or which port you chose), named "Docker <name of your container with photoprism>", OK > Set Source IP to Specific IP (your computer IP or local LAN subnet) for safety > OK > OK 

11. Don't forget to disable SSH unless you're going to be actively using it. 

### C. Docker Compose
If you go this route, you can follow [this article](https://linuxhint.com/docker-compose-with-synology/), but it doesn't provide guidance for making sure docker-compose shuts down or starts up with your Synology. Also, when adding exceptions to the Firewall, you must use "Custom" ports and NOT "Select from a list of built-in applications" because the latter rules will disappear when docker-compose restarts. 

There are many solutions to getting docker-compose to start/stop w/ the DSM, including:

- turn docker-compose into a service (best)
- use rc.local (OK, but Synology's security system will label it as a threat/security problem)
- use the Synology GUI and run tasks as root. Really not ideal to run as root, but I haven't found a way around it yet, not a whole lot of time invested. 

The 3rd method: 
1. Synology GUI > Control Panel > Task Scheduler.
2. Create two new Triggered tasks, run as root, one on boot up and another on shutdown, and use the following scripts:
(I created a folder docker-compose under docker, which is optional. Mine is /volume1/docker/docker-compose, but check where your data is stored.)
Boot up: 
```
DIR='/<your>/<path>/docker-compose'
# wait until DIR, which must contain docker-compose.yml, is mounted to proceed
while [ ! -d "$DIR" ]; do
    sleep 10
done

sudo docker-compose up -d
```
Shut down: 
`sudo docker-compose down`

**Comment by Tirallala** [comment]
Thank you very much @MontereyRedheaded 
I'm using PhotoPrism without MariaDB at the moment, and after reading your post I'm a bit scared of trying to set it up tbh. What I have for the documentation is the steps + screenshots (english) of setting it up without MariaDB. Does that help?

**Comment by graciousgrey** [comment]
We've added the step by step instructions for sqlite to our docs https://docs.photoprism.app/getting-started/nas/synology/#setup-using-docker-sqlite.

Thank you very much @Tirallala 

I will move this issue back to TODO so that someone else can add instructions for mariadb :)

**Comment by graciousgrey** [comment]
Instructions for PhotoPrism with mariadb are available now: https://docs.photoprism.app/getting-started/portainer/
