### ISSUE TITLE
Edited metadata is not included in downloaded files (when the file was uploded over webdav)

### ISSUE THREAD

**Issue by danielr1996** [photoprism/photoprism#2678]
#### 1. What is not working as documented?
When editing metadata and then downloading that picture, the metadata is still like the original in the downloaded metadata

#### 2. How can we reproduce it?
1. Upload any picture through webdav (i used photosync, as recommended)
2. Change the metadata, e.g. date to something different from the original
3. Download the picture
4. In Windows, right click and click Properties
5. Select the Details tab
6. The metadata is different from the one that was edited in photoprism

This happens no matter if upload to import or originals, however when uploading through the webui it works.

#### 3. What behavior do you expect?
I'd expect that when I edit metadata in photoprism that this edited metdata is also included in the downloaded file, no matter how that picture was uploaded.

#### 4. What could be the cause of your problem?
The checklists at <https://docs.photoprism.app/getting-started/troubleshooting/> provided no information regarding my problem. 
As a wild guess I would say that imported files from webdav are copied to a different location and the originals are downloaded but other files are edited

#### 5. Can you provide us with example files for testing, error logs, or screenshots?
Any picture should work (i uploaded jpegs)

#### 6. Which software versions do you use?

(a) latest docker amd64 (2bd1b301e70373df0c7a53f0db5c29043c08cda1135bdd8a5d11a1b8c13cdbca), Build [220901-f493607b0](https://docs.photoprism.app/release-notes/)

(b) Database Type & Version: mariadb:10.8

(c) Operating System Types & Versions: Windows 10 to download, Android to upload via Photosync

(d) Browser Types & Versions: Firefox 104.0.1 (64 Bit)

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?
Traefik 2.7

**Comment by graciousgrey** [comment]
That's a feature request not a bug and we already have an open issue for it :)

https://docs.photoprism.app/user-guide/library/metadata/
https://github.com/photoprism/photoprism/issues/402
https://github.com/photoprism/photoprism/discussions/1092

**Comment by danielr1996** [comment]
Ok I understand, I was looking in the editing section of the documentation and couln't find anything, the one you linked does indeed say that photoprism doesn't modify original files.

However what still isn't clear to me is: Why does it work when I upload a picture through the web ui, but not when I upload it through webdav. 

To clarify: I don't expect the original files to be modified, but I do expect that a file downloaded through the integrated download functionality includes the modifed metadata. And at least I would expect the behaviour to be constent, wether I upload via ui or webdav. 

So in my opinion this is still a bug which should be fixed

**Comment by graciousgrey** [comment]
> And at least I would expect the behaviour to be constent, wether I upload via ui or webdav.

When editing something on the photos edit dialog all files should be treated the same way, independent from the ingestion method.

When using the Web Upload the import method is used which moves or copies the original file from the import folder  to the originals folder and gives it a unique name (https://docs.photoprism.app/user-guide/library/#importing-files). This might change metadata such as the file's modify date. 

Also when downloading a file the only metadata that differs between the downloaded file and the original file should be the FileModifyDate and FileAccessDate.

But this is not caused by edits done using the PhotoPrism Web UI. 

You can verify this by running `exiftool -j filename.jpg` on

## When using the web upload
1. The image before you upload it
2. The image (it will have a new name now) that has been copied or moved to the originals folder
3. The same image in the originals folder after you made changes on the photo edit dialog
4. The image you downloaded using the download functionality 

## When adding the file to the originals folder using webDAV
1. The image before you transfer it using webDAV
2. The image directly after it has been transferred to the originals folder
3. The same image in the originals folder after you made changes on the photo edit dialog
4. The image you downloaded using the download functionality

**Comment by danielr1996** [comment]
Thanks, that clarifies the differences
