### ISSUE TITLE
Add slideshow button to photo viewer

### ISSUE THREAD

**Issue by thundergreen** [photoprism/photoprism#269]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/photoprism/photoprism/issues/269)

Dear all,

first of all thanks you very much for this awesome iece of software.. I am plannning to use this as a kind of screensaver for my home autmation dashboard. Is there any chance to get a slideshow.. Diashow for it?

Thanks in advance.

Thorsten

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- $5.00 have been anonymously funded.
### Submitted pull Requests
- [#318 Frontend: Add slideshow button to photo viewer #269](https://issuehunt.io/r/photoprism/photoprism/pull/318)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/photoprism/photoprism/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by lastzero** [comment]
Thank you very much! We're currently working on sharing, so it will take a while. Requests backed by sponsors will have a higher priority though.

**Comment by thundergreen** [comment]
I understand. And your application is really neat and clean . That's why I chose it but to be honest I was wondering not having found any issue about this here . Then I'll of course wait ..keep on this awesome project

**Comment by TheDarkTrumpet** [comment]
I'd like to throw my thoughts behind making a slideshow option a possibility.  I'll "watch" this task, after my current side projects are done, I may look at this as well.  It would be really nice to have.

**Comment by lastzero** [comment]
There are other photo viewers that support slideshows. However those would need to be customized like our current photo viewer while everyone is desperately waiting for a stable release. I guess it's best to deliver what we have now and improve later.

**Comment by lastzero** [comment]
We currently use https://photoswipe.com/

How do you like https://galleriajs.github.io/?

**Comment by lastzero** [comment]
Started a poll, see https://twitter.com/browseyourlife/status/1259569242724282370

**Comment by TheDarkTrumpet** [comment]
Galleriajs seems to be just fine.  The functionality for the slideshow, quite honestly, doesn't need to be super big on my end.  photos.app supports quite a bit, and would be way overkill.  Galleriajs seems to be fairly simple, and would just work.  Could always be expanded upon later, if time allows.

If people are waiting for a stable release, wrapping that up should take priority over this kinda feature.  It's going to be a few weeks before I personally can look into this in more detail due to an outstanding project.

In terms of the poll. If you would, please add (mentally) a vote for galleriajs or 'both' (although if galleriajs supports all the same features you have already, then using that makes the most sense.  Unfortunately I don't use twitter, or much in terms of social media, for a few reasons :)

**Comment by lastzero** [comment]
Found a way to make it possible without breaking changes :) Hope you like it!

**Comment by thundergreen** [comment]
@lastzero Sounds great! If it would be merged .. perfect! :) Waiting your feedback guys! Gat work!

**Comment by lastzero** [comment]
It's already merged, see [demo.photoprism.org](https://demo.photoprism.org/)

Going to add video playback to the photo viewer today as well.

**Comment by thundergreen** [comment]
@lastzero Looks good. Any chance to have  a setting option for the time between two pics in the slideshow? Seems a bit too fast for me :P 

And last question. Possible to add this slideshow in api? Let's say to start a slideshow remotely.

**Comment by lastzero** [comment]
@thundergreen Both is possible. Adding a configuration option in Settings is easy. A remote API a bit more complicated, don't think we can do this for our first release.
