### ISSUE TITLE
Combine storage and originals

### ISSUE THREAD

**Issue by al13nus** [photoprism/photoprism#2708]
Hey together,

I was wondering why the originals folder and storage folder is not combined? I started creating transcoding files of my videos and they land all on storage which is getting bigger. At the end its like having two originals, because for every real original there is another file but in another location. Does it make sense? And I'm talking not about the cache but the storage/sidecar.

Maybe an option to put the sidecar along with originals and change the indixing to not delete the duplicates would be an improvment? Thankful for your thoughs. 

My folder structure looks like this:

/mnt/local/Cloud -> originals
/opt/photoprism/storage -> storage

Getting the Cloud bigger is fine, getting opt bigger not so fine

**Comment by heikomat** [comment]
Having sidecar and cache files NOT be in the `/originals` folder is a good thing. This way my originals folder doesn't get polluted. And maybe i only have read-rights on the originals folder, then my storage folder HAS to be somehwere else.

I think the way easier solution for you is to just not put the `storage` folder in `/opt`?
Afaik you can configure it to be anywhere you want. (i'm not 100% sure on that, but because most people use docker, they can mount the storage-volume wherever)

**Comment by heikomat** [comment]
Found it. The config is `PHOTOPRISM_STORAGE_PATH` (see [here](https://docs.photoprism.app/getting-started/config-options/#storage)). You can set your storage folder to wherever you want it to be

**Comment by lastzero** [comment]
Put a dot in front of the folder name if you want it to be inside the originals folder for some reason, e.g. `.storage` or `.photoprism`. That makes it hidden so files inside don't get indexed. 

Using a single folder can be useful. For example, if you are using an external device, so that you can easily mount your library on different computers.

On the other hand, external drives can be slow, and advanced users may want to optimize storage costs and performance by putting the folders on different devices, e.g. a traditional RAID for the originals and an SSD for the database and cache.

That said, please don't use GitHub Issues for questions and technical support. Thank you! ❤️
