### ISSUE TITLE
How does one recover all their original data?

### ISSUE THREAD

**Issue by p-baum** [photoprism/photoprism#277]
How does one extract all their master import files considering the fact they may have been moved/deleted during import.

Vendor-lock-in is probably one of the major motivations for installing this software in the first place.

**Comment by lastzero** [comment]
Files will never get deleted. What can be imported will be renamed, so that names are unique and sorted by date. You don't have to use import, you can copy your files to originals and manage the structure yourself if you have the time or use other tools for this.

**Comment by p-baum** [comment]
ok. so i have to backup before i add my stuff to photoprism. Correct?

**Comment by lastzero** [comment]
You can index files in originals without creating a copy first. You can also set it to read only, but then you won't be able to upload or create JPEGs from any RAW images.

**Comment by p-baum** [comment]
This conversation is unnecessarily complicated - a typical warning sign of vendor-lock-in.  I have hope. Lets break this down.

> Files will never get deleted

DISPUTED: From my (and likely every new users) perspective, the import masters are in fact deleted from the "Import" directory upon import.  (An option exists to keep these "REAL originals" but it is actively discouraged)

> What can be imported will be renamed

Well that's quite inconvenient but thankfully conveniences are easily programmatically overcome. Please provide the permanent renaming and relocation scheme.

> you can copy your files to originals

I tried this and just got a page of grey boxes with spinner gifs.  Did i do something wrong? 

> and manage the structure yourself

How can i manage the structure when my "import originals" have been consumed relocated and renamed using  an unknown method?

**Comment by lastzero** [comment]
There is no lock-in and importing / renaming is an OPTIONAL feature you don't have to use. We are working on our docs to explain this better and in detail. You're welcome to donate or contribute to help with this.

**Comment by p-baum** [comment]
>There is no lock-in and importing / renaming is an OPTIONAL feature

Compare and contrast to the user interface option of  "Move files to save space and improve performance"

------------------------
I cannot help you with your docs until I understand your software. To this end please provide me with the PERMANENT renaming and relocation scheme for files removed from "Imports" upon import.

**Comment by lastzero** [comment]
This is open source, you can find the answer to the naming scheme here: https://github.com/photoprism/photoprism/blob/develop/internal/photoprism/canonical.go

Basically, we're trying to make the names unique so that there are no duplicates.

Import is an optional feature, you can also just index. Two separate commands. When you import, imported files in the originals directory will have canonical names, independent of the copy / move checkbox.

**Comment by p-baum** [comment]
Thanks for the detail. Sadly I dont speak that language. What is it? go? Im too old for that shit.

Dont get me wrong. Great product here. I like it and the promises it makes. But I love my photos more. You understand.

I'll focus on protecting/backing-up my photos before they are consumed by this wonderful and confusing black box.

Above all - Thankyou. Its the best solution I found so far for my photo problems

**Comment by lastzero** [comment]
You are right, be careful with your originals! We absolutely avoid modifying original images, even though some users want us to modify embedded Exif metadata.

When sharing is done, we'll improve our UI and documentation to better explain how importing works and also make sure everyone understands this is strictly optional. I need it for my photos because I have to merge directories with lots of duplicates from different sources.

**Comment by lastzero** [comment]
@p-baum Improved wording on import page to better explain what it does - hope this helps!

![Screenshot 2020-04-07 at 14 13 31](https://user-images.githubusercontent.com/301686/78667881-0462aa00-78da-11ea-836c-ee82cb3f4960.png)
