### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by pittbull** [photoprism/photoprism#2801]
#### 1. What is not working as documented?

After applying the latest update I am unable to login to Photoprism. It fails with: Invalid credentials.

Current version: 221025-3b9890e34-Linux-AMD64

#### 2. How can we reproduce it?

Not sure, but when trying to reset the password using: docker exec -ti PhotoPrism photoprism passwd the following error is given:

INFO[2022-10-25T21:52:50+02:00] migrate: executing pre migrations
INFO[2022-10-25T21:52:50+02:00] migrate: executing main migrations
WARN[2022-10-25T21:52:50+02:00] users: Admin account is not allowed to log in
INFO[2022-10-25T21:52:50+02:00] please enter a new password for '' (mininum 8 characters)
New Password:
Retype Password:
INFO[2022-10-25T21:52:55+02:00] closed database connection
ERRO[2022-10-25T21:52:55+02:00] only registered users can change their password

#### 3. What behavior do you expect?

To log in.

#### 4. What could be the cause of your problem?

I do not know.

#### 6. Which software versions do you use?

(a) Current version: 221025-3b9890e34-Linux-AMD64

(b) MariaDB

(c) Unraid 6.11.1

(d) Firefox

(e) N/A

**Comment by pittbull** [comment]
I have special characters in my password - could that potentially be the problem?

**Comment by krlls** [comment]
I have the same problem after update 😢

> I have special characters in my password - could that potentially be the problem?

There are no special characters in my password. I don't think that's the problem

**Comment by streiman** [comment]
Are you on the preview version? Then it might be this:

"Session and user management have been re-implemented. If you are upgrading from the last preview, you may need to run the "photoprism users reset" command in a terminal after the upgrade to recreate the new database tables. They are not compatible with the last preview, which is why we have stopped releasing preview builds until they are stable enough."

https://docs.photoprism.app/release-notes/#development-preview

**Comment by pittbull** [comment]
Embarrasing on my part. I read the wrong release notes 🫣
