### ISSUE TITLE
Feature request: Support JPEG XL as image format

### ISSUE THREAD

**Issue by Tokariew** [photoprism/photoprism#2808]
JPEG XL allow to losslesly transcode existing photos in traditional jpeg format to achieve smaller sizes. Lastly i transcoded some of my images to this format and was little suprised that photoprism don't support them. Can support for this format be added, so we can import jxl images to photoprism?

**Comment by lastzero** [comment]
Support is planned from our side, but we need support in Go and common Web browsers. You might find an existing issue for this.

**Comment by lastzero** [comment]
Here it is:
- #668

Should we keep both feature requests open so we can remember twice as good, or would it be okay to keep just one request open?

**Comment by lastzero** [comment]
According to the Google Chrome team:
- There is not enough interest from the entire ecosystem to continue experimenting with JPEG XL
- The new image format does not bring sufficient incremental benefits over existing formats to warrant enabling it by default 

Sources:
- https://www.phoronix.com/news/Chrome-Deprecating-JPEG-XL
- https://bugs.chromium.org/p/chromium/issues/detail?id=1178058#c81

**Comment by lastzero** [comment]
Although we would like to support JPEG XL, it seems best to wait based on the information above. Does everyone agree?

**Comment by lastzero** [comment]
One option would be to add read support but continue to use regular JPEG thumbnails. However, I'm not sure how useful this is, since few users will have JPEG XL files.

**Comment by G2G2G2G** [comment]
>Although we would like to support JPEG XL, it seems best to wait based on the information above. Does everyone agree?

Only option now for in browser is some javascript to translate it into some other image format. imo not that great so yea have to wait...
I'd support avif if people want it though, I know I do. Especially to replace gifs

**Comment by lastzero** [comment]
We already transcode animated GIF to AVC. Two different target formats that basically do the same seem a bit over the top, also in terms of ongoing maintenance & test efforts?

**Comment by G2G2G2G** [comment]
You sound like google in their reasoning for dropping jxl

**Comment by lastzero** [comment]
Bad take! They have thousands of developers and billions on their bank account, while we are drowning in work and can't go on vacation because of this.

**Comment by lastzero** [comment]
@G2G2G2G In case you have not noticed, Google is trying to push their own formats which compete with JPEG XL. The reason they give is total nonsense, while we're just honest and transparent here.

**Comment by G2G2G2G** [comment]
They're depreciating webp2 as well, and jpeg xl is worked on as much by them as webp / avif was...
and you take more vacation per year than everyone I know combined has in the past 10. I think you'll manage

**Comment by lastzero** [comment]
Are you OK?

**Comment by lastzero** [comment]
👉 @G2G2G2G https://photoprism.app/code-of-conduct

**Comment by G2G2G2G** [comment]
not relevant to this thread, nor did anything go against it. Stay on topic

**Comment by lastzero** [comment]
@G2G2G2G How is that respectful and not ignorant, given the obvious amount of mostly unpaid work we put into this? Don't feel entitled to us doing this work and never claim that we have so much free time when in reality we work seven days a week, 16 hours most of the time. Even when we take a few days "off," we work many hours a day.

You're blocked because your communication is just too much for us right now. Let us know when you've had time to think about it.

**Comment by xplosionmind** [comment]
Hi! I cannot overlook the disrespect polluting this thread, therefore: much support to you, @lastzero ❤️

Nevertheless, I would like to ask if this issue could be reopened, if it makes sense.

I do not really care if thumbnails are in a poorer image format… I would just love to upload/import in PhotoPrism JXL images, primarily for the sake of storage economy, but of course also for the many other advantages of this format.

At this point my question is: since #668, if I am not wrong, is focused on front-end performance, and this issue instead is concerned with overall support (hence handling JXL files in the backend), shouldn’t both issues stay open since they concern two different features?

**Comment by lastzero** [comment]
@xplosionmind Thank you for your kind words! If disrespect and trolling could stop us, it would have happened long ago. From what I can tell, we are still doing relatively well compared to other projects.

That said, we've been quietly continuing to work on it, so the issue isn't really closed. With our latest release you should be able to index JPEG XL images, see the feature overview on our website:

https://www.photoprism.app/editions#compare

For this, we use the command line tools provided by the reference implementation. This approach is not well suited for creating thumbnails, though that's not a pressing issue as long as we wait for browser support.

Since Google is unlikely to provide native JPEG XL support in Go (considering how they've been actively working against it lately), one option might be to use libvips for thumbnail creation. It looks like it might have JPEG XL support already, but I haven't had time to check if it's mature enough (**we'd appreciate help evaluating it**):

- https://github.com/libvips/libvips/discussions/2055
- https://github.com/libvips/libvips/issues/3132

**Comment by derneuere** [comment]
@lastzero I can recommend libvips regardless of the JPEG XL support. It's very fast and resource friendly, which is why it's our main thumbnail engine in LibrePhotos.
