### ISSUE TITLE
Folders load slow

### ISSUE THREAD

**Issue by jerome-cui** [photoprism/photoprism#2842]
I have more than one thousand of folders and after I imported into Photoprism I found the "Folders" page loads too slow.
Reproduce:
1. add more than one thousand folders of images 
2. index all of them
3. after finished, visit Photoprism and click the "Folders". It will take seconds to load.

Suggestion:
1. Maybe we have no need to display all folders at loading, but load a batch of fixed size one time and load more if we scrolled to the bottom.
2. Another method is load folders in pages and show page numbers at the bottom
3. The last method is we maybe not flat show all last level folders directly, but keep the original folder structure and let user navigate from the top folder to last level of folder.

**Comment by lastzero** [comment]
The file browser or the actual folders page? Did you test on our preview yet? What about you use subfolders instead of putting all the folders in the originals root?

Edit: I've labeled this as a feature request for now as it's a known limitation of the file browser. The folders page could require virtualization, but it's some work and not a bug that we don't have this yet.

**Comment by jerome-cui** [comment]
I mean the "Folders" page. In fact all my image folders are under different subfolders, but in folders page it neither show root folder nor subfolder.

**Comment by lastzero** [comment]
So you're asking for a virtual view comparable to the regular search (cc: @heikomat).

Kindly note:
- the page may take longer to load the first time, because the thumbnails are cached the second time
- the upcoming release will not load all the results if you were on the folder page before, unless you used the back button
- a feature request for a nested albums / folders view already exists, see #401

**Comment by jerome-cui** [comment]
> 

That's great. I tried the preview version just now and seems the "Folders" page load very fast now. 
Thanks for your great work!
