### ISSUE TITLE
Config: Add option to stream videos over the specified CDN

### ISSUE THREAD

**Issue by shivanshs9** [photoprism/photoprism#2875]
**Describe what problem this solves and why this would be valuable to many users**

Right now, the `PHOTOPRISM_CDN_URL` envvar only enables static assets, thumbnails and compressed library images to be delivered via CDN. Not for video files.

**Describe the solution you'd like**

CDN could be enabled for videos too.

**Comment by lastzero** [comment]
Videos are complicated in that these are streamed, the supported formats must be detected and the video must be transcoded on demand if the format is not supported or the bitrate is too high. We found this not to work well with (at least) our provider and that's why it's not supported. If you have a lot of practical experience and know how to build it so that it always works and is compatible with any CDN provider, please let us know! 👍

**Comment by lastzero** [comment]
@shivanshs9 This issue is related to what I've been working on this week:

- #3297

If I remember correctly, KeyCDN had problems with video streaming. I can't remember any details though. It will definitely cause a lot of extra traffic that you have to pay for. Not all users might want to do that!?

Cloudflare doesn't support video by default either, only for an additional fee (because of the traffic it causes).

Note that we had to switch our website and [demo.photoprism.app](https://demo.photoprism.app) from KeyCDN to Bunny CDN last weekend, which might work better for videos based on the settings I've seen in their admin UI.

I've also started working on a CDN setup guide (contributions and feedback welcome):

- https://docs.photoprism.app/getting-started/using-a-cdn/

**Comment by lastzero** [comment]
An updated preview build will be available for testing soon. As always, help with testing is much appreciated! Thank you ❤️

**Comment by lastzero** [comment]
Had to add more cache headers for this to work. CDN caching can then be enabled by adding the following variable to your docker-compose.yml file:

```yaml
PHOTOPRISM_CDN_VIDEO: "true"
```

**Comment by lastzero** [comment]
The last change prevents token headers from being sent in public mode (like on our demo), so that the default tokens are used for viewing and downloading. Changing tokens each time the instance is restarted would otherwise prevent caching because these are part of the URL.

**Comment by lastzero** [comment]
A new development preview will be available for testing soon!

**Comment by lastzero** [comment]
Our demo works great with this. Let us know if you require any further changes. We'll otherwise release it like it is and close this issue.
