### ISSUE TITLE
Smart albums

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#29]
Some users might want the software to automatically create albums e.g. like the iPhone does. Not sure if this is what we want. I would like to have more control over what the software does.

**Comment by lastzero** [comment]
Good idea!

**Comment by devzsolt** [comment]
Not sure about it because I just saw the Google Photos implementation which is kind of lame, it usually groups a bunch of unrelated photos when I'm taking more photos on a day than usually and names it like Saturday in [some meaningless reverse geocoded location]. Is the iPhone implementation any better? 
Anyway I think this should be an opt-in setting/plugin rather than the default.

**Comment by lastzero** [comment]
Done, see Moments and Calendar ⭐️
