### ISSUE TITLE
Broken after upgrade

### ISSUE THREAD

**Issue by casidiablo** [photoprism/photoprism#293]
Not sure if the schema changed. I'm running `200503-0ff34b6-Linux-x86_64` and I ran `photoprism migrate` just in case.

And yet, trying to open the gallery gets me this error in the browser:

```
Error 1054: Unknown column 'photos_labels.uncertainty' in 'on clause'
```

**Comment by lastzero** [comment]
Yes, the schema is changing continuously every time we add or improve features so that we don't need to change it later, when users expect it to be stable.

The easiest strategy is to delete the database and re-index. Alternatively you can remove the tables that cause the issue using the mysql command line tool or any MySQL-compatible database UI. Tables will automatically be re-created when you start the server. Or you can try to fix specific table columns manually, if you know what's wrong, but that's not recommended.

**Comment by casidiablo** [comment]
Cool. Good to know. So... what does the `photoprism migrate` command do?

**Comment by lastzero** [comment]
It migrates the database automatically and doesn't change existing columns to avoid data loss. Hand crafted migrations for every change would be better, but we don't have time for this at the moment. We'll do it for our stable release.

**Comment by savegame** [comment]
@lastzero , i update it just today, remove database and start photoprism, but have error: 
```
FATA[2020-05-09T02:51:09+03:00] dial tcp [::1]:4000: connect: connection refused 
```

**Comment by lastzero** [comment]
Default port changed to 2343 as some users had issues with 4000. See example Docker Compose config in our docs.

**Comment by lastzero** [comment]
Re-added port 4000 to exposed in our Dockerfile so that older configurations continue to work:

`EXPOSE 2342 2343 4000`

Docker builds are running, new images available soon. I have other duties today, so if there are sill or other issues, it might need to wait until tomorrow or next week.

**Comment by savegame** [comment]
@lastzero , i don't use docker, just built it in freebsd, where i should look to change port configuration? ( i'll try find it by myself first =) )

**Comment by lastzero** [comment]
Run "photoprism help" and "photoprism config"

Did you compile TensorFlow on FreeBSD?

**Comment by savegame** [comment]
@lastzero, yes, but version 1.14 from official FreeBSD ports. It should work by installing it with **pkg install** , but need some fixes for symlinks to *libtensorflow.so.1*
