### ISSUE TITLE
Lost thumbnail after reindexed

### ISSUE THREAD

**Issue by ravetam** [photoprism/photoprism#299]
First of all, this is an awesome tool, I have been using it for the past week to organize and geotag all my photos from a recent trip. One issue I encountered twice is that photoprism were not able to reverse lookup certain GPS location which causes the image to be tagged with "Unknown" location. So what i did is slightly modify those images GPS data with exiftool.

Once re-indexed and since the image hash has now changed and thumbnail are named using the image's hash, Photoprism no longer finds the thumbnail.

`ERROR photo: thumbnail not cached`

However, a few smaller thumbnails are generated which i assumed are being used for labeling.

> ├── 69f05da9b6a8113125dce0e5ffb9c5f6a5132f47_224x224_center.jpg
> ├── 69f05da9b6a8113125dce0e5ffb9c5f6a5132f47_224x224_left.jpg
> ├── 69f05da9b6a8113125dce0e5ffb9c5f6a5132f47_224x224_right.jpg
> └── 69f05da9b6a8113125dce0e5ffb9c5f6a5132f47_3x3_resize.png

Maybe this can be fixed my renaming and moving the existing thumbnails to its new location. This will reduce a lot of orphaned thumbnails.

**Comment by lastzero** [comment]
Well observed, this is because we disabled on-demand thumbnail rendering as users with no thumbs at all were running out of memory, see #294. 

In your case, on demand rendering probably wouldn't hurt as it's just a couple of photos. Your existing thumbs can not be found as the sha1 hash changed and that's the cache key.

Either set `PHOTOPRISM_THUMB_UNCACHED: "true"` in `docker-compose.yml` or render missing thumbs:

```
docker-compose exec photoprism photoprism thumbs
```

We should automatically re-render those thumbs in the future and maybe delete the old ones to save storage.

**Comment by lastzero** [comment]
My change should automatically trigger resampling when files were updated in the index. It does not clean-up the cache directory to remove old thumbs, that's an optimization we'll take care of later.

**Comment by lastzero** [comment]
New Docker build is available within the next hour. You're welcome to test!

**Comment by ravetam** [comment]
thanks for the quick response! i will test it tonight and post my result

**Comment by ravetam** [comment]
Tested and confirm issue is fixed, new thumbnails are being generated now.

**Comment by lastzero** [comment]
Excellent, thank you! :)
