### ISSUE TITLE
Videos: Some HVC QuickTime files do not play on iOS and Safari without transcoding

### ISSUE THREAD

**Issue by RobinMM** [photoprism/photoprism#3008]
Certain HVC1 live photos can't playback on iOS devices. While exactly the same files work when viewing them in the 'Synology Photos Mobile iOS App'. It works also fine when viewing them on Windows desktop browsers.

Mentioned by @lastzero 
_Same on my iPad, doesn't play although the video contents are streamed. So this likely is a JS problem. Modern Apple devices & browsers support playing HVC natively, so no transcoding is required.
The error I see in the JS console is: "Unhandled Promise Rejection: AbortError: The operation was aborted."
Next step would be to google it as I have no idea what it means. Other videos can be played. So it either is a HVC related Safari problem or the frontend code that handles video formats / streaming must be improved to be fully compatible.
This JS error could also not be related to the video at all as it could have been triggered elsewhere... the JS console shows the video stream red like an error, but the response code is 206, so no error.
Apple has a history of breaking things that worked. Latest Safari even broke Google Maps until they released an update. So not surprised.
My educated guess is that Safari plays HVC but not this particular file (could use 10bit colors instead of 8bit...)._

I have tried different browsers on my iPhone, Edge, Chrome and Firefox, All browsers having same issue. I have provided sample files. Both are HVC1 live photos. But only IMG_4690 works, IMG_4559 not.

![image](https://user-images.githubusercontent.com/1236301/207888553-7efc93a2-aeeb-4514-8164-e437ff1c6184.png)

[sample-files.zip](https://github.com/photoprism/photoprism/files/10237714/sample-files.zip)

**Comment by lastzero** [comment]
After checking the files provided, I am 90% sure that the problem is the QuickTime container.... I'm not sure why Apple's software shouldn't play this container though, since they invented it, but it's possible as standard MPEG-4 should be used on the web. A "workaround" would be to force transcoding for Safari too.

See this [note in our documentation](https://docs.photoprism.app/developer-guide/media/videos/):

> Although the QuickTime `.mov` container format served as the basis for MPEG-4, there are differences and the two are not strictly interchangeable. Nevertheless, they can be played in most browsers and are not automatically transcoded for this reason.

**Comment by lastzero** [comment]
That being said, it is possible that we can get the video files to work by setting other HTTP headers, so that Safari uses the QuickTime parser if it has one.

I would have thought that Apple only maintains a parser/decoder for QuickTime and MPEG4, but that's not necessarily the case. It could also be that for some reason Safari only supports QuickTime with AVC and not HVC - or Apple will add support in a future release of Safari.

**Based on what I wrote above, could you (or someone else who would like to see this fixed) please do some research and suggest one or more solutions that we can try? Thank you!**

**Comment by huahuasousou** [comment]
It's funny, you can see that I've been reporting similar issues for the past half year, and then I spent a week found this bug and writing out all my findings.

But the authors of photoprism thought that I was just a user without any professional skills, and always told me that under their test, all the files I provided were "sucessed play after convert", and told me just need enable the forced transcoding.

Apparently they never actually tested the files I uploaded and actually read the issues I described. Until the second user reported again.

https://github.com/photoprism/photoprism/discussions/2854
https://github.com/photoprism/photoprism/discussions/2852
https://github.com/photoprism/photoprism/discussions/2775

**Comment by lastzero** [comment]
We wish you a Merry Christmas. Sorry if the level of free support is not what you expected.

**Comment by lastzero** [comment]
@huahuasousou Thanks to the additional pressure you put on us, I was able to find the underlying issue:

- the problem was caused by the mime-type detection, which might not work reliably with newer QuickTime files created by Apple devices
- if we assume all files ending with `.mov` are QuickTime videos, playback works as expected
- a new development preview will be available for testing soon
- you need to re-index the affected files for the fix to take effect

**Comment by RobinMM** [comment]
Cool! Will check it out once available :)

**Comment by lastzero** [comment]
The last commit removes the custom read limit of 1024 bytes for mime detection, so that the default of 3072 bytes is used. This might help to avoid incorrect results as previously observed with QuickTime videos
