### ISSUE TITLE
Albums: Change default sort order from "oldest" to "newest"

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#3021]
**This way, users who use albums to organize recently taken pictures (on a trip, for example) don't have to change the sort order in the edit dialog, which may feel more natural and more consistent with how other apps work.**

Feedback welcome!

**Comment by dror3go** [comment]
I personality don't like this change, it doesn't make sense to me.

I look at albums as something that happened and is done, so for that I expect to see it in chronological order every single time I see it or share it with someone. Like reading a book.
As opposed to the main Browse section which is live and breathing, where I expect to see items in reversed chronological order by default. Like reading a blog.
Mind you that organizing recently taken items on a trip is useful only on a very specific time frame.

If there's a need to help users who are managing photos while on a trip - how about separating the user's defined sort order in the Browse section from the sort order of the Unsorted section?

I'm not using any other photos app, but it's my understanding that Google Photos does not sort items in albums in reverse chronological order by default.
Which app does?

As a side note: I'm not a big fan of having lots of configurable variables, but I think that such a change should be implemented, if at all, by a configurable variable.

**Comment by lastzero** [comment]
Thanks for your feedback! That was very helpful. I understand your point, that's why the default was "oldest" until now. The change has been reverted as we will eventually need to implement settings for this. Once we implement tags, those can be sorted by newest.

**Comment by dror3go** [comment]
Thanks for reconsidering @lastzero! 🙂
May I ask what do you plan for tags, and how do they differ from labels?

**Comment by richard-lee-863** [comment]
Was this supposed to be turned into a configurable setting? I currently need all Calendar views to be default sorted "newest" first, so that it matches Google Photos. That way i can quickly eyeball both Photoprism and Google Photos and make sure I haven't missed anything while going through the transfer process. 

There will always be people wanting different defaults for different reasons, so surely a setting in the Library settings would make the most sense? Perhaps different options for the different "Views" (Albums, Calendar, Moments etc...)?

**Comment by graciousgrey** [comment]
@richard-lee-863 we do have a separate issue for this https://github.com/photoprism/photoprism/issues/405 :)
