### ISSUE TITLE
Enable photos that have been automatically 'stacked' to be unstacked

### ISSUE THREAD

**Issue by jimmcslim** [photoprism/photoprism#308]
I'm sure I've seen some documentation somewhere indicating what the time threshold was for photos to be automatically stacked...

Anyway, it would be good if there was a way to unstack a set of photos that have been stacked.

**Comment by lastzero** [comment]
Happens when they were taken in the same second at the same location or when file names almost match, like when they have a sequential postfix like copy 1, copy 2,.... you can turn this off in Settings.

We plan to add a "unstack" button to the files tab in the edit dialog. It's on our todo.

**Comment by jimmcslim** [comment]
It would be good to understand how the matching works, I'll have a look at the code. E.g. I have photos named `2016.01.01-17.39.22.jpg` and `2016.01.01-17.39.42.jpg` and they have been stacked together; so taken within the same minute from a file naming point of view, but have quite different subjects. I could see a benefit in being able to control the way stacking works; by filename the same up to X characters, or including in stack if taken within X seconds of a previous photo, or even some assessment of how similar they are to a previous photo... I accept this is all great functionality to have but adds complexity! Thank you for your work on this project!

**Comment by lastzero** [comment]
@jimmcslim Numbers after the second last dot in a file name would be regarded as sequence, you can turn this off in Settings if you happen to have a lot of files that use dots and numbers in their names. Maybe I change it to at least 5 digits, so that dates are not affected.

**Comment by lastzero** [comment]
I've set the milestone to MVP, but think this might be a follow up ticket for #356 since we won't be able to add additional setting before our release. This can easily be added later.

**Comment by lastzero** [comment]
Added **Ungroup videos from JPEGs that have the same path and name #375** as a follow-up. I'll remove this from the milestone as we won't add more settings are this point.

**Comment by fdw** [comment]
It seems I can only ungroup sidecar JPGs from a stack. Is that me not seeing something, or is it yet not possible to ungroup also the main raw file?

Version is latest docker.

**Comment by lastzero** [comment]
You need at least one JPEG, otherwise the photo can't be displayed and is hidden.

If you happen to have completely unrelated files with exactly the same file name (minus extension), you need to wait. Apple exported some of my videos and JPEGs like that. To ungroup those, we need to create a new JPEG as primary file first. Thus issue was about ungrouping two JPEG files.

**Comment by fdw** [comment]
I have two raw files that, because of errors with the camera's clock, have the same timestamp, but aren't related at all. I can understand why they have been stacked, but I'd like to ungroup them.
Both files have a sidecar jpg each, but if I click "ungroup" on it, only the JPG is removed from the stack; both raw files are still in it.

Should I open a new ticket for this?

**Comment by lastzero** [comment]
Yes please, also add screenshots if you like.
