### ISSUE TITLE
Frontend: Implement "infinite scrolling" for photo viewer

### ISSUE THREAD

**Issue by jimmcslim** [photoprism/photoprism#309]
May have found a bug on the main Photos view...

1. On the main Photos view,
2. Click on a Photo to go to the 'Lightbox' (?) view,
3. Click right to bring the next photo into the lightbox view,
4. Keep clicking right,
5. The lightbox view will cycle back to the start of the thumbnails that had been loaded in the main card/mosiac/list view, rather than progressing through the whole image database.

**Comment by lastzero** [comment]
It's because there is no infinite scrolling implemented, also for the edit dialog. It's on our todo.

**Comment by lastzero** [comment]
This issue is not as clear and easy as it seems since the list of images may change while viewing, for example because new files were imported in the meantime. This may lead to repeating photos or,  in case something was deleted (e.g. on another device), you may accidentally skip photos if a simple offset is used to load additional content.

**Comment by jimmcslim** [comment]
I agree that there are definitely edge cases. The context of an installation only used by a single user, I'd like to be able to go from the infinite scrolling cards/mosaic/list view, to the lightbox view and be able to 'infinitely click' next through the lightbox view. Maybe a best effort / eventual consistency principle should apply here?

**Comment by lastzero** [comment]
Maybe, tough decision. Even a single user installation is affected since users often look at photos while the indexer is running or files are synced in the background via WebDAV. Our card, mosaic and list views look simple and intuitive now, but it was a hell lot of work to get this right. 

The difference to the photo viewer is, that other views don't have a "single selected photo". When the index jumps, it feels like a HUGE bug - the wrong photo, a totally different time, very unexpected. Even though it can be explained technically. So we would have to find the nearest other photo from a common sense perspective and maybe show some kind of animation to indicate data has changed and the number, order or contents of the images may have changed in the background.

**Comment by lastzero** [comment]
Instead of using infinite scrolling, we could load up to 1000 photos when the viewer is opened. That way we have a consistent list and order and at least a higher limit. On the other hand, it would cause an additional backend request, thus affecting performance / UX since we can not use the existing result list.

**Comment by lastzero** [comment]
Option C is to preload additional search results, but don't render them to avoid loading all thumbnail images at once. This would also make infinite scrolling faster since we don't need to wait for a request to complete. On the other hand, it will often create more backend requests than actually needed, like when you just try different search terms without actually browsing through results.

**Comment by lastzero** [comment]
Update: Still thinking about the best solution, eventually it will come into my mind. For now, it's best to continue with albums. This is somewhat related in that albums must always be fully loaded in the photo viewer so that slideshows of a single album don't end early.

**Comment by lastzero** [comment]
This "quick fix" should solve the issue for users who want to show an album, unless the album contains more than 480 photos. In that case, they probably have enough time to scroll down or send a pull request with a better solution :)

**Comment by lastzero** [comment]
Page size reduced to 120... 480 might download 100 MB of thumbs at once... not good on mobile :D

**Comment by lastzero** [comment]
This UX improvement will load the **photo viewer** ("lightbox") with up to 3333 search results or album entries if not already loaded in the main view.

Note: 3333 photos might already be too much, I expect the next bug report to be "running out of memory, please help!1!!!". Good thing is that the viewer will only load the actual photos on demand, but the old ones remain in memory. This can easily get out of control if the browser doesn't have extremely good memory management.

**Comment by lastzero** [comment]
Just fixed a huge bug, basically the wrong or no photo was shown. Much better now!

**Comment by lastzero** [comment]
One more improvement since - as expected - the loading delay was bad for UX. So now results are loaded upfront und also updated in the background in case of changes. Hope is is worth all the complexity! ;)

**Comment by lastzero** [comment]
Seems to work, received no complaints. Please create a new issue if you find a bug!
