### ISSUE TITLE
Make video sidecar JSON files' dir configurable

### ISSUE THREAD

**Issue by linosgian** [photoprism/photoprism#311]
It would be great to be able to keep the `read-only` flag also indexing videos properly. My rationale is around keeping my setup with the flag enabled is that I use my photos as a source for various apps/software, it's not a matter of trust to photoprism itself but rather that I don't want my originals' folder to get littered with sidecar files that only concern photoprism. These files will show up everywhere.

As @lastzero mentioned  in https://github.com/photoprism/photoprism/issues/17#issuecomment-628539546 in order to achieve this, photoprism needs to support having additional files outside the originals' folder.

If you want to guide me through what needs to be done, I'd volunteer to implement it.

**Comment by lastzero** [comment]
I knew this feature request wouldn't take long 🥳

What about we add the option to create additional files in `originals/.photoprism`? That way users can create a backup without having them directly mixed with pre-existing files. Also they don't need to mount even more docker volumes. Using the temp and cache directories doesn't seem right as I would expect some users to put them on temporary volumes and delete them from time to time.

**Comment by linosgian** [comment]
That should work, but would you consider having it configurable for anyone that's willing to mount it elsewhere entirely? And keeping the `originals/.photoprism` as the default.

**Comment by lastzero** [comment]
Working on it right now... having it somewhere completely different is not as easy as the complete prefix / path would be different, so there are much more code changes needed.

**Comment by linosgian** [comment]
I see. Would we be able to keep the `read_only` flag on with the `originals/.photoprism` path? It kind of defeats the purpose of it since the sidecar file will have to be written under `originals`, but still, the originals folder will be kept intact for the most part (other operations).

**Comment by djbarney** [comment]
I love this product, but having the json files be created in a location under my  "originals" location, would defeat the "read-only" mount i've configured in docker (running on a synology nas). As many others have stated, it's not that i do not trust PhotoPrism, but if i want to use the json sidecar functionality for improved exif data, i do end up with an "altered" Originals folder. I know it doesn't alter my photo's itself. With the originals mount put on read-only, the read-only flag and the json sidecar flag set to true, every single photo indexed will generate an error currently.

It might be a much more difficult thing to realise in code, but we have a database generated, would it not be possible to put the json files or contents of those files there as well? then your library of indexed items wouldn't be split "data-wise", all metadata in the database, and thumbnails in the mounted folders as set before. I'm not a go-coder, so im not sure how hard this would be to do.

Thanks for the awesome support and dedication!

**Comment by lastzero** [comment]
Using a relational database as file storage is typically not a good idea, we could use the cache or temp path for JSON files in read-only mode instead. They can be recreated relatively fast in case they get lost.

For JPEGs automatically created from RAW, PNG or MP4, it's more difficult as those are first-rank citizens of our index / files tables and you should backup them as re-creating them every time the cache / temp path gets lost is a hell lot of work. Already thought about not indexing files without JPEG representation at all in read-only mode so that the index doesn't contain hidden files.

**Comment by lastzero** [comment]
In a first step, automatically converted files are now created in a `.photoprism` subdirectory so that they don't get mixed with manually created files.

If read-only mode is turned on, we could create JSON files in the cache directory as a next step although that's more complicated than you might think since the user may move and rename originals randomly. Using the original file name as cache key is not the best option in this case. So maybe it makes sense to store JSON in our database for each photo after all. Need to think about it before we continue.

**Comment by linosgian** [comment]
That's great. If you need help implementing this, I'd be willing to do it. If you decide that that's the way to go. I'd love to keep my `originals` folder clean, since as I said before, I point various software to it.

Cheers! :]

**Comment by lastzero** [comment]
@linosgian JSON is relatively easy since it's just metadata... do you also have unconverted RAW photos you would like to browse in PhotoPrism?

As mentioned, keeping JPEGs separate based on the file name is bad in that backups will only contains RAWs (which might be not be readable in 20 years from now, JPEG very likely will still work somehow) and renaming might lead to missing and (worse) wrong JPEGs. The only option is to use sha1 hashes here, but then you have no chance to find the matching file manually and lookups can be slower if the hash is not already known. Tradeoffs everywhere.

**Comment by lastzero** [comment]
In part, we already have the renaming issue now when you move originals but don't move the matching files in `.photoprism`. This may lead to lost information, like when you backup metadata to YAML files. Basically we'd have to include a sha1 in there too and automatically move them for the user when the original was moved. That's one of the reasons we prefer to index files in our database, so that they can still be matched, even if they have been moved. If the files are outside the originals directory, we can not index them anymore though.

**Comment by djbarney** [comment]
> @linosgian JSON is relatively easy since it's just metadata... do you also have unconverted RAW photos you would like to browse in PhotoPrism? RAW in this case includes all files other than JPEG, since we create thumbnails from a full-resolution JPEG (also for performance reasons, since JPEGs are small compared to RAWs, videos and even PNGs).
> 
> As mentioned, keeping JPEGs separate based on the file name is bad in that backups will only contain RAWs (which might be not be readable in 20 years from now, JPEG very likely will still work somehow) and renaming might lead to missing and (worse) wrong ~JPEGs~ thumbnails. The only option is to use sha1 hashes here, but then you have no chance to find the matching file manually and lookups can be slower if the hash is not already known. Tradeoffs everywhere.

^ I might not fully understand this reasoning. Shouldn't the user be the owner of their photo's and therefore be responsible for backups or readability of their fileformats in 20 years? I'm not sure Photoprism should play a role there. For me personally, I view photoprism as an amazing viewer that augments my "raw photocollection", without touching the originals. Making backups of these files is up to me (and well taken care of imho by not giving any program write permissions, and making regular incremental backups to a different nas).

There is a case to make for files uploaded through photoprism, as in a way those files could be considered "the originals", but even then, i'd consider putting them in a similarly protected folder as  the (in my case) read-only mounted originals folder, and keeping all analyzed metadata, thumbnails and everything else that augments my photo's, in a separate spot. I'd be completely ok if at any moment i'd lose the metadata, photoprism databases, thumbnails or anything created by photoprism, as long as it has never touched my originals folder. With that folder and my own backups, i can always re-index back into a working photoprism, even though that would take long.

For files that are moved or even edited outside of photoprism, is there a way for photoprism to detect that some files in the library are no longer where photoprism last had seen them? in that case, just spitballing here, maybe it would be nice to present the user with a prompt or something like that, telling the user that "files in location x can no longer be found, would you like to remove these from the library or specify a different location for these files?" and then re-index the newly given location, compare to info already in the external metadata files and database and either replace the files path in the db or regenerate metadata and add them to the library? I get that this one is a difficult situation to deal with, i'm just thinking of how for example adobe lightroom might do this. lightroom doesn't touch my originals either, and if i move photo's on my nas to a different folder, it will prompt me to ask where they went, and validate that they are indeed at that new location and/or altered since including in the album they went missing from.

**Comment by lastzero** [comment]
> ^ I might not fully understand this reasoning. Shouldn't the user be the owner of their photo's and therefore be responsible for backups or readability of their fileformats in 20 years?

Guess I'm user and developer at the same time. Do you suggest starting a second project for automatically converting RAWs? :D

> For me personally, I view photoprism as an amazing viewer that augments my "raw photocollection", without touching the originals.

We don't touch them. The question is how and where to store related files, if not for creating backups than for good performance and user experience. They at least shouldn't get lost all the time.

> i'm just thinking of how for example adobe lightroom might do this. lightroom doesn't touch my originals either

Adobe Lightroom copied all my originals to a hidden directory that is very much organized like our directory structure when you import files. Do you use a different version or are there special settings I haven't found yet?

![Screenshot 2020-05-19 at 13 56 03](https://user-images.githubusercontent.com/301686/82323541-7f8aa600-99d8-11ea-9d94-1245c32c9439.png)

**Comment by djbarney** [comment]
I'm both a user and a .net developer, but im very tempted to take a poke around in this codebase and see how it works exactly. I love that we can have this open discussion btw!

I use Lightroom Classic Cc, that might indeed be a different version. It created a folder inside my C:\users\username\pictures\lightroom by default (location of which is changeable in settings), where it creates a similar setup to what you show with the .lrlibrary, except these are called "Lightroom Catalog.lrcat" instead, and it doesn't have a copy of my photo's there. it seems to be previews and metadata db files only.

![Annotation 2020-05-19 141416](https://user-images.githubusercontent.com/36897259/82325168-10628100-99db-11ea-85da-acaaa04278d4.png)

The folder with "the originals" in this case, is a copied folder i made myself. At the point i started using lightroom, i also did not fully trust the non-destructive editing etc they promise at https://helpx.adobe.com/lightroom-classic/help/lightroom-catalog-basics.html. The "originals" are again set read-only. The folder location is on my synology nas, and is also configured with read-only permissions through SMB, to make absolutely sure that nothing is altering my photo's, even though it's just a copy in this case.

The folder structure in the screenshot contains a helper.db file in the Lightroom Catalog Helper.lrdata subfolder, 16 subfolders with corresponding thumbnails / previews generated by lightroom in the Lightroom Catalog Previews.lrdata folder, along with another 2 .db files called previews.db and root-pixels.db. Not sure exactly what is in them, but the total folder weighs in at around 788mb for this catalogfolder of 4482 photo's, raw nikon and jpeg mixed. in this catalog, it's somehow keeping track of all exif data, including gps location etc, which i think it keeps in the previews.db file.

The important thing for me, is that the mounted "originals" folder, has in fact, not been altered. No changes to folder structure, no hidden stuff, no alterations to exif, xmp or even standard "edited on date x" metadata.

**Comment by lastzero** [comment]
Great to have somebody here with Lightroom experience 👍 

I tested it because somebody said it supports XMP sidecar files for syncing with other apps (like PhotoPrism), but all I managed to get is XMP data embedded in JPEG. Probably the originals unless there are multiple copies of the same file, which would be a waste of storage.

More questions if you have time:
1) How does Lightroom manage moved, renamed or modified originals? Will they be indexed as copy or does it (reliably) detect the file was just moved?
2) Is it possible to lose metadata by moving, renaming or editing originals?
3) Will Lightroom combine copies of the same file (or the same photo in different formats like JPEG and RAW) into one photo, so that the same image doesn't show up X times in search results?
4) When you create a JPEG with Lightroom, will it be stored in a hidden, internal directory (the catalog / library) or in the originals folder next to the RAW file it was made from?

In Lightroom, there's probably a difference between automatically and manually created JPEGs, while technically it's the same: A file in a format that is helpful for the use case (view in browser) and that may belong to other, related files. I for myself like to see what's on my disk and I don't like apps using my storage without telling me what's there. I also don't have time to manually convert all my RAWs. Our idea is to use what's there and if PhotoPrism creates something for you, shows you what it is without hiding it away in a big fat hidden folder. In fact, our thumbs directory may already get very large, but at least you can delete and re-create it without losing anything valuable.

This of course doesn't exclude optional settings for a behaviour that mimics Lightroom! Except when it comes to storing XMP metadata in JPEG headers of originals. That's especially bad if you have multiple versions (like different sizes) that each contain slightly different information, depending on when they were saved / updated.

**Comment by lastzero** [comment]
Think it should be possible to add another config value like `PHOTOPRISM_SIDECAR_PATH` that points to a different directory than `PHOTOPRISM_ORIGINALS_PATH`. Let's call this **Option A**. However, as mentioned above, renaming files in originals will likely break this if the directories use the same folder and name structure. Impact could be missing thumbs or backups in case the database gets lost.

**Option B** is to use the existing cache directory to store sidecar, jpeg and backup files based on the sha1 hash of the original. Editing the original would break this as the hash changes. That also means we need to implement a garbage collection process to save storage. Note that Lightroom and Photoshop tend to modify originals when metadata changes, even though there seem to be settings to turn it off. Expect the worst.

**Option C** is a combination (the nuclear option) which would add an additional table to our index that keeps tracks which files in which directories belong together based on different criteria such as name and hash (pretty much like the originals directory is currently managed, but more complex with a second base path).

**Comment by lastzero** [comment]
`Option B 2` is to store file contents in a database table that references the original file. This of course only is feasible for smaller sidecar files, not JPEGs and other large binary files. For those files, we could store the location in the filesystem, so the filename would not be correlated to the original in anyway (no hash, no similar name). It's probably what Microsoft would do for maximum vendor lock-in :D

**Comment by linosgian** [comment]
I think that Option A does not seem that bad. All of the thumbnails can be recreated with the original RAW/JPEG files. It might take sometime, but the _losing the database_ issue is quite a big one. I think that the most valuable info that the database holds right now is the albums. Once photoprism provides a stable database schema and users start to build their albums, it would be much more important to lose. All in all I think option A is seemingly the _easiest_ solution when it come to implementation, and sort of straightfoward, since all the logic of how images are handled remains the same, expect for the image/sidecar files' paths, or rather, the directory will be configurable rather that using that of the original photo.

Also, about the backups, users can definitely take measure to backup the `.photoprism` folder, in case they don't want to lose the generated JPEG files, as you said. If I'm honest photoprism shouldn't take that decision for them, beforehand and without choice presented to them.

As @djbarney mentioned above, I view photoprism as one the very few, self-hosted solutions to view photos (hopefully soon I'll migrate to the newer versions, that support videos too), It's not too complex (except for the dependency to download specific versions of tensoflow from dl.photoprism.org, but that's something that should be discussed in another issue), it's written in Golang, that I'm familiar with, and also it's actively developed (also props for the maps integration with the exif GPS metadata, it's awesome). Hence, I expect it to do these things well and for the time being nothing more. If I want to edit my photos (e.g. generate JPEGs from the RAW files, add a `DateTaken` exif entry, I'll probably do it through some other software. If photoprism expand its functionality to do that too, I will reconsider the way I use it.

**Comment by lastzero** [comment]
> I think that Option A does not seem that bad.

Thanks for voting :)

> Also, about the backups, users can definitely take measure to backup the `.photoprism` folder, in case they don't want to lose the generated JPEG files, as you said. If I'm honest photoprism shouldn't take that decision for them, beforehand and without choice presented to them.

That's why new config values are added every week. We'll do our best to document them with their specific advantages and tradeoffs, but it's overhead and leads to slower development. Techies should keep in mind that the average user might want to have less, not more choice.

> Hence, I expect it to do these things well and for the time being nothing more. If I want to edit my photos (e.g. generate JPEGs from the RAW files, add a `DateTaken` exif entry, I'll probably do it through some other software. If photoprism expand its functionality to do that too, I will reconsider the way I use it.

In fact we "only" use darktable on behalf of our users who don't have time to do everything manually or using a collection of different tools. This is all optional, you can turn it off and do everything full manual. I personally like the convenience and probably others too.

**Comment by lastzero** [comment]
This seems done with our latest improvements?

**Comment by linosgian** [comment]
This seems like it's done indeed. I've migrated both my photoprism instances to the latest version and also mounted the docker volume holding my originals folder as readonly, just to make sure everything is working as expected. Indexing is done, browsed the photos for a bit, no errors thrown so far. Cheers :partying_face:
