### ISSUE TITLE
Import new added files only

### ISSUE THREAD

**Issue by guim31** [photoprism/photoprism#322]
Please forgive me if I shouldn't post something like this here... but I did not find any place to ask the question.

I'm using Photoprism on my unraid NAS (running in a docker container) since 2 days.
I have a cron job that copy files from my phone into my /photo folder on my NAS.
The /photo folder is the one Photoprism is looking at (/Pictures/Originals in the container)

How shoul I do to update the Photoprism library with the new files only ? 
I have to re-index everything everytime... and this process is long as there are about 10k photos.
Photoprism skips all the "old" pics it allready indexed, but still this is very long !

**Comment by lastzero** [comment]
No problem: That's why we have the import feature. By nature, any file in the originals folder may change. It's more efficient just to copy and process new files than to scan all existing files.

In addition you can sync with WebDAV, which will also just index or import new files.

As a third option, you can index only one folder, depending on how you organize your originals:

![Screenshot 2020-05-19 at 19 30 29](https://user-images.githubusercontent.com/301686/82358764-4289d800-9a07-11ea-94d3-ed9e9c5fee32.png)

**Comment by guim31** [comment]
Ok, thanks for this answer.
This is where I understand that I don't understand !

I have mounted a `/Import` folder in my container... but I don't know its purpose nor how to use it.

My folder tree on my NAS looks like that :

```
Pictures
|____ Originals
|_______ file1.jpg
|_______ file2.jpg
|_______ file3.jpg
|____ Import
|_______ _empty for now_
```

Should I put new photos I want to add in the IMPORT folder, and then Photoprism will move them in the ORIGINALS folder ?

**Comment by lastzero** [comment]
Right, the files will also be renamed based on year, month, day and time to avoid duplicates (otherwise you might import the same files over and over again). Try with a few test files. You can also find a short description in Library > Import.

**Comment by guim31** [comment]
Just tried it and it worked good :+1: 

But the files where not renamed. I wish they were. 
I did not set a READONLY variable, not mounted "originals" as RO volume

**Comment by lastzero** [comment]
We don't rename existing files so that creating a backup / syncing is easier. Other tools might not find the files anymore too.

**Comment by bugs181** [comment]
You're contradicting yourself and creating more confusion.

> Right, the files will also be renamed based on year, month, day and time to avoid duplicates (otherwise you might import the same files over and over again).

And then you say:

> We don't rename existing files ...

So which is it?

**Comment by lastzero** [comment]
We don't rename existing ORIGINALS. We MAY rename files moved to originals during import so that they have unique names.

**Comment by lastzero** [comment]
Please give us some time to complete and improve our docs, obviously this is still on the todo. The point here was to simplify backups of originals. You don't create backups from the import directory which is a temporary folder for uploads. Of course we need to rename uploaded files, otherwise the same file might be added over and over again ;)
