### ISSUE TITLE
Metadata: Extend valid year range from 1990 to 1970

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#3220]
As a user with scanned images taken before 1990, I would like to see earlier years supported in the Exif metadata so that they are indexed and displayed properly.

**Comment by dinoschachten** [comment]
Nice idea! Sorry for only pointing this out now (didn't see this earlier) - if it doesn't make a difference how far the range is extended, I'd suggest to increase it even further:
Some people have scans of older photos or even scans of art predating the photography era. Would it be a problem to extend the range to the year 0?

**Comment by lastzero** [comment]
It can make a difference, 1970 is a safe tradeoff as it's the beginning of Unix timestamps also commonly used in filesystems: https://en.m.wikipedia.org/wiki/Unix_time

**Comment by dinoschachten** [comment]
True. My thinking was that with your intention to use this value to indicate the creation of the original content rather than a file creation (scan) date, the requirements for this piece of metadata tend to go beyond what makes perfect sense for filesystems etc. as the original analog media can easily predate 1970.

However my understanding of UNIX time as described in the Wikipedia article is that through negative values and the use of enough bits the range is extendable in both directions, making 1970 merely an (arbitrary) reference point? In that case I obviously agree that choosing this widely accepted format is a good, clean solution that poses no obvious limitations. 😊

**Comment by GlassedSilver** [comment]
We shouldn't mistake the photo date with the digitalization date. Digikam for example lets you set both separately.

**Comment by graciousgrey** [comment]
@GlassedSilver PhotoPrism does not currently support a separate digitization date. We focus mainly on digital photography, where CreateDate and DateTimeOriginal should be approximately the same. 

We know this is not the case for e.g. scanned images. You are welcome to open a separate feature request for this.

**Comment by GlassedSilver** [comment]
I think with the current hype around film (which reminds me a lot of vinyls rising in popularity for years now) there's quite a need for this - both current as well as many years old photographs would profit from tracking digitization dates separately from the date of the shot. I'll make an issue for this, thanks for the encouragement!
