### ISSUE TITLE
WebDAV: Display upload and sync status of individual files in the UI

### ISSUE THREAD

**Issue by eljejer** [photoprism/photoprism#3318]
**Describe what problem this solves and why this would be valuable to many users**

As a result of not optimal web server configuration, I experience incomplete WebDAV uploads.
This is not announced in the web UI

I share an album containing 118 photo's by selecting this album, clicking the Share button and then choosing WEBDAV UPLOAD. After selecting the WebDAV account and folder to which the album should be uploaded, I press UPLOAD.
Immediately a pop up message "118 files uploaded" appears.
When this process (partially) fails, there is no feedback about this in the UI.  
Also in the Log section, nothing  is reported about a failed upload

**Describe the solution you'd like**

I would like the feedback pop up to appear regularly during the upload. And not the way it is programmed at the moment:
"we will upload so and so many files, so let's report this as being processed instantly".

I would like to receive e message about a (partially) failed WebDAV upload

**Describe alternatives you've considered**

The way I found out about it now, was checking the journal for error messages of the web server

**Additional context**

In my case I run PhotoPrism in a container on Linux laptop and the web server runs on a home server with Arch Linux.
I have set up a routine where I make a selection of my photo's o the laptop that I want to share to the Linux home server where nextcloud and nginx are installed. Then I can show these photo's on my TV using either Plex, Jellyfon and or Kodi

**Comment by lastzero** [comment]
Could the upload problems be related to this issue, for which we have just supplied a fix?

- #3310

If so, we would appreciate help with testing!

Please note:

- The upload is running in the background and may take a while. Therefore, immediate feedback on whether everything was successful is not possible. However, the general error logs may contain information.
- You can also check the `files_share` and `files_sync` tables with any standard database UI or command line client. Unfortunately, due to many other feature requests, we will not be able to provide a web UI for this in the near future.
- The upcoming multi-user functionality makes this more complex as not everyone should be able to see everything and get all the notifications, meaning any UI we develop must limit the scope of what is displayed.

**Comment by eljejer** [comment]
@lastzero Personally, I haven't seen any corrupted photo's on the nexcloud end. Only "incomplete", in the sense that the batch as a whole was not being received on the nextcloud server. I was missing a number of files.

**Comment by eljejer** [comment]
I can imagine that I can try to force the webserver configuration in a state that "my error" occurs (again) and check whether or not photo's are corrupted as a result of this state.

**Comment by eljejer** [comment]
@lastzero While examining the partial upload, I also encountered something that was unexpected; may be a bug?
- I remove the incomplete batch from nextcloud
- I upload the same batch again from photoprism to nextcloud with an altered nextcloud/nginx configuratin 
- no files er being received when I use the same receiving directory
- only when I use another directory name, will the files be transferred
Very strange...

**Comment by lastzero** [comment]
Make sure to use our preview build before reporting issues as the webdav client has been completely reworked and thus behaves differently in all aspects.
