### ISSUE TITLE
Using photoprism without Docker

### ISSUE THREAD

**Issue by ligurio** [photoprism/photoprism#333]
I'm using BSD where there is no Docker support at all.
How to install and use photoprism without Docker?

**Comment by poerhiza** [comment]
See https://github.com/photoprism/photoprism-docs/pull/9 for fedora - I imagine it'll be close to that.

**Comment by lastzero** [comment]
Somebody is using PhotoPrism with FreeBSD, maybe it was @savegame?

In general, you would build / install it like a developer since we don't have packages or a port for BSD, see https://github.com/photoprism/photoprism/wiki/Setup

Instead of using Docker, you can manually type the command listed in the Dockerfile and replace Linux packages with BSD packages.

**Comment by savegame** [comment]
yes, i build photoprism from sources in FreeBSD jail (like docker/chroot for linux) in FreeNAS. 
Other dependecies for photoprism i get from FreeBSD ports (like tensorflow)...
For now, i really dont have much time for creating some Wiki page - how to build and install Photoprism on freebsd, sorry ... maby later, i really like this project and help with it as soon as posible.

**Comment by lastzero** [comment]
Added this to our FAQ:

### I'm using an operating system without Docker support. How to install and use PhotoPrism without Docker? ###

In general, you would build / install it like a [developer](../developer-guide/setup.md) since we don't have packages for specific operating systems yet.

Instead of using Docker, you can manually type the commands listed in our development [Dockerfile](https://github.com/photoprism/photoprism/blob/develop/docker/development/Dockerfile) and replace packages with  what is available in your environment. You often don't need to use the exact same versions for dependencies.

If your operating system has Docker support, we recommend learning Docker as it vastly simplifies installation and upgrading.

**Comment by savegame** [comment]
steel work on freebsd ;-) ( but problems with tensor flow, it disappear from ports... ) 
<img width="348" alt="Снимок экрана 2020-09-08 в 23 15 48" src="https://user-images.githubusercontent.com/16311332/92523739-88261700-f229-11ea-9c2c-34cb202fd157.png">
