### ISSUE TITLE
Config: Title of the search page must be set based on the site title

### ISSUE THREAD

**Issue by edwinclement08** [photoprism/photoprism#3439]
#### 1. What is not working as documented?
When setting the PHOTOPRISM_SITE_TITLE environmental variable via PHOTOPRISM_SITE_TITLE, the search page still shows 'Photoprism'.
The other pages like Albums and Favourites show the '<page name> - <site title>' as expected.

#### 2. How can we reproduce it?

Run the docker container with PHOTOPRISM_SITE_TITLE env variable set to anything other than Photoprism

#### 3. What behavior do you expect?

The Title of the page to be <site title> when on home page

#### 4. What could be the cause of your problem?

Not sure

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

![image](https://github.com/photoprism/photoprism/assets/9532892/1b6b626c-0188-42e4-9544-e039b855daa6)
![image](https://github.com/photoprism/photoprism/assets/9532892/db6331c2-0deb-4042-a4eb-03ea3237e50a)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: PhotoPrism® CE Build [230514-0b780defb]

(b) Database Type & Version: SQLite

(c) Operating System Types & Versions: Windows

(d) Browser Types & Versions: Firefox, Chrome

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?
No

#### 7. On what kind of device is PhotoPrism installed?

Unraid

(a) Device / Processor Type: 
Intel Core i7-3770

(b) Physical Memory & Swap Space in GB
16 GB, 1 GB

(c) Storage Type: HDD

(d) Anything else that might be helpful to know?

Did try to edit options.yml and got the same result.

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

No

**Comment by lastzero** [comment]
While I recognize that there is room for improvement, this seems to work more or less as intended. Could you additionally try setting `PHOTOPRISM_SITE_CAPTION` and `PHOTOPRISM_APP_NAME` to see if/how that changes the title of the page? I'm in a hurry and can't check the code in detail right now, but I remember there is logic that uses all of these values to generate both the toolbar and HTML page titles.

**Comment by edwinclement08** [comment]
I tried `PHOTOPRISM_APP_NAME` as well, but that didn't seem to effect the name on the browser. The `PHOTOPRISM_SITE_CAPTION` I have kept as `Browse Your Life` and that is not what is shown.
The reason I wanted this functionality is that I have multiple instances of photoprism for my family and it becomes a bit confusing when more than a couple of them are open. All of the pages are titled `PhotoPrism`.

**Comment by lastzero** [comment]
Yeah, so it is possible that overwriting the title with `PHOTOPRISM_APP_NAME` currently only works in our Plus version, since this might be implemented as a "proof of concept" in the extension we provide to our members. If so, we may eventually add this tiny tweak to our regular version as well.

In the short term, you can also achieve the behavior by adding a line or two of Go if you are comfortable with building from source.

**Comment by lastzero** [comment]
@edwinclement08 Thanks to your report, I found a line in our frontend code that should not be there and caused a different behavior in our community edition. I apologize for that. After removing this line, I tested it again. For this I started the server as follows (of course you can use environment variables instead):

```
photoprism --site-title="TITLE" --site-caption="CAPTION" start
```

To verify the effect of the config values, I've then used this command, which confirms that the site title was applied to the app name:

```
photoprism --site-title="TITLE" --site-caption="CAPTION" config | grep TITLE 
| app-name               | TITLE            |
| site-title             | TITLE            |
```

If a site-caption is set, it will be used as page title on the (default) search page:

![search-caption](https://github.com/photoprism/photoprism/assets/301686/3a9fed58-88dc-4baf-8416-f2c21e004f98)

Otherwise, and on all other pages, the configured site title will be used:

![albums-title](https://github.com/photoprism/photoprism/assets/301686/92af0c85-b8b4-4f53-a990-ecf9fefb9a92)

I would appreciate if you could test it again with this change. An updated development preview build will be available soon!

**Comment by lastzero** [comment]
The release notes have been updated to mention this issue:

https://docs.photoprism.app/release-notes/#development-preview

These docs explain how to use our preview build:

https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by edwinclement08** [comment]
Hey @lastzero, thanks for your quick fix. Updating Caption and Title to the same value resolved the issue.

**Comment by lastzero** [comment]
Thank you very much for testing! We will try to release a new stable version with this fix in the next few days. In the meantime, our development preview is generally safe to use, as it does not contain any breaking changes or known issues.

**Comment by edwinclement08** [comment]
Thanks a lot😄.
