### ISSUE TITLE
Documentation: What exactly does read only mode

### ISSUE THREAD

**Issue by twatzl** [photoprism/photoprism#344]
Hello, 
I am currently trying to figure out whether to use read only mode or not. However I could not find any good documentation on what read only mode exactly does or what photoprism does when not in read only mode.

`photoprism help` only tells me the following: 
`   --read-only, -r                      don't modify originals directory (reduced functionality) [$PHOTOPRISM_READONLY]`

Maybe the docs could be extended with information that answers the following information:
- what does read only mode do?
- what features will not work when photoprism is in read only mode?
- how does photoprism behave when NOT in read only mode?

**Comment by lastzero** [comment]
Improved our flag description and added this to our FAQ:


### What exactly does read-only mode? ###

There are users who don't want us to modify their original files and folders in any way, so we've added a configuration option for this use case. It will disable uploads, import and all other features that might rename or delete files in the originals folder.

**Comment by twatzl** [comment]
Hmm. I am still not sure. The issue is "all other features" as someone who is not involved in development I have no idea what this affects. It would be cool to have a list of what actually gets disabled. Or even better a feature list/table with the info what works and what does not work in offline mode. (this would btw also make it easier to understand what photoprism is capable of in general)

Also i am not sure what you mean by import. Just the moving of images within the collection or does this also affect the AI labelling?

Sorry if my questions are stupid, but from my point of view as a user I want to get an idea of what I can expect before running it.

**Comment by lastzero** [comment]
This would be an affected feature: https://github.com/photoprism/photoprism/issues/167

Reason I wrote "every feature" is that I can't update the docs in the exact same moment I implement a new feature that would, according to common sense, be affected by the read only mode.

Import is a copy function, so you can copy files to your library. Pros and cons are described in our new user guide (work in progress) and our FAQ:

### I'm having issues understanding the difference between the import and originals folders? ###

Import is a temporary folder from which you can move or copy files to originals in a structured way that avoids duplicates. Most users with existing collections will want to index their originals directly without importing them, so that existing file and directory names stay the same. On the other hand, importing is more efficient when adding files as you don't need to re-index all originals to find new photos and videos.

**Comment by twatzl** [comment]
Ok. Thanks I think this will work out.
