### ISSUE TITLE
Video: Limit FFmpeg Transcoding Resolution

### ISSUE THREAD

**Issue by lukasdotcom** [photoprism/photoprism#3466]
**Describe what problem this solves and why this would be valuable to many users**

A lot of the time I am recording video in 4k, but on all of the clients I never actually need to watch the video at 4k and the sidecar file is then unnecessarily big and uses an unnecessary amount of bandwidth when played.

**Describe the solution you'd like**

For this purpose the environment variable "PHOTOPRISM_FFMPEG_SIZE" should be added to set the maximum resolution FFmpeg converts the video to, for example:

- `PHOTOPRISM_FFMPEG_SIZE=720`
- `PHOTOPRISM_FFMPEG_SIZE=3840`

**Comment by lastzero** [comment]
@Lukasdotcom @theresagresch I wonder if it makes sense to only allow standard video resolutions to be specified? So HD, Full HD, Ultra HD, 2K and 4K. For example, few users will know that 4K actually means 3840 × 2160, and NOT a width of 4000 or 4096 pixels, as one might assume.

**Comment by lukasdotcom** [comment]
We could either add cases to the original environmental variable to detect sizes like HD, HD+, UHD, 2K, and 4K and that they will cause certain predetermined resolutions to be used. Or you can only put in the more human readable names in that environmental variable and we create a new one that works like the original one called FFmpeg Resolution Advanced.

**Comment by lukasdotcom** [comment]
Ill make a new pull request for either option depending on what you think is the better option.

**Comment by lukasdotcom** [comment]
I just made the pull request based on the option where the FFMPEG_RESOLUTION variable can either use a standard one or an advanced user can specify a resolution down to the pixel #3549.

**Comment by lastzero** [comment]
@Lukasdotcom Thanks a lot! I appreciate your PR but was prepared to refactor the config option myself today :)

**Comment by lastzero** [comment]
@Lukasdotcom After checking all possible options, I decided to (re)use the default sizes defined in the thumbs package and adjust the config value to the next appropriate size. Supported sizes can be displayed by running the `photoprism show video-sizes` command in a terminal.

I also renamed `PHOTOPRISM_FFMPEG_RESOLUTION` to `PHOTOPRISM_FFMPEG_SIZE` so that the name of the option matches the image quality options e.g. `PHOTOPRISM_THUMB_SIZE` and `PHOTOPRISM_JPEG_SIZE`.

**It would be great if you could quickly review my changes and let us know if this works for you so we can release it this week. Thank you!**

**Comment by lastzero** [comment]
The overview of config options has been updated in our docs: https://docs.photoprism.app/getting-started/config-options/#file-converters

**Comment by lukasdotcom** [comment]
Looks good to me. You might also want to mention in the docs that the resolution is only changed if the bitrate limit is exceeded.
