### ISSUE TITLE
Darktable: Color profiles are not preserved in converted images

### ISSUE THREAD

**Issue by aperture147** [photoprism/photoprism#3479]
Hi, I'm using PhotoPrism to store my ARW images and convert them to JPEG.

I'm aware that PhotoPrism is using DarkTable to convert RAW image to web-safe JPEG, which will normalize all images with wide gamut  color profile (like AdobeRGB or ProPhotoRGB) to sRGB IEC61966-2.1. 

Is there any option to make PhotoPrism preserve color profile of an image after converting or convert it to a target color profile (like DCI-P3 or AdobeRGB) instead of sRGB?

Thank you!

**Comment by lastzero** [comment]
Embedding color profiles isn't easily possible with the native Go libraries we use right now, which is why we plan to add support for generating thumbs with libvips.

**Comment by aperture147** [comment]
> Embedding color profiles isn't easily possible with the native Go libraries we use right now, which is why we plan to add support for generating thumbs with libvips.

As PP is using Darktable cli to convert images, is there any option of darktable-cli to preserve the color profile? I can't find any document of darktable... if there is then we can safely use that to preserve the color profile, then actually we don't need an option to change target color profile anymore, since color profile conversion is a lossy conversion.

**Comment by lastzero** [comment]
I'm not a Darktable expert, but the manual mentions both Adobe RGB and custom ICC profiles: https://darktable-org.github.io/dtdocs/en/special-topics/color-management/overview/

Note that even then PhotoPrism would not be able to preserve this profile for the thumbnails because ICC profiles cannot be embedded with the native Go libraries that we currently use. So if you choose an exotic profile that isn't supported for normalization, your browser might display incorrect colors.

**Comment by lastzero** [comment]
Embedding ICC color profiles into our JPEG thumbnails seems to be possible with libvips:

- #1474 
 
Libvips is a very fast C image processing library for which a Go integration library also exists:

- https://www.libvips.org/
- https://github.com/libvips/libvips
- https://github.com/davidbyttow/govips

Any help with that would be much appreciated! 💎

**Comment by lastzero** [comment]
I just noticed that your original issue was about Darktable, not our thumbnails. Should it not be resolved with these changes, please let us know so we can update the Darktable CLI command if needed (ideally let us know what settings are required so that the color profiles are preserved in the generated JPEG files):
- #1474

**Comment by lastzero** [comment]
I'll move ahead and label this as successfully tested, since we didn't receive any feedback that would indicate otherwise.

**Comment by lastzero** [comment]
There's a user on Reddit who might be having similar issues?
- https://www.reddit.com/r/photoprism/comments/1cywqim/distorted_images/
