### ISSUE TITLE
Struggling to find documentation regarding Import vs Originals

### ISSUE THREAD

**Issue by bugs181** [photoprism/photoprism#350]
As the title states, I'm having issues understanding the difference between the Import vs Originals folders. As I don't plan to move all of my existing images, I had planned to expose those as docker volumes and then create symlinks to the pictures I want PhotoPrism to have access to. Which folder should my symlinks go in? What is the difference in how these two folders behave?

**Comment by bugs181** [comment]
Related #322

**Comment by lastzero** [comment]
We've described it here briefly https://docs.photoprism.org/en/latest/getting-started/docker-compose/ and also in Library > Import, which you already found.

**Import** is a temporary folder to move or copy files to originals in a structured way that avoids duplicates. Most users with existing collections will index their **originals** directly without importing them, so that existing file and directory names stay the same. You can use symlinks in originals, it's up to you where they point as long as PhotoPrism has the right filesystem permissions.

Note that Symlinks from mounted directories to directories invisible to Docker (not mounted) won't work, at least that's what I expect. Would be a big security issue otherwise because it would give all Docker apps access to all files. Instead, use Docker to mount directories to subdirectories `originals` like `/photoprism/originals/folder1`, `/photoprism/originals/folder2`,...

**Comment by lastzero** [comment]
Added this to our FAQ:


### I'm having issues understanding the difference between the import and originals folders? ###

Import is a temporary folder from which you can move or copy files to originals in a structured way that avoids duplicates. Most users with existing collections will want to index their originals directly without importing them, so that existing file and directory names stay the same. On the other hand, importing is more efficient when adding files as you don't need to re-index all originals to find new photos and videos.
