### ISSUE TITLE
Index: Skip and report media files with an invalid extension

### ISSUE THREAD

**Issue by vorezal** [photoprism/photoprism#3518]
**Describe what problem this solves and why this would be valuable to many users**

When indexing is attempted for invalid file types (e.g. jpg file extension that is actually a HEIF/HEIC file) it results in the file being hidden but also completely invisible to the UI. Adding an error message with enough details to find, convert, and reindex the original would facilitate cleanup without the need to run SQL queries.

**Describe the solution you'd like**

Add "invalid file type" warning in Library > Errors with original file information, path, etc.

**Describe alternatives you've considered**

As per the discussion linked below under additional context, adding a new error seemed like the most supported solution. I'm sure there are a number of alternative solutions however, including:

- Since the current implementation displays a count of hidden files under Library > Hidden but is unable to display any details when navigated to, an alternative may be to display invalid hidden files based on SQL alone. This may be more complex or technically infeasible however.
- Automatically detect the file type based on magic number, which in this case would mean checking the beginning of the file for the string ftypheic.

**Related Issues**

- https://github.com/photoprism/photoprism/issues/4118
- https://github.com/photoprism/photoprism/discussions/3489

**Comment by rphlo** [comment]
I have similar issue were extensions can not be trusted. What could be done would be to use libmagic on the files that trigger the error 'invalid file type'

**Comment by lastzero** [comment]
Instead of having PhotoPrism accept files with a wrong extension (which can also lead to vulnerabilities if you later want to block or ignore certain file types), you could use a script similar to this one to fix the extensions:

https://github.com/photoprism/photoprism-contrib/blob/main/scripts/Batch%20Rename/README.md

**Comment by pgalbavy** [comment]
I'm a very new user of PP, just trying to finish my first full index of > 1TB of 20+ years of photos and I have 16k+ hidden files. While I *could* go down into the DB and see the directories with the files, a non-tech user would find this impossible,

I wholly agree with:

> Since the current implementation displays a count of hidden files under Library > Hidden but is unable to display any details when navigated to, an alternative may be to display invalid hidden files based on SQL alone. This may be more complex or technically infeasible however.

Just showing the paths to the hidden files would be a big start. The reasons for it being missed from indexing is another story, but would also be useful.

**Comment by lastzero** [comment]
@pgalbavy When you open the photo detail dialog (e.g. by clicking on the title in the cards view, using the context menu or by clicking on the "Edit" button in the full screen viewer), you can see the full path and much more on the "Files" tab:

![Screenshot 2023-11-20 at 09 53 54](https://github.com/photoprism/photoprism/assets/301686/2fb10c96-7cbf-40a6-b89a-6579c2d4ae06)

You may also find further helpful information when you navigate to `/library/errors`:
- https://demo.photoprism.app/library/errors

**Comment by pgalbavy** [comment]
Thanks for the suggestion, but that only works if I can figure out which of my 16k files are "hidden". Without visibility of the list files and their containing directories you can't do anything. Where in the UI (or via the CLI) can I do that?

I think having a list - or folder hierarchy and files in each - would be a good UI feature.

Also, there was nothing of significance under errors - lots of NSFW moves, detecting my "red silver" Maine Coons - so I have turned that off - and a handful of failures to match faces because of connection errors (probably network blips overnight).

I have updated some settings I have learnt more about, fixed the QSV GPU access and am now running a new full index, but it will take 4 days or more, based on the last one.

Edit: As an aside, I think I found the cause of my hidden files - all my CRW files not being converted to JPEG as I initially ran in read-only mode to get a feel for the system. Subsequent non-full indexing didn't do much and while I have no cancelled the new full reindex and gone with "photoprism convert -ext crw ..." from the CLI, I will probably run a full reindex at some point. Not sure from the descriptions if the latter would kick off the conversion for missine thumbnails/JPEGs anyway.

**Comment by vorezal** [comment]
Just in case it does help you despite your edit, I've been using the following SQL query directly against the database to get a list of hidden files that are not displayed anywhere in the UI:
`select photo_path,photo_name,original_name from photos where deleted_at is NULL and photo_quality<0;`

You should be able to call this from the CLI and output the results to a file with something like this, if needed:
`mysql -u <dbuser> -p <database name> -e"select photo_path,photo_name,original_name from photos where deleted_at is NULL and photo_quality<0;" > output.txt`

I don't currently have any photos hidden like this, so it's a little difficult to fully test.

**Comment by lastzero** [comment]
Please note that these changes **need to be tested very well**, as mime type detection may not be 100% reliable for certain file types, especially videos and modern image types like heic(s).

An updated [photoprism/photoprism:test](https://hub.docker.com/r/photoprism/photoprism/tags?page=1&name=test) build will soon be available on Docker Hub. Any help with testing these changes is much appreciated! :pray:

**Comment by lastzero** [comment]
We removed the strict check for MP4 files, as we found that many such videos are based on MP4 but actually have a different (sub) type:

![Screenshot 2024-03-25 at 16 34 50](https://github.com/photoprism/photoprism/assets/301686/39a2cca3-c5f1-49fe-9add-3ee39942038c)

**Comment by lastzero** [comment]
If you would like to test this but don't have any suitable files, our sample archive can provide you with test files for all common types and formats:
- https://dl.photoprism.app/samples/Formats/

**Comment by steven-ellis** [comment]
@vorezal There is a side issue with this approach where you're using a tool like rclone to backup Google Photos (see #4421).

You can't simply rename / change the extension as that will break future syncs. DO we have an alternative option such as check the file content (like .mp4) or perhaps create a symlink rather than a rename.

**Comment by anthraxn8b** [comment]
I guess this is exactly my problem.
I have a lot of errors like this one:

index: skipped 2015/01/20150130_000000_DE06EBAF.jpg due to invalid extension for media type 'image/png'

How would I fix this in a "best practice" way?

**Comment by Issomane** [comment]
@anthraxn8b 
The issue is closed. 
You might want to create a new one
