### ISSUE TITLE
Videos: QuickTime files are ignored by the convert command

### ISSUE THREAD

**Issue by mario-g98** [photoprism/photoprism#3525]
#### 1. What is not working as documented?

When trying to transcode video files using the CLI command `photoprism convert` QuickTime videos get skipped.

#### 2. How can we reproduce it?

1. Download [this](https://dl.photoprism.app/samples/QuickTime/MVI_1724.MOV) sample
2. Place it in Originals folder
3. Index it through the GUI
4. Run `photoprism convert` in terminal

#### 3. What behavior do you expect?

The video should get transcoded, but instead it is skipped.

#### 4. What could be the cause of your problem?

Maybe the CLI command is not configured properly?

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

![Screenshot from 2023-07-07 12-21-23](https://github.com/photoprism/photoprism/assets/49582442/70edb626-4e0a-4820-b558-ba703d028a67)

After the command is finished, I go to the gallery and open the video. It then starts transcoding.
![Screenshot from 2023-07-07 12-21-57](https://github.com/photoprism/photoprism/assets/49582442/6b7a1fbe-49c0-4f61-9d75-d7f7a9548c5a)

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: 230625-17242fb07-Linux-AMD64-Plus

(b) Database Type & Version: MariaDB 11.0.2

(c) Operating System Types & Versions: Unraid OS 6.12.2

(d) Browser Types & Versions: Firefox 115.0

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: Intel Core i3-7100

(b) Physical Memory & Swap Space in GB: 16GB

(c) Storage Type: HDD

**Comment by lastzero** [comment]
@mario-g98 @theresagresch As it turned out, the `photoprism convert` command only checked if the video codec is AVC, without also checking if the container is MP4 or has another format like MOV (QuickTime).

Transcoding should not be skipped because some browsers cannot play certain QuickTime AVC videos. My changes improve format checking so that the conversion command no longer skips QuickTime files. An updated [development preview](https://docs.photoprism.app/getting-started/updates/#development-preview) will be available for testing soon!

**Comment by lastzero** [comment]
Release Notes haven been updated: https://docs.photoprism.app/release-notes/#development-preview
