### ISSUE TITLE
Support for complex/composite keywords

### ISSUE THREAD

**Issue by maiatobi** [photoprism/photoprism#3629]
### What does not work as expected?
Pictures that pre-processed by other software (ie digikam, ligthroom, etc) most likely will include keywords/tags/labels.
This keywords/tags/labels are imported into photoprism but it seems spaces are used as a separator so only individual words are keywords.

This is explained here:
[iptc:keywords can't have spaces in them. #2344](https://github.com/photoprism/photoprism/discussions/2344)

I think the scope of the explained requirement is too complex for what is actually needed:

All keywords are stored in the keyword table. What is the difference in storing a composite keyword that include one or more spaces?.

I made a test and inserted a keyword with value "KEY_A KEY_B" (without the quotations) in the keyword table, and a row in the keywords_photo table to associate it with a picture.

Photoprism is capable of finding the picture if I use the KEY_A but not if I use KEY_B. 

Photoprism is also capable of finding the picture if I use "KEY_A KEY_B"  (Including the quotations) in the search box. Which means that photoprism is not using double quote or single quote to search for exactly that term, is just ignoring the double quote and using OR on each word.

Even worse using KEY_A1 will also find the picture as it seems that numbers at the end of a word are ignored (So that also mens we cannot have keywords with alphanumeric characters?).

### What behavior do you expect?

I think it should be relatively simple to parse iptc:keywords or whatever field in IPTC/XMP are analysed to include spaces and use double quotes or single quotes in the search box to indicate we want to search for that exact text. A text with a space in the middle is not different that a text without space in the middle for a database instead of using "KEYWORD%" it can search "%KEYWORD%" so it will match if the keyword is contained not only if the keyword start with the search parameter like is done now.

thanks
PS One of the anoying things of the current system is that connecting words are created as keywords (ie "de", "la", "como" in spanish).

**Comment by graciousgrey** [comment]
Thanks for sharing your use case! 

PhotoPrism aggregates keywords from many different sources, many of which contain a lot of noise that would clutter the index, e.g. automatically generated filenames like da39a3ee5e6b4b0d3255bfef95601890afd80709.jpeg or metadata automatically generated by smartphones and added to images, for example internally used IDs. 

We plan to additionally offer a [tagging system](https://github.com/photoprism/photoprism/issues/1779) that will allow you to organize your pictures with arbitrary tags - that may also include spaces, numbers and emojis - so that you have complete freedom and your tags are not mixed with automatically extracted metadata.
