### ISSUE TITLE
Browser running out of memory when opening folders with many files

### ISSUE THREAD

**Issue by chancez** [photoprism/photoprism#364]
When you open a folder in the library page, it begins loading all images from that page. It would be ideal if it only loaded a small amount, and fetched additional photos as you scrolled. I have some folders which have thousands of images and it begins to consume a lot of memory in my browser and on the server if I open it.

**Comment by lastzero** [comment]
We read directly from the filesystem, so there is no count, offset or caching we could use for infinite scrolling or pagination. This view is not meant for general searching / browsing and we didn't want to implement it at first for this exact reason.. Note that we automatically create albums from folders and you can also sort by file name in our other views. What is your specific use case? As a quick fix, we could limit the number of thumbs to 1000 or 10000 if this helps to prevent a situation where your server or browser becomes unresponsive. It will also help to ndex first, so that thumbs don't need to be rendered on the fly.

**Comment by chancez** [comment]
I just have some directories that are not organized, and it didn't seem to show any albums for my folders until after indexing was finished. It's mostly just a foot gun page right now is the main issue.

**Comment by lastzero** [comment]
Right, you'll have to wait for indexing to complete before starting to browse. We'll limit the number of thumbs and/or disable on demand rendering for the file browser. It worked when I tested it with many photos even though it was slow as expected. Our users asked for a view to see all files in a folder, so that's what we do. How many photos are in your biggest folder?

**Comment by chancez** [comment]
@lastzero thousands.

**Comment by lastzero** [comment]
Thanks for reporting this, hope we find a solution that works for everyone :)

**Comment by lastzero** [comment]
Added a limit of 500 files per folder, does this work for you?

Fix is merged to master, new Docker images available for testing soon (~1 hour).

**Comment by lastzero** [comment]
Closing this since we received no more feedback. 500 files should work, maybe more. We can always change it when there is demand.
