### ISSUE TITLE
Albums: Preview image missing when sharing album links

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#3658]
### Discussed in https://github.com/photoprism/photoprism/discussions/3452

<div type='discussions-op-text'>

<sup>Originally posted by **dror3go** June  5, 2023</sup>
I'm not sure if this is a bug, a change in config that I've missed, a change in behavior or what, but in the past when I shared a link to an album in WhatsApp/Telegram/etc. There was a preview with thumbnails of several pictures from the album.
Somewhere in the past few releases this changed, and the preview shows only the album's name.

Is that the new desired behavior?</div>

**Comment by lastzero** [comment]
There simply was a `/` too much in the generated preview image URL. Should be fixed now.

**Comment by lastzero** [comment]
Even after fixing the URL, it's still not displaying the preview image when sharing. I suspect this could be due to the redirect, which is now delayed.

**Comment by lastzero** [comment]
I overlooked that path.Join() will break the site URL, so with this change it simply prepends it to the generated path.

**Comment by lastzero** [comment]
Our development preview and [public demo](https://demo.photoprism.app/) have been updated. It looks good to me now! :+1:

**Comment by dror3go** [comment]
Looks good, thanks a lot!

**Comment by lastzero** [comment]
With these changes, album share preview images are regenerated whenever changes are made. Change detection does not yet work when an album contains a picture that is later made private without being (directly) removed from an album. Manual changes in the database also do not cause the thumbnail cache to be cleared. For this reason, the cached image now also expires after only one hour instead of one day as before.

In addition, the rendering has been improved so that previews now look like Polaroids rather than simple squares:

![preview](https://github.com/photoprism/photoprism/assets/301686/d3467717-8cff-43e6-8daa-464bf66aa587)

![flowers](https://github.com/photoprism/photoprism/assets/301686/26db5c74-a7aa-4d61-895c-d82969fdd964)
