### ISSUE TITLE
Video: Remove deprecated FFmpeg `-vsync vfr` command flag

### ISSUE THREAD

**Issue by alxjsn** [photoprism/photoprism#3659]
I have an Intel ARC380 video card which uses the DG2 platform. I tried to set up transcoding to work with it but quickly realized that it wouldn't work due to an older version of FFMpeg being used. The version installed is the latest on Ubuntu Lunar so it would require another version of Ubuntu or updated static binaries to be downloaded. I opted for the later to test this out, but realized that some changes may be required in Photoprism as well.

```
photoprism_1  | time="2023-08-21T20:48:13Z" level=warning msg="h264_vaapi: failed to transcode 2023/04/20230421_015535_E6ECC174.mov [5.484633ms]"
photoprism_1  | time="2023-08-21T20:48:13Z" level=info msg="libx264: transcoding 2023/04/20230421_015535_E6ECC174.mov to avc"
photoprism_1  | time="2023-08-21T20:48:13Z" level=debug msg="ffmpeg version 6.0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
-vsync is deprecated. Use -fps_mode
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/photoprism/originals/2023/04/20230421_015535_E6ECC174.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2023-04-21T01:55:35.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 35.000000
    com.apple.quicktime.location.ISO6709: [REDACTED]/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 8
    com.apple.quicktime.software: 16.4.1
    com.apple.quicktime.creationdate: 2023-04-20T20:55:35-0500
  Duration: 00:00:30.43, start: 0.000000, bitrate: 7854 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080, 7688 kb/s, 30.01 fps, 30 tbr, 600 tbn (default)
    Metadata:
      creation_time   : 2023-04-21T01:55:35.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : HEVC
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 96 kb/s (default)
    Metadata:
      creation_time   : 2023-04-21T01:55:35.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
    Metadata:
      creation_time   : 2023-04-21T01:55:35.000000Z
      handler_name    : Core Media Metadata
  Stream #0:3[0x4](und): Data: none (mebx / 0x7862656D), 13 kb/s (default)
    Metadata:
      creation_time   : 2023-04-21T01:55:35.000000Z
      handler_name    : Core Media Metadata
  Stream #0:4[0x5](und): Data: none (mebx / 0x7862656D), 38 kb/s (default)
    Metadata:
      creation_time   : 2023-04-21T01:55:35.000000Z
      handler_name    : Core Media Metadata
[vost#0:0/libx264 @ 0x61ca640] One of -r/-fpsmax was specified together a non-CFR -vsync/-fps_mode. This is contradictory.
"
photoprism_1  | time="2023-08-21T20:48:13Z" level=warning msg="libx264: failed to transcode 2023/04/20230421_015535_E6ECC174.mov [5.671157ms]"
photoprism_1  | time="2023-08-21T20:48:13Z" level=error msg="video: failed to transcode 2023/04/20230421_015535_E6ECC174.mov"
photoprism_1  | time="2023-08-21T20:48:13Z" level=debug msg="server: GET /api/v1/videos/a6ce0d4279b23ff98099fe80cc577407e03f90a3/3ug1kcaz/avc (206) [308.307926ms]"
```

I used the latest binary from here to test this: https://johnvansickle.com/ffmpeg/

It seems like some changes occurred between 5.x and 6.x which Photoprism has to account for so I wasn't able to fully test that transcoding works with my card. I do know that other applications that use the newer version of FFMpeg transcode successfully using my new video card.

Reference: https://github.com/intel/cartwheel-ffmpeg

**Comment by lastzero** [comment]
This is a known issue. We are currently using the FFmpeg packages that ship with the distribution, as we do not have the resources to check the static builds you referenced for important security updates and bug fixes. With the next Ubuntu update, we will likely get the new version and can adapt our code to work with it.

**If you can help us with this by providing examples and specific instructions, that would be very helpful and will speed up the process.**

**Comment by lastzero** [comment]
@alxjsn Do you know if these static builds support all the file formats we currently support, including those protected by patents? See https://www.photoprism.app/kb/file-formats for an overview of supported video file types and their extensions.

**Comment by Toadlips72** [comment]
@lastzero not sure if this will be helpful, but I am receiving the same error transcoding via ffmpeg, and it appears that the `-vsync` option (which is deprecated) cannot be used with `-r` option.

**Error in log:**
<pre>[vost#0:0/libx264 @ 0x808013200] One of -r/-fpsmax was specified together a non-CFR -vsync/-fps_mode. This is contradictory.</pre>

**Original command line:**
<pre>/usr/local/bin/ffmpeg -i /mnt/photos/originals/2023/08/IMG_1535.MOV -c:v libx264 -c:a aac -vf format=yuv420p -max_muxing_queue_size 1024 -crf 23 <b>-vsync vfr -r 30</b> -b:v 25M -f mp4 -y /mnt/photos/sidecar/2023/08/IMG_1535.MOV.avc</pre>

**The command will work if I use `-r` without the `-vsync`:**
<pre>/usr/local/bin/ffmpeg -i /mnt/photos/originals/2023/08/IMG_1535.MOV -c:v libx264 -c:a aac -vf format=yuv420p -max_muxing_queue_size 1024 -crf 23 <b>-r 30</b> -b:v 25M -f mp4 -y /mnt/photos/sidecar/2023/08/IMG_1535.MOV.avc</pre>

**It will also work if I use only `-vsync`:**
<pre>/usr/local/bin/ffmpeg -i /mnt/photos/originals/2023/08/IMG_1535.MOV -c:v libx264 -c:a aac -vf format=yuv420p -max_muxing_queue_size 1024 -crf 23 <b>-vsync vfr</b> -b:v 25M -f mp4 -y /mnt/photos/sidecar/2023/08/IMG_1535.MOV.avc</pre>

Since `-vsync` is deprecated, and `-r` apparently throws out timestamps that `-vsync` would generate, I'm guessing you'd want to go with the `-r` option and call it a day?

**Comment by lastzero** [comment]
@Toadlips72 Thanks for pointing this out! We originally added the vsync option to transcode 4K 60 FPS to 30 FPS in order to reduce the bitrate for watching the videos over an internet connection (it still needs to be fast for 4K, but only half as fast). **I'll remove the `-vsync vfr` command flag in our preview build then, so everyone can test this and give feedback before we release it in our stable version.**

**Comment by lastzero** [comment]
An updated [development preview](https://docs.photoprism.app/getting-started/updates/#development-preview) build will be available later today for you to test this!

**Comment by Toadlips72** [comment]
@lastzero Thanks for quick feedback and for looking into this!  I'm trying out photoprism for the first time, and so far I am really impressed!  I'll see if I can figure out how to install the preview build and test it out! :)  Thanks!!!!

**Comment by lastzero** [comment]
A new build is now available and the release notes have been updated: https://docs.photoprism.app/release-notes/#development-preview
