### ISSUE TITLE
Album sidebar doesn't list actual albums

### ISSUE THREAD

**Issue by nnleaf** [photoprism/photoprism#3903]
#### 1. What is not working as documented?

The dropdown menu for Album only shows 'Unsorted', not my actual albums

#### 2. How can we reproduce it?

On the sidebar, I can see the albums I've created aren't shown.

#### 3. What behavior do you expect?

The dropdown menu should show my albums

#### 4. What could be the cause of your problem?

Not sure

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

![Screenshot-2023-11-22_18-01-23](https://github.com/photoprism/photoprism/assets/32043611/cf213306-0651-4633-bd32-59505fcd6adf)

I've tried it on multiple systems, same result.

**Comment by graciousgrey** [comment]
This is the expected behavior. The "Albums" section shows all your albums, the "unsorted" section shows all photos that are not yet assigned to an album. 
If we would add an individual menu item for each album, it would quickly become very cluttered, as many users have hundreds to thousands of albums.
