### ISSUE TITLE
CDN: Improve Cross-Origin Resource Sharing (CORS) and cache headers

### ISSUE THREAD

**Issue by Daniel-H123** [photoprism/photoprism#3931]
#### 1. What is not working as documented?

I am currently facing an issue related to CORS while attempting to load fonts from a different CDN hostname, which is routed through Cloudflare. According to the documentation provided [here](https://docs.photoprism.app/getting-started/using-a-cdn/), I expect the fonts to load successfully, but it seems there is a CORS-related problem preventing their loading.

#### 2. How can we reproduce it?

1. Use a different CDN hostname routed through Cloudflare.
2. Attempt to load fonts from this CDN hostname.
3. Observe the CORS-related blockage in DevTools, preventing successful font loading.

#### 3. What behavior do you expect?

Successful loading of fonts with `Access-Control-Allow-Origin` header set to `PHOTOPRISM_SITE_URL` variable.

#### 4. What could be the cause of your problem?

`Access-Control-Allow-Origin` header not set.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

![Screenshot 2023-12-03 015829](https://github.com/photoprism/photoprism/assets/78355193/9a585d73-f527-463f-bab1-4ec460e9d837)

#### 6. Which software versions do you use?

Latest release

#### 7. On what kind of device is PhotoPrism installed?

Windows Server 2019, 32GB ram, I7 4790k

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Yes, Synology reverse proxy, but tested without and headers are not present either.

**Comment by lastzero** [comment]
@Daniel-H123 Note that the CDN config options are intended for users who run a public server and additionally want to use a CDN to serve static content such as frontend assets, thumbnails, and videos. An example of this would be our public demo at https://demo.photoprism.app/.

Cloudflare users typically use the service as a reverse proxy ("web application firewall") to make their private server publicly accessible over the internet. In this case, you don't need to configure an external CDN, which might resolve your issues?

**Comment by lastzero** [comment]
I've added a note regarding the use of Cloudflare to our docs:
- https://docs.photoprism.app/getting-started/using-a-cdn/#cloudflare

**Comment by Daniel-H123** [comment]
> @Daniel-H123 Note that the CDN config options are intended for users who run a public server and additionally want to use a CDN to serve static content such as frontend assets, thumbnails, and videos. An example of this would be our public demo at https://demo.photoprism.app/.
> 
> Cloudflare users typically use the service as a reverse proxy ("web application firewall") to make their private server publicly accessible over the internet. In this case, you don't need to configure an external CDN, which might resolve your issues?

Understandable, but using Cloudflare for the website as a whole, didn't work for me because Cloudflare limits the amount of websocket connections for free users, so it was pretty unreliable.

> I've added a note regarding the use of Cloudflare to our docs:
> 
> * https://docs.photoprism.app/getting-started/using-a-cdn/#cloudflare

While this would resolve the issue, I still see the benefits of supporting the modification of the `Access-Control-Allow-Origin` header. As you can see on [this](https://developers.cloudflare.com/fundamentals/concepts/how-cloudflare-works/#performance) website, Cloudflare also offers caching and performance optimisations, especialy for static resources. Also Photoprism doesn't need any more configurations at all for this type of use. The images load in perfectly, and the fonts will load in for sure if the headers are set correctly.

I'm very new at GO, but i've tried to help you by creating a base structure for it. It probably needs a setting in the docker enviroment, but i'll leave that up to you.

PR: #3940

**Comment by lastzero** [comment]
@Daniel-H123 You can test the changes referenced above by using the `photoprism/photoprism:test` image provided on Docker Hub. It will:

1. Ignore any configured CDN URL if it is the same as the site URL, minimizing the impact of configuration mistakes.
2. Add a `PHOTOPRISM_HTTP_CORS` config option that sets the `Access-Control-Allow-Origin` header to `*` if it is set to `"true"`, e.g. `PHOTOPRISM_HTTP_CORS: "true"`.
3. In addition, if `PHOTOPRISM_HTTP_CORS` is not set, the server automatically checks whether an Origin header is present and, if so, sets the `Access-Control-Allow-Origin` header to the same value so that Cross-Origin Resource Sharing (CORS) should also possible.

Note that 3. was implemented for testing purposes only, as it is generally not safe unless the origin is checked against a list of allowed origins - so either such a check must be added or the code must be removed again.

**Please let me know if this helps you get it working with Cloudflare and if not, what additional changes would be needed. Thank you!**

**Comment by Daniel-H123** [comment]
> @Daniel-H123 You can test the changes referenced above by using the `photoprism/photoprism:test` image provided on Docker Hub. It will:
> 
> 1. Ignore any configured CDN URL if it is the same as the site URL, minimizing the impact of configuration mistakes.
> 2. Add a `PHOTOPRISM_HTTP_CORS` config option that sets the `Access-Control-Allow-Origin` header to `*` if it is set to `"true"`, e.g. `PHOTOPRISM_HTTP_CORS: "true"`.

Thanks for your changes, however I don't think this should be the behaviour of the access-control-allow-origin header. Setting it to `*` is not safe, because that way every site can access requests to photoprism in theory.

> 3. In addition, if `PHOTOPRISM_HTTP_CORS` is not set, the server automatically checks whether an Origin header is present and, if so, sets the `Access-Control-Allow-Origin` header to the same value so that Cross-Origin Resource Sharing (CORS) should also possible.

This option is also not good as you said, because the origin header is just copied back.

In my opinion, the access-control-allow-origin header should just be the `c.SiteDomain()` as it is the only trusted domain.

**Comment by lastzero** [comment]
The **original site** domain should not need this header, because it's not a **cross site** request...
What am I getting wrong here? :thinking:

**Comment by lastzero** [comment]
@Daniel-H123 Maybe you could still test these changes for us, as it took me half a day to finish this and provide new images for you? It would be great to know if it is really this header that helps/was the problem and if `PHOTOPRISM_HTTP_CORS: "false"` also works...

As written above, 3. is **safe** if the origin is validated e.g. using the CDN-URL and SITE-URL settings. However, as I only have limited time to test this with you, I would like to have confirmation from you first before proceeding.

Thank you very much! :heart:

**Comment by lastzero** [comment]
@Daniel-H123 I have just tested the behavior with a CDN running under a different TLD. As long as the `Content-Security-Policy` header is set correctly, there were no problems, not even with websockets or videos.

**Could it be that your CDN provider needs to set different headers (and not us) or that you are using Cloudflare in a way that is not officially supported?**

**Comment by Daniel-H123** [comment]
> @Daniel-H123 I have just tested the behavior with a CDN running under a different TLD. As long as the `Content-Security-Policy` header is set correctly, there were no problems, not even with websockets or videos.
> 
> **Could it be that your CDN provider needs to set different headers (and not us) or that you are using Cloudflare in a way that is not officially supported?**

I'll come back on this. Also keep in mind that the error does not occur every time, but it was unreliable.

**Comment by lastzero** [comment]
Maybe you are using the CDN as the SITE URL and the SITE URL as the CDN? The screenshot you added above doesn't provide much information... except that Chrome has a problem that could be solved with other headers or URL settings. 

Setting the `Access-Control-Allow-Origin` header to change the default same-origin policy, which works for 99% of all sites, should really be a measure of last resort. In most cases you should set `Content-Security-Policy` instead or the URLs are incorrectly configured in the first place.

**Comment by Daniel-H123** [comment]
I've tested your code, and the solution you provided works, but it is a security risk to allow all origins by setting it to `*`.

Also setting it just to what the origin header says is also insecure, because it will always match (as you said).

I've merged your solution with my code and modified it to use the PHOTOPRISM_SITE_URL as the value for the `Access-Control-Allow-Origin` and that works as expected. See https://github.com/Daniel-H123/photoprism/commit/50b7f592535fc49f78005f029bba0c4130019415

I've tested the code, but i'll add some tests later.

**Comment by lastzero** [comment]
It is not uncommon to set this header to the origin or * if you are serving content as a CDN. Thus my question, if you are using the CDN (Cloudflare) as the primary site URL while PhotoPrism has the role of a CDN, e.g. to stream videos that are not supported by Cloudflare if you are using their free tier?

Edit: In this case, you would be exposing your communication with the API, including all passwords and access tokens, so they COULD take over your instance if they wanted to. IMHO this is a far bigger problem than the "Access-Control-Allow-Origin" header. We could instead set this header only for static content and streaming video, and not for all endpoints, so that you can use PhotoPrism as a CDN (instead of using a CDN with PhotoPrism, which is the currently supported use case).

**Comment by lastzero** [comment]
@Daniel-H123 It would shorten the time I need to fully understand and resolve the issue if you could provide us with the exact URLs (including information on which domain is used for what, e.g. which is the origin from the browser's point of view) and the complete request and response headers for different types of content (which you can see if you use the Network tab in your browser's developer console):
- https://docs.photoprism.app/getting-started/troubleshooting/logs/#__tabbed_1_2

You can find our contact details here if you don't want to share this publicly:
- https://www.photoprism.app/contact

Thank you! :)

**Comment by Daniel-H123** [comment]
> It is not uncommon to set this header to the origin or * if you are serving content as a CDN. Thus my question, if you are using the CDN (Cloudflare) as the primary site URL while PhotoPrism has the role of a CDN, e.g. to stream videos that are not supported by Cloudflare if you are using their free tier? Edit: In this case, you would be exposing your communication with the API, including all passwords and access tokens, so they COULD take over your instance if they wanted to. IMHO this is a far bigger problem than 

I use Photoprism as primary site url, and CloudFlare proxied to photoprism as cdn url. The problem with cors does not only occur when using cloudflare, but just when configuring the cdn url to another domain.

> We could instead set this header only for static content and streaming video, and not for all endpoints, so that you can use PhotoPrism as a CDN (instead of using a CDN with PhotoPrism, which is the currently supported use case).

This would solve the security risk. Maybe limiting the CDN domain to only deliver static resources is also an option, but I don't think that is worth the hassle.

Edit: I'll post some more details in a sec

**Comment by Daniel-H123** [comment]
> @Daniel-H123 It would shorten the time I need to fully understand and resolve the issue if you could provide us with the exact URLs (including information on which domain is used for what, e.g. which is the origin from the browser's point of view) and the complete request and response headers for different types of content (which you can see if you use the Network tab in your browser's developer console):
> 
> * https://docs.photoprism.app/getting-started/troubleshooting/logs/#__tabbed_1_2
> 
> You can find our contact details here if you don't want to share this publicly:
> 
> * https://www.photoprism.app/contact
> 
> Thank you! :)

Example:
App url: http://app.prsm.com:2342/

**Comment by lastzero** [comment]
I'm happy to take another look once you've provided us with the information requested above, as it's too much guesswork for me otherwise:
- https://github.com/photoprism/photoprism/issues/3931#issuecomment-1892681160

Note that using PhotoPrism as the origin site along with a CDN works flawlessly on our public demo (and all other sites we and other users run). So there's currently no reason to believe that using a CDN won't work as documented, unless there's something special about your setup that I don't know about.

**Comment by Daniel-H123** [comment]
Example

App url: http://app.prsm.com:2342/
CDN url: http://cdn.prsm.com:2342/

Without any additional configuration, chrome blocks the request of fonts from example, because it comes from another domain, thus triggering CORS protection.

**Config:**

![image](https://github.com/photoprism/photoprism/assets/78355193/ee951b8e-7a73-41f8-b0b8-ab300f8580e1)

**Default behaviour:**

![0eb95b8ba524f78ce8fc8a5e28872f8f](https://github.com/photoprism/photoprism/assets/78355193/3ebcf052-831c-47f8-b4d3-b398b6b3b2a4)

**Expected behaviour (with #3940):**

![image](https://github.com/photoprism/photoprism/assets/78355193/5e1c3e82-e1c7-406f-9709-d05b551aa2c1)

I have no idea what i'm missing if all the other sites are working fine.

Edit: The demo site also includes the `Access-Control-Allow-Origin` header in cdn requests

![9d25be6cc86717b80bf6f88bcf09e818](https://github.com/photoprism/photoprism/assets/78355193/b4096666-2160-4808-8062-f5d9e2bbe5bd)

**Comment by lastzero** [comment]
Does it work if you add a `Content-Security-Policy` header that includes the SITE URL and the CDN URL? If you are using our Community Edition, you can do this with any reverse proxy you run in front of PhotoPrism (as mentioned in our docs).

See our public demo at demo.photoprism.app for an example:
![Screenshot 2024-01-15 at 22 54 24](https://github.com/photoprism/photoprism/assets/301686/73ccbc3d-308c-4a9f-9d2d-eefef4268eca)

**Comment by lastzero** [comment]
> Edit: The demo site also includes the `Access-Control-Allow-Origin` header in cdn requests

Exactly, that's what I'm trying to say:

**Essentially all CDNs set the header this way because they exist to deliver content to OTHER websites. Why would you want to prevent this? Unless you are using a service that is not intended to be used this way...**

**Comment by Daniel-H123** [comment]
> > Edit: The demo site also includes the `Access-Control-Allow-Origin` header in cdn requests
> 
> Exactly, that's what I'm trying to say:
> 
> **Essentially all CDNs set the header this way because they exist to deliver content to OTHER websites.

Because normaly a cdn only delivers static resources **(That is not dependant on user authentication cookies).** By having the header set to `*`, other sites can technically get [your profile page](https://demo.photoprism.app/library/settings/account) or your [private images](https://demo.photoprism.app/library/private). I know this is theoretically, but if you can stop it pretty easily, why not.

Example CDN url to 'sensitive' page: https://demo-cdn.photoprism.app/library/admin/users

>  Why would you want to prevent this? Unless you are using a service that is not intended to be used this way...**

You don't want to prevent it, but only limit to the main app url that is supposed to be used to access Photoprism

Edit: On further inspection, maybe it does not matter because vue is used, but that was my reasoning for it. Are the headers added to API routes?

**Comment by lastzero** [comment]
No, this is prevented by the same origin policy. Maybe PhotoPrism could "hack" the CDN, but the CDN doesn't have access to the credentials that you'd need to access the protected API endpoints. That is, unless you try this with our PUBLIC demo, which is not protected for the obvious reason.

**Comment by Daniel-H123** [comment]
> No, this is prevented by the same origin policy. Maybe PhotoPrism could "hack" the CDN, but the CDN doesn't have access to the credentials that you'd need to access the protected API endpoints. That is, unless you try this with our PUBLIC demo, which is not protected for the obvious reason.

Then adding `*` for the header should not cause a security problem. My bad.

**Comment by lastzero** [comment]
The situation is different if you use cookies, as these MAY be configured to be readable across subdomains and COULD be read by code hosted on both of the example domains you provided, e.g.:

```
Set-Cookie: name=value; domain=prsm.com
```

This should not be something to worry about in our case, since (a) we [use a cookie-free API](https://docs.photoprism.app/developer-guide/media/thumbnails/#server-api) and (b) any proper CDN would filter out the custom and authentication headers, so they won't be passed to the origin server and protected response data won't be cached.

Based on the information provided, my assumption now is that you are using a WAF/CDN that does not set the `Access-Control-Allow-Origin` header on its own (as other CDNs would do) and instead passes on the headers returned by the origin server 1:1. As a result, the requests work if you set the `Access-Control-Allow-Origin` header in our security middleware. Is this correct?

If so, please note that a Web Application Firewall (WAF) assumes that it handles all requests and that there is no other way to reach the origin server. It works differently than a CDN running on a separate domain, with the origin site still responsible for all API requests that require authentication. A WAF should therefore not be referred to as a CDN, as this leads to high levels of confusion, especially when it comes to how headers are handled and what security it provides if not used as intended.

**Comment by lastzero** [comment]
@Daniel-H123 With the updated `photoprism/photoprism:test` image, you can use the following configuration options to set the CORS headers according to your needs:

- **--cors-origin `URL`** origin URL from which browsers are allowed to perform cross-origin requests (leave empty to disable or use * to allow all) [$PHOTOPRISM_CORS_ORIGIN]
- **--cors-headers `HEADERS`** one or more HEADERS that browsers should see when performing a cross-origin request (default: "Origin, Accept, Accept-Ranges, Content-Range") [$PHOTOPRISM_CORS_HEADERS]
- **--cors-methods `METHODS`** one or more METHODS that may be used when performing a cross-origin request (default: "GET, HEAD, OPTIONS") [$PHOTOPRISM_CORS_METHODS]

**Comment by Daniel-H123** [comment]
This works. Thanks!

**Comment by lastzero** [comment]
Based on these findings, I have put additional effort into refactoring our server endpoints:

- Static fonts and CSS files now automatically include CORS headers when a CDN is configured.
- If a `Cdn-Host` header is present (Cloudflare uses other headers), only GET, HEAD, and OPTIONS requests are allowed to reduce the impact of CDN misconfigurations.
- Our custom `X-Auth-Token` header has been added to the Vary response header where appropriate.
- The request middleware has been split into different handlers for each endpoint type (API, Static, WebDAV) to avoid adding irrelevant or inappropriate headers to the response.

@Daniel-H123 It would be great if you could test this again with the updated `photoprism/photoprism:test` image so I know if it is (still) working for you. Thank you very much!

**Comment by Daniel-H123** [comment]
> @Daniel-H123 It would be great if you could test this again with the updated `photoprism/photoprism:test` image so I know if it is (still) working for you. Thank you very much!

I've tested it with PHOTOPRISM_CORS_ORIGIN and the resources load in correctly, but i'm not sure anymore what the configuration options are now (if you even changed that).

An important thing to note is that the PHOTOPRISM_CORS_ORIGIN option needs to be the origin with port **without** trailing slash, so [protocol]://[hostname]:[port], but that is something for the docs.

**Comment by Daniel-H123** [comment]
> > @Daniel-H123 It would be great if you could test this again with the updated `photoprism/photoprism:test` image so I know if it is (still) working for you. Thank you very much!
> 
> I've tested it with PHOTOPRISM_CORS_ORIGIN and the resources load in correctly, but i'm not sure anymore what the configuration options are now (if you even changed that).
> 
> An important thing to note is that the PHOTOPRISM_CORS_ORIGIN option needs to be the origin with port **without** trailing slash, so [protocol]://[hostname]:[port], but that is something for the docs.

**Comment by lastzero** [comment]
With the very latest test image, you ideally shouldn't need any extra configuration as the CORS headers are automatically set for a specific list of static assets included with the Docker image (so they shouldn't do any harm and I currently don't see any way this could be exploited either).

If you still set the CORS Origin option, it will always be present, even for requests and assets for which it may not be needed.

On the other hand, the automatically set header value is `*` since we have users who don't have their actual site URL configured or who (for whatever reason) use multiple domains for their instance.
