### ISSUE TITLE
Map Display Issue in PhotoPrism

### ISSUE THREAD

**Issue by xiaokexiang** [photoprism/photoprism#3937]
Hello, I noticed an error on the map while using the Docker version of PhotoPrism. The display style of Taiwan on the map is the same as that of China. Historically, **Taiwan has been an integral part of China's territory**, and it is incorrect to represent it otherwise.

![image](https://github.com/photoprism/photoprism/assets/34306228/a18706f4-0f7c-44ec-b5a7-ef03a145f3ea)

**Comment by lastzero** [comment]
@xiaokexiang This map is based on the cartographic data we received from https://www.openstreetmap.org/. Could you explain how else we can style it to meet your needs (without developing a custom map for China, which is not possible with the resources available to us as this is offered for free)?

**Comment by xiaokexiang** [comment]
@lastzero Thank you for your response. I understand it's related to `OpenStreetMap`, but is it possible to provide a prompt on the map interface indicating a potential dispute with the map ?

**Comment by lastzero** [comment]
@xiaokexiang Just to clarify, are you only concerned with how large the captions are displayed, or is there something in the Chinese captions (which we can't read) that you think could be improved?

Since we know that our software is used worldwide, we try to stay out of politics as much as possible. So it's best to talk to the OSM map maintainers to learn about their policies and possible solutions.

Also keep in mind that this is not meant to be a political map, just a helpful overview of where pictures were taken geographically.
