### ISSUE TITLE
PWA controls and text fields not working correctly

### ISSUE THREAD

**Issue by matthabjan** [photoprism/photoprism#3951]
Steps to reproduce:

Install Photoprism website as PWA on Anroid Firefox.

Actual results:

The PWA opens as expected, but controls do not work (e.g. back button, entering text in a field). This works as expected when the same site is opened in the Firefox Android browser directly. The same PWA of the same site works as expected also when using Chrome for Android. So this seems to be a Firefox-specific issue.

Expected results:

In Firefox for Android, controls should work as if the website is opened in the browser directly.

Which software versions do you use?

(a) PhotoPrism Architecture & Build Number:
PhotoPrism® CE
Build 231128-f48ff16ef

(b) Database Type & Version:
MariaDB 11.1

(c) Operating System Types & Versions: Linux, Android

(d) Browser Types & Versions: Firefox 120.1.1 (Build #2015990546)

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?
None

On what kind of device is PhotoPrism installed?
Raspberry Pi 4

Do you use a Reverse Proxy, Firewall, VPN, or CDN?
None.

**Comment by lastzero** [comment]
![Screenshot_20231212_225252](https://github.com/photoprism/photoprism/assets/301686/7b9bafea-32b4-4fee-97f6-8cbe467bee4f)
![Screenshot_20231212_225319](https://github.com/photoprism/photoprism/assets/301686/3679c99d-2a32-4d51-8042-fe4ace13de42)

Seems to work for me after restarting my Android phone? Could this be a problem that must me fixed in Android or Firefox for Android rather than in our application? What could we possibly do about it?

**Comment by matthabjan** [comment]
Thank you for testing! A restart didn't help in my case unfortunately.

But I figured out it works with a different phone (Android11, different Firefox version).
After this I checked several PWA-websites and had the exact same problems there as well - should actually have tested before reporting here.

So this is definitely a Firefox/Android related problem, and the issue should be closed.
