### ISSUE TITLE
Shared link can view other albums

### ISSUE THREAD

**Issue by Bart1909** [photoprism/photoprism#400]
Uploaded two folders.
Creating shared link for folder one with ID: 2tf4kgs2x5
Created shared link for folder two with ID: 2o2k94pbvj

Opening link one in private browser session. Pictures are shown from that folder.
When clicking on "Albums" in the left corner, the overview is shown with both albums.
Then I can enter the seconds album with its pictures.

Same behavior, if I use the second link first.

**Comment by Bart1909** [comment]
If I add another album without shared link, the album is not shown.
So I can only view all shared albums with one shared link.

**Comment by lastzero** [comment]
Strange, works for me. Are you sure you didn't somehow click / load both links? Tokens will accumulate in the session store so that you'll automatically see all albums that were shared with you, not just the one you opened last.

![Screenshot 2020-07-13 at 20 30 52](https://user-images.githubusercontent.com/301686/87339990-c5329d80-c547-11ea-9fa0-04de4f55b1c0.png)

**Comment by Bart1909** [comment]
Can’t reproduce it now... very Strange. I‘m quite sure, that I used different, fresh inkognito chrome processes.
Will test this tomorrow again, I’m indexing all files at the moment

**Comment by Bart1909** [comment]
Tested it again and can't reproduce the error. Maybe it was my fault and I used the same incognito browser or something else...
