### ISSUE TITLE
Photos not visible in vary large windows

### ISSUE THREAD

**Issue by richardklose** [photoprism/photoprism#413]
If a browser window is resized above a certain size, the photo disappears, when the photo is opened.
Reproducible in Safari 13.1.2 and Chrome 84.

It looks like that this happens, as soon as the viewport has more than 1920px height, as long as the window is big enough in its width.
I assume, that has to do with `PHOTOPRISM_THUMB_SIZE`, however, If I don't want large thumbnails, I'd expect the image to stay at the maximum thumbmnail size and not try to load a bigger thumbnail, that doesn't exist.

**Comment by lastzero** [comment]
That's probably because uncached thumbnails are off by default und the max pre-rendered size is 2048x2048px. Need to add some kind of fallback mechanism, going through the thumbs path and checking what files are actually there... can't trust the settings as some users randomly delete files. Maybe it's better to limit the requested size in the frontend photo viewer instead.

If you know what you are doing, set `PHOTOPRISM_THUMB_UNCACHED` to `"true"`. This should solve the issue.

See [Memory usage spiked making photoprism unusable on RPI #291](https://github.com/photoprism/photoprism/issues/291)

**Comment by lastzero** [comment]
Did you try setting PHOTOPRISM_THUMB_SIZE_UNCACHED to PHOTOPRISM_THUMB_SIZE, so that both are the same?

**Comment by lastzero** [comment]
PHOTOPRISM_THUMB_SIZE_UNCACHED is currently set to 7680 so that the original image it not used as fallback as was requested and implemented here: [Configure thumbnail types and sizes #157](https://github.com/photoprism/photoprism/issues/157)

It's hard to find settings that work for everyone :(

**Comment by richardklose** [comment]
Setting PHOTOPRISM_THUMB_SIZE_UNCACHED to PHOTOPRISM_THUMB_SIZE to the same value works. Does this mean, for larger views, the original photo is used? This would solve it for me, as my network is fast enough to handle that. 

But when using photoprism over internet, I could think of scenarios where people might want to force the viewer to not display anything above PHOTOPRISM_THUMB_SIZE, so limiting the requested size in the frontend photo viewer sounds reasonable.

**Comment by lastzero** [comment]
Yes, the original should be used in that case... browsers typically don't fix rotation based on exif metadata. So it's not an ideal solution, besides the large file size.

Maybe we also set PHOTOPRISM_THUMB_UNCACHED to true again since we now render thumbs while indexing (was a separate step before)... users can still delete the cache directory and then run out of memory / cpu.

**Comment by lastzero** [comment]
Started a new Docker build with a fallback as discussed: https://travis-ci.org/github/photoprism/photoprism/builds/709510735

**Comment by lastzero** [comment]
Closing this, let us know when there are still issues :)
