### ISSUE TITLE
Correct thumbnails, after clicking on them the wrong photo is displayed (for some photos)

### ISSUE THREAD

**Issue by hpoperator86** [photoprism/photoprism#4187]
#### 1. What is not working as documented?

Hello dear community,

I currently have just over 28000 photos indexed. They are family photos and photos from everyday life. 

As the small preview image, all the photos are displayed correctly, but with some photos I have the problem that the correct photo is displayed, but when I click on it, a completely different photo is displayed. The strange thing is that there are also photos here that I have already opened once and everything was correct and when I opened them again, the same wrong photo was displayed. It seems as if the database here refers to a different photo. I am attaching a video here that shows the problem (In the source folder where the photos are located, all photos are fine).

https://github.com/photoprism/photoprism/assets/149537735/76492083-88a0-4b45-b262-8e0807594092

#### 2. How can we reproduce it?
unfortunately I have no idea, I'm not that technically savvy.
see video.

#### 3. What behavior do you expect?
the correct display of photos.

#### 4. What could be the cause of your problem?
I suspect the database

#### 5. Can you provide us with example files for testing, error logs, or screenshots?
yes, to a certain extent. These are family photos, so unfortunately I can't make all my pictures available

#### 6. Which software versions do you use?
(a) PhotoPrism Architecture & Build Number: AMD64, ARM64, ARMv7,...
PhotoPrism® CE Build 231128-f48ff16ef

(b) Database Type & Version: MariaDB, MySQL, SQLite,...
1:11.3.2+maria~ubu2204

(c) Operating System Types & Versions: Linux, Windows, Android,...
Linux 6.1.0-0.deb11.17-amd64 (PhotoPrism was installed in a Docker)

(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,...
Firefox (latest version)

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?
Google, Translate Plugin and uBlockOrigin Plugin

#### 7. On what kind of device is PhotoPrism installed?
Fujitsu Primergy TX1310 M1 - Server

(a) Device / Processor Type: Raspberry Pi 4, Intel Core i7-3770, AMD Ryzen 7 3800X,...
Intel(R) Xeon(R) CPU E3-1226 v3 @ 3.30GHz

(b) Physical Memory & Swap Space in GB
Physical Memory: 8GB DDR3L 1600MHz ECC (HMT41GU7BFR8A-PB)
SwapSpace: 4GB

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage,...
HDD

(d) Anything else that might be helpful to know?
I have photoprism running as a docker which was installed with a docker-compose under portainer. Here in this thread I posted the docker-compose and the stack.env:
https://github.com/photoprism/photoprism/discussions/4173

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?
**No**

**Using NGINX?**
No!

**Comment by lastzero** [comment]
If there is no way to reproduce this issue, we unfortunately cannot fix it or even confirm it as a bug:
- Something like this would usually happen if changes have been performed in the background (e.g. **updated metadata such as location or time, pictures moved to the archive, ongoing index operations,...**) or there are other inconsistencies so that the pictures you are trying to open are no longer available (at least not in the latest search results, depending on which filters and sort order you are using).
- I would recommend to also test this with another browser to see if that makes a difference, because that would indicate a potential frontend issue. Thank you very much!

**Comment by lastzero** [comment]
If the problem is that the selected pictures are no longer included in the (latest) search results, the first available picture (i.e. the one at the beginning) would be displayed. To confirm, you can also press the "Reload" button to see if the displayed results have changed, for example when sorting by "Recently Added" and an indexing process is currently taking place in the background:

![Screenshot 2024-04-16 at 19 19 00](https://github.com/photoprism/photoprism/assets/301686/c435e90f-e141-420e-aca4-0e45eb1fab52)
