### ISSUE TITLE
Metadata: Don't ignore stop words when generating titles from file names

### ISSUE THREAD

**Issue by impatman** [photoprism/photoprism#4192]
PLEASE PROCEED ONLY IF YOU ARE ABSOLUTELY SURE THAT THIS IS NOT A TECHNICAL SUPPORT INCIDENT AND/OR POSSIBLY A PROBLEM WITH SOME OTHER SOFTWARE YOU ARE USING. VISIT <https://www.photoprism.app/kb/getting-support> TO LEARN MORE ABOUT OUR SUPPORT OPTIONS. THANK YOU FOR YOUR CAREFUL CONSIDERATION!

---------------------------------------------------------------------------

#### 1. What is not working as documented?

Files are labeled incorrectly when indexed from a folder starting with the word "non".

#### 2. How can we reproduce it?

1. Create a folder in originals called "Non Commercial Pics". 
2. Upload Pictures to said folder
3. Scan for new indexes.
4. Pictures are labelled as "commercial pics" 

Number of pics in my library 6k. No changes in default settings, just installed the app yesterday.

#### 3. What behavior do you expect?

I expect the pics to be labelled as "Non Commercial Pics" 

#### 4. What could be the cause of your problem?

I have zero clue. This is a weird error. 

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

I cannot provide logs directly. The pictures are of sensitive nature. Here's the best I can do.
https://imgur.com/a/scuqS9s

#### 6. Which software versions do you use?

[PhotoPrism® CE](##REDACTED##/about)
Build [231128-f48ff16ef](https://docs.photoprism.app/release-notes/)

#### 7. On what kind of device is PhotoPrism installed?

Synology NAS - Portainer

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Not Currently

**Comment by lastzero** [comment]
"non" could be on the stop word list that we use when indexing human language in path names:
- https://github.com/photoprism/photoprism/blob/develop/pkg/txt/resources/stopwords.txt

It could also be that we need to add "non" to this list of short words:
- https://github.com/photoprism/photoprism/blob/develop/pkg/txt/shortwords.go

If you don't have too many of these folders, so that changing the title manually is not possible, I recommend that you simply change the name through the edit dialog to whatever suits you best (batch edit for changing the title of multiple pictures is planned but not available yet):
- https://docs.photoprism.app/user-guide/organize/albums/#edit-album-details

**Comment by lastzero** [comment]
@impatman Your issue should be fixed with these changes. Thanks for reporting it!
