### ISSUE TITLE
Bug: Many video files now not playing, Sidecar jpg acting as main file. Video file still there.

### ISSUE THREAD

**Issue by andrewdolphin** [photoprism/photoprism#4319]
I have several videos that for some reason now don't play through the web ui. Instead the sidecar jpg file is picked and shown. Other files in the same list work fine. On those not working the proper file is there and is shown as part of the stack but just not played. File extensions and codecs are the same as working files. You can tell from the gallery which ones this is happening to as the incorrect file size is shown (the sidecar jpg file size is shown)

Using docker version, updated to the latest seconds ago and problem persists.

**Comment by lastzero** [comment]
Please note that in order to process bug reports we need complete information on how to reproduce the issue and your runtime environment (including sample files for testing):
- https://www.photoprism.app/kb/reporting-bugs

If you are not sure yet, don't have detailed information, or need technical support, you are welcome to post your issue and ask for help in our community forums e.g. GitHub Discussions.

**Comment by graciousgrey** [comment]
I will go ahead and close this as we have received no further information. We will be happy to reopen the issue as soon as we have all the information needed to reproduce/debug the problem.
