### ISSUE TITLE
Live Photos: Add support for Samsung Motion Photos

### ISSUE THREAD

**Issue by ark-** [photoprism/photoprism#439]
Initial support for Samsung Motion Photos is now available for testing on our public demo at https://demo.photoprism.app/ and/or with the development preview build:

- https://docs.photoprism.app/release-notes/#development-preview
- https://docs.photoprism.app/getting-started/updates/#development-preview

Please do not upload any private pictures to [our demo](https://demo.photoprism.app/), as everyone can see them there. Thank you very much! 🙏

---

Support for Samsung Motion Photos could be implemented similar to Apple Live Photos:
- https://github.com/photoprism/photoprism/issues/177

The videos are stored in the exif data under the following tags:

```
EmbeddedVideoType: MotionPhoto_Data
EmbeddedVideoFile: <Binary File>
```

Where `EmbeddedVideoFile` is an MP4 file with its own exif data and is of type `video/mp4`. Version MP4 v2 [ISO 14496-14], compressor avc1.

I'm sure `EmbeddedVideoType` could be something other than `MotionPhoto_Data` for other Android phone manufacturers as I imagine "MotionPhoto" is a trademark name. Unfortunately I do not know the details of the other devices but some research could make this improvement cover other manufacturer's phones too.

I found discussion and exiftool commands to extract this information here: https://forum.xda-developers.com/android/software/samsung-motion-photo-extractor-t3339997

Example commands:

```
exiftool -EmbeddedVideoFile -b -w _MotionPhoto.mp4 *.jpg

exiftool -trailer:all= -if "$EmbeddedVideoType eq 'MotionPhoto_Data'" *.jpg
```

**Comment by lastzero** [comment]
Samsung embeds video files in JPEGs, is that correct?

Extracting makes sense if this is a common file type and Samsung still uses it... seems to be a hack on the first sight, so I wouldn't be surprised if they start(ed) using a different solution like Apple e.g. storing multiple files.

As a workaround, you can probably write a script to "manually" extract videos before indexing (or maybe you already did so)?

**Comment by lastzero** [comment]
Anyhow, it would be good to get example files for testing! If we don't have time now, then maybe later.

**Comment by ark-** [comment]
Hmmm, the script would be useful for a one time import but if I'm auto uploading from my phone that's not ideal. BUT it's a workable solution. I may do this to see how it looks in the UI.

Let me ask around some people I know with newer Samsung phones and get sample photos from them. Also if others realise they could use this feature maybe some thumbs up on this suggestion would help show a need.

I agree that if this format is only used for just the one phone generation it's definitely a low priority. I'll update my top post with a sample image in a few days, I don't have any to hand right now.

**Comment by libeanim** [comment]
@lastzero Here an [example picture](https://user-images.githubusercontent.com/1412303/92759077-a3ab3200-f38f-11ea-898c-8bf633cc9a20.jpg).
Not sure if Samsung considers this a hack, as they seem to store the motion photo in the metadata for 2+ years now. (The example picture was taken with a Galaxy S10 and I have pics from an S8 where it is stored in the same way.)

I'd suggest, instead of extracting and storing the video at import, I'd rather read it from the metadata every time when it's needed. Don't think that has a big performance issue as it will be loaded through the image anyway. And I guess it makes a big difference in terms of storage space needed if the video is in metadata and on disc simultaneously. (And ideally, we don't want to delete it from the metadata automatically which would also alter the file hash of the original picture).

Metadata:
```
ExifTool Version Number         : 11.88
File Name                       : 20200423_183341.jpg
Directory                       : .
File Size                       : 6.9 MB
File Modification Date/Time     : 2020:04:23 19:33:44+02:00
File Access Date/Time           : 2020:09:10 17:55:35+02:00
File Inode Change Date/Time     : 2020:06:27 13:12:34+02:00
File Permissions                : rw-rw-r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Little-endian (Intel, II)
Make                            : samsung
Camera Model Name               : SM-G973F
Orientation                     : Horizontal (normal)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Software                        : G973FXXU4CTC9
Modify Date                     : 2020:04:23 18:33:41
Y Cb Cr Positioning             : Centered
Exposure Time                   : 1/1320
F Number                        : 2.4
Exposure Program                : Program AE
ISO                             : 50
Exif Version                    : 0220
Date/Time Original              : 2020:04:23 18:33:41
Create Date                     : 2020:04:23 18:33:41
Shutter Speed Value             : 1
Aperture Value                  : 2.4
Brightness Value                : 22.58
Exposure Compensation           : 0
Max Aperture Value              : 2.4
Metering Mode                   : Center-weighted average
Flash                           : No Flash
Focal Length                    : 4.3 mm
Color Space                     : sRGB
Exif Image Width                : 4032
Exif Image Height               : 3024
Exposure Mode                   : Auto
White Balance                   : Auto
Digital Zoom Ratio              : 1
Focal Length In 35mm Format     : 26 mm
Scene Capture Type              : Standard
Image Unique ID                 : L12XLLD01VM
GPS Latitude Ref                : North
GPS Longitude Ref               : West
Compression                     : JPEG (old-style)
Thumbnail Offset                : 888
Thumbnail Length                : 50555
XMP Toolkit                     : Adobe XMP Core 5.1.0-jc003
Micro Video                     : 1
Micro Video Version             : 1
Micro Video Offset              : 4535831
Micro Video Presentation Timestamp Us: -1
Image Width                     : 4032
Image Height                    : 3024
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Time Stamp                      : 2020:04:23 19:33:41+02:00
Embedded Video Type             : MotionPhoto_Data
Embedded Video File             : (Binary data 4535775 bytes, use -b option to extract)
Aperture                        : 2.4
Image Size                      : 4032x3024
Megapixels                      : 12.2
Scale Factor To 35 mm Equivalent: 6.0
Shutter Speed                   : 1/1320
Thumbnail Image                 : (Binary data 50555 bytes, use -b option to extract)
GPS Latitude                    : 51 deg 30' 17.94" N
GPS Longitude                   : 0 deg 4' 43.45" W
Circle Of Confusion             : 0.005 mm
Field Of View                   : 69.4 deg
Focal Length                    : 4.3 mm (35 mm equivalent: 26.0 mm)
GPS Position                    : 51 deg 30' 17.94" N, 0 deg 4' 43.45" W
Hyperfocal Distance             : 1.56 m
Light Value                     : 13.9

```

**Comment by lastzero** [comment]
Thanks for sharing an example! I was able to extract the embedded MP4 / AVC1 video using the following command:

```
exiftool -b -EmbeddedVideoFile samsung-motion.jpg > samsung-motion.mp4
```

After running Exiftool to [generate JSON sidecar files](https://docs.photoprism.org/getting-started/faq/#what-are-sidecar-files-and-where-do-i-find-them), we may extract the video file next if `EmbeddedVideoFile` exists:

```
  "TimeStamp": "2020:04:23 19:33:41+02:00",
  "EmbeddedVideoType": "MotionPhoto_Data",
  "EmbeddedVideoFile": "(Binary data 4535775 bytes, use -b option to extract)",
  "Aperture": 2.4,
  "ImageSize": "4032x3024",
```

Extracting it on the fly, every time the user hovers over a motion photo, doesn't seem to be a great solution in terms of complexity, disk I/O, and performance... although it would save disk storage in favor of reducing CPU / RAM usage & better performance.

Most browsers won't be able to play the original motion photo directly, right? It is ~50% larger than just the video, so a significant difference. Especially for mobile users who pay for traffic.

PhotoPrism also needs the actual video file for extracting & indexing properties like width, height & duration. Note that video (1440x1080) and photo resolution (4032x3024) are not identical. Rotation might also differ.

How many motion photos do users typically have? Is this more like an exception or a default, so that storage becomes a real issue?

**Comment by libeanim** [comment]
Ace, glad it worked!

Hmm yea, I guess the only way where it makes sense to leave it as one file is if the video can be extracted in the browser (as the browser would download the entire file anyway). Didn't get to testing if it works but I do see that it is probably a more hacky way of doing it and probably not the best solution...

Ideally, we want to do it in a way that is compatible with the Apple Live Photo integration and also get the correct metadata from the video (like resolution). So I guess you are right and extracting it might be the best option after all.

Usually, the motion photo setting is activated once in the camera and then stays active, so all pictures will be motion photos from then onwards. I assume not many users activate/deactivate it on a photo-by-photo basis.

Maybe having two options in the settings would do the trick?
- [ ] Extract Motion Photo at import
- [ ] Auto-delete Motion Photo video embedding after extraction

**Comment by lastzero** [comment]
We avoid modifying originals for now, see [FAQ](https://docs.photoprism.org/user-guide/faq/#why-do-some-pictures-have-an-odd-date-like-01011980).

When deciding for a strategy, keep in mind that it should also work on a Raspberry Pi without causing the server to become unresponsive. Happens easily:

 - [Memory usage spiked making photoprism unusable on RPI #291](https://github.com/photoprism/photoprism/issues/291)
- [Photoprism maxing out swap space, making system unresponsive. #294](https://github.com/photoprism/photoprism/issues/294)

Users with existing photo collections typically index directly and don't use import as they want to keep file and folder names. The extracted video can be stored outside the originals folder in the storage / sidecar folder, similar to generated JSON and JPEG sidecar files.

**Comment by CraftJJGamer308** [comment]
Hello, I am just wandering if there's a way to make a motion photo from a photo and a video with `exiftool`. So it's the other way around. I'd love to hear from you...

**Comment by alex-phillips** [comment]
Not sure if a separate issue should be open, but would love to see support for Google Motion photos. These have been in the pixel phones for quite a while now. They also embed an MP4 inside of the JPEG image.

**Comment by lastzero** [comment]
Sure, once we're done with high priority issues on our roadmap :)

**Comment by graciousgrey** [comment]
@alex-phillips could you send us example google motion files to hello@photoprism.app? :)

**Comment by alex-phillips** [comment]
@graciousgrey Sent. I've included a photo from a Pixel 2 as well as a Pixel 4a as I'm not sure if they are handled the same. I found that this python script works on splitting out the mp4s from the Pixel 2 photos, but doesn't work on the 4a photos: https://github.com/ViRb3/google-camera-motion-photo-splitter/blob/master/splitter.py

GoMoPho seems to work on 4a: https://github.com/cliveontoast/GoMoPho

**Comment by lastzero** [comment]
Thanks! Not sure when I'll get to this as we need to make progress with multi-user support first. Doing our best :)

**Comment by alex-phillips** [comment]
Not a problem! Love the app, you guys are doing great work. Appreciate it all!

**Comment by Fylax** [comment]
@alex-phillips Google Camera deals with Live Photos differently from Samsung.
I have opened a more detailed Issue here: #1739

**Comment by mholt** [comment]
FYI these can be a little tricky to parse. The EXIF Go library I was using expected metadata to be near the beginning, but the sample Samsung image provided by @tribut [over here](https://github.com/photoprism/photoprism/issues/1739#issuecomment-1216457652) has about a 1 MB `mdat` box before metadata. I [submitted a patch](https://github.com/cozy/goexif2/pull/2) here but it can buffer up to 5 MB in memory now, instead of 64 KB, so that it can get past the early `mdat`. (Hope that is helpful.)

**Comment by lastzero** [comment]
Thank you!

**Comment by lastzero** [comment]
We've merged @gokcedilek's pull request today so everyone can test it with our development preview build:
https://docs.photoprism.app/release-notes/#development-preview

There seems to be one last issue for which we will need to find a solution:

- It looks like the video file extension is automatically determined based on the mimetype, which is not known until after the file is extracted. So it's impossible to check if the file already exists?
- This could lead to a big overhead when indexing Samsung Motion Photos, because extracting the binary data takes time.
- Also, you could inject file types other than videos into the library this way, like malicious executables that someone might click (or that a vulnerable virus scanner might scan, they all have bugs).

Edit: IMHO, it should be safe to assume that the extracted file is an MP4 container, containing either an AVC or HVC video. So it would probably be sufficient to check if there is already an ".mp4" sidecar file, and only if not, extract the embedded video file as ".mp4". To be extra safe, we could additionally check if the original file was created by a Samsung device (or another supported vendor using the same mechanism and format, e.g. Google).

**Comment by lastzero** [comment]
Our public demo at https://demo.photoprism.app/ has been updated so that you can test your Samsung Motion Photos there as well. Please do not upload private pictures for this, as everyone can see them. Thank you very much! 🙏

**Comment by Radiokot** [comment]
Live photos are magic ✨ Processing of Samsung JPEGs works flawlessly on the demo. Many thanks to the contributors and reviewers!
The enhanced live photo viewer is coming soon to the Android gallery.

https://github.com/photoprism/photoprism/assets/5675681/f0835c66-2477-414d-a1ac-9eb32ad5634d

**Comment by mholt** [comment]
@Radiokot That's neat! How does Photoprism know when to blend the motion part into the still photo? Is there a frame number or microseconds in the EXIF data or something?

**Comment by Radiokot** [comment]
@mholt the Android implementation shown on the video assumes that the still image is the last frame, which seems to be true for Samsung live photos. As for short videos which are treated by PhotoPrism as live photos and have the still image captured from the first frame – they will remain displayed in a loop.

**Comment by dave-hpe** [comment]
This doesn't seem to work for Google photos from Pixel phones.

**Comment by Fylax** [comment]
@dave-hpe This issue addresses Samsung Motion Photos only.
Google Camera Live Photos are discussed in issue #1739

**Comment by Radiokot** [comment]
@lastzero maybe add some live photos to the default demo content? You can use photos of my cat and bicycle, which I manually upload every day.

**Comment by lastzero** [comment]
@Radiokot We'll be happy to add one of your cat pictures to https://dl.photoprism.app/qa/plus/, so it's included in our demo! Could you please send the originals to [samples@photoprism.app](mailto:samples@photoprism.app) for this? Seems like the demo restarted, so I can't download them from there...

**Comment by lastzero** [comment]
My latest commit adds support for direct streaming of videos embedded in JPEG images. To make this possible, we've added native support for the ISO base media file format on which MP4, QuickTime (MOV), and HEIC are based.

### HEIC Files

In order to play Samsung HEIC Motion Photos, some more changes had to be implemented, as it is based on the same standard as the videos and therefore the HEIC at the beginning has to be ignored to find the MP4 video at the end of the file. This should also be working now.

### Related Information

- https://github.com/photoprism/photoprism/blob/develop/pkg/live/README.md
- https://github.com/photoprism/photoprism/blob/develop/pkg/video/README.md
