### ISSUE TITLE
[Bug] docker-compose error

### ISSUE THREAD

**Issue by zero77** [photoprism/photoprism#4428]
#### 1. What is not working as documented?
When running `sudo docker-compose up -d` it should start Photoprism but it displays the below error instead.

#### 2. How can we reproduce it?

1. wget https://dl.photoprism.app/docker/docker-compose.yml
2. sudo docker-compose up -

#### 3. What behavior do you expect?

Photoprism should start

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

https://pastebin.com/raw/pA6wbBtq

#### 6. Which software versions do you use?
OS: Debian 12

docker-buildx-plugin      0.16.1-1~debian.12~bookworm   amd64
docker-ce                 5:27.0.3-1~debian.11~bullseye amd64
docker-compose            1.29.2-3
docker-compose-plugin     2.29.1-1~debian.12~bookworm   amd64
docker.io                 20.10.24+dfsg1-1+b3           amd64
python3-docker            5.0.3-1
python3-dockerpty         0.4.1-4    

#### 7. On what kind of device is PhotoPrism installed?

Debian 12  amd64 VM

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

No

**Comment by lastzero** [comment]
Kindly note that we are unable to provide support for setting up home servers within the scope of our free community support. However, it looks like you are still using the outdated Python-based `docker-compose` command instead of `docker compose` (without the dash).

For general help with setting up Docker and Docker Compose, see our Getting Started guide:
- https://docs.photoprism.app/getting-started/troubleshooting/docker/#installation
