### ISSUE TITLE
Error in reverse geocoding

### ISSUE THREAD

**Issue by calucido** [photoprism/photoprism#444]
Photoprism Version: 200729-65c57f5-Linux-x86_64 

I keep getting the error "photo: record not found (estimate place)", and the location section on the photos list says "unknown". I re-indexed a couple photos and the expected locations appeared. It sounds to me like the place names were overlooked in a database migration. Should I just reindex and call it a day? Also: if I entered in metadata that was not present in the original image file or sidecar, will I lose that data when I reindex?

**Comment by lastzero** [comment]
Metadata that was manually changed won't the modified by the indexer.

Place estimates will only happen, if a photo has no own coordinates so that the place of a nearby photo will be used.

**Comment by lastzero** [comment]
Do you still have issues? If you have an old database, it's possible your database schema is outdated and can not automatically be migrated (e.g. when a column type changed to prevent data loss), see #450. You may try to only delete locations and places so that albums are not affected. Deleted tables will be re-created after a restart (you'll also have to re-index your photos to get the latest location data from our geolocation service).

**Comment by calucido** [comment]
I'm pretty sure it's just the old database. I'll close the issue and reopen if I notice it happening with new photos.
