### ISSUE TITLE
Incorrect location information for Nusfjord, Lofoten

### ISSUE THREAD

**Issue by kvalev** [photoprism/photoprism#4468]
__Default template is not really applicable__

A lot of locations in the village of Nusfjord get resolved to the incorrect city.

For example this [S2 cell](https://places.photoprism.app/v1/location/45de142d658c) gets resolved to the city of Ramberg, even tho the location is right in the middle of Nusfjord - https://maps.app.goo.gl/o8bDydoSLWrzNXAX8

I have observed the same problem with a bunch of other locations in or around Nusfjord.

**Comment by graciousgrey** [comment]
Thank you for reporting!

The data we use is based on openstreetmap:

https://nominatim.openstreetmap.org/reverse?lat=68.03533&lon=13.349557&format=jsonv2&accept-language=en&zoom=18

It shows village:Ramberg. If this is wrong you might want to report this to the OSM team. 

Interestingly, the address on Google Maps also shows Ramberg as the city rather than Nusfjord.

**Comment by lastzero** [comment]
I'll move ahead an close this as we haven't receive any additional feedback on this.
