### ISSUE TITLE
Download: Select Files and Formats and configure defaults

### ISSUE THREAD

**Issue by RAYs3T** [photoprism/photoprism#449]
## Download of multiple files
So right now whenever you download a single picture, it will download all the files assosiated with this specific one.
This leads to the behavior of downloading a raw+jpeg when you click on the download button.
In firefox for example this gives you two pop-ups to save the file.

In the most situations you only need one type of image. You either want the raw to edit the picture or just the version displayed for whatever.

## How about a dropdown?
What about adding a little drop down menu at the side of the button, where you can select what exact file you wish to download?
![image](https://user-images.githubusercontent.com/16596807/89622365-3b01fe80-d893-11ea-82e3-fe4da2504c4c.png)

## Make the default file type to download an option (later)
This also has great potential to be an option where the user could set its prefered download file type.
Tho I would NOT include this into this issue / PR. That might be something for later.

@lastzero If you're ok with that I would do the changes and throw it in a PR?

**Comment by lastzero** [comment]
Sorry for the wait! You are right, need to improve this. Selecting a smaller (resampled) size should be possible as well. 

Adding a download dialog so that users may select specific file type(s) and size(s) seems necessary. However, this might complicate PhotoPrism for less experienced users as they'll feel unsure what to select.

**Comment by MrRaph** [comment]
It's the only feature missing in PhotoPrism that lead me to find another software... :(

**Comment by graciousgrey** [comment]
Good to know that this feature is important for some users. In the future we plan to have something like a public roadmap/feature voting, so that we gain insights which features are most wanted :)

**Comment by shoeper** [comment]
> Sorry for the wait! You are right, need to improve this. Selecting a smaller (resampled) size should be possible as well.
> 
> Adding a download dialog so that users may select specific file type(s) and size(s) seems necessary. However, this might complicate PhotoPrism for less experienced users as they'll feel unsure what to select.

Maybe the proposed dropdown could contain very few carefully selected options (depending on object type and available formats) and for more there is an `advanced` option.

Another option could be to allow adding additional options in the user or system settings.

Too many options would also slow usage down for advanced users and many average users are even overwhelmed by any options. Probably it would be even better to have one default when clicking download without any further options. E.g. jpeg for images, gif (or mp4?) for moving pictures, mp4 for live pictures, mp4 for videos. Just click download and photoprism provides a good option.

**Comment by lastzero** [comment]
In a first step, downloads have been refactored:
- When **clicking download in the photo viewer or context menu in search results**, this will download all media files without sidecar files using their current file name by default. The file name schema can be configured in `config/settings.yml` - you may choose to let PhotoPrism generate a file name based on the photo title or use the original name (before importing and renaming).
- In addition you can download **single files** in the photo edit dialog > Files tab.
- When downloading **albums**, RAWs and sidecar files will be excluded. In addition, files will be named using their taken date and the photo title so that they can viewed in the right order - even without special software that reads their metadata.

**Comment by ministryofsillywalks** [comment]
Just ran into this limitation. I made a big selection of photos from the last year that I wanted to make into a calendar.  Mix of unedited raws and jpegs.
When I went to download the album I just got the jpeg files and the raws converted to jpegs (which of course were quite off in colour balance)
Now I have to manually download all the raw files so that I can edit them for the printing.
So yeah having the option to download the highest quality or "originals" from an album would be awesome!

**Comment by lastzero** [comment]
Use the regular search with the `album:name` filter, select all items with long / shift click, and then download using the button in the context menu (bottom right):

https://demo.photoprism.org/browse?view=cards&q=album%3Acalifornia

We'll add yet another config option / select dialog for this in a future release.

**Comment by lastzero** [comment]
![download-settings](https://user-images.githubusercontent.com/301686/224490802-1b83431e-5a56-40e4-a5e2-bc040fda7b8b.png)

**Comment by lastzero** [comment]
I've started a new preview build for testing. It should be available within the next hour!

**Comment by lastzero** [comment]
Moved the download settings to the bottom so the map settings don't lose visibility:

![download-settings](https://user-images.githubusercontent.com/301686/224499748-9626b5b4-d3da-46f7-91b6-ff8305e24a42.png)

**Comment by DrDonoso** [comment]
Hello @lastzero, 

What do you think about a feature that allows which default file extension when downloading?
When I upload a photo with photosync into a folder, it uploads the **.HEIC** and **.MOV** for the live photos (make sense to me), so Photoprism is converting it into **.HEIC.jpg** and **.MOV.jpg** which is really great (_but could be really great to disable transformation .MOV->.jpg_). But then with the existant options it is only possible to download:
- .HEIC, .MOV, .HEIC.jpg, .MOV.jpg (_when unselecting everything_)
- .HEIC, .MOV (_when selecting Originals option_)

It will add a lot of value when using a PWA on an Android Phone (also from other computers) you could download the jpg without going into Edit->Files->Selecting the file->Download which is a bit overwhelming.

I highly appreciate your effort 🥇 

Thanks!

**Comment by lastzero** [comment]
@DrDonoso That would probably mean that you would have to treat images and videos differently. Did I understand correctly that you always want to download the original video file, but the JPEG version of images? Or would you prefer to always download (web) compatible formats, i.e. AVC for videos and JPEG for images?

Edit: Note that if you always want to download AVC-encoded videos, they may need to be transcoded first, which takes time and therefore delays the download.

**Comment by WitchDoctor-Actual** [comment]
i think there should be a download jpg or png option with multiple selected so you can easily use them for uploading to a blog or other site that doesn't allow heic.

**Comment by mordka** [comment]
As a user I would like to specify file types to download so that I can quickly download only images.

**Comment by lastzero** [comment]
@mordka You can change the types of files that are downloaded under Settings > General > Download:

![download-settings](https://github.com/user-attachments/assets/70b24dac-a428-490d-9cf0-0aeb6f22e738)

However, I believe there is currently no way to specify that you always want a JPEG file, for example, especially since videos, live photos and animations cannot be converted to JPEG. Other types, such as PNG and vector graphics, may only be available as PNG because the transparency would be lost if converted to JPEG.
