### ISSUE TITLE
Folder structure after import

### ISSUE THREAD

**Issue by corgan2222** [photoprism/photoprism#455]
Hello

im also comming from Photostation on a Synology and have changed to Unraid running photoprism in docker. 
I really like the photoprism look and have tryed to import some Folders.

But after a folder import (given the originals folder) photoprism dont show me the Folder Structure as it is under "albums -> folder".
All subfolders are shown on the first layer.

On Filesystem:
- Dir
  - subdir1
  - subdir2

in photoprism

- Dir
- subdir1
- subdir2

I have found the original strucure under "Library - Original" but without any Thumbnails on the Folder.

So the question is, ether how to show the tree correct under Albums, or display the Folder Thumbs under Library?

**Comment by lastzero** [comment]
We don't support nested structures (except in Library > Originals) for a number of reasons. First, there are many tools (like Windows Explorer or Finder) that already browse folders in such a way.

Second, the same album could exist multiple times so that you always need to provide the full path to know which one you really mean. Selecting albums from a tree is also not very user friendly on mobile devices. Instead you can set a category for each album. In general, it's difficult to browse deeply nested trees.

Personal photo albums typically can be sorted by time. It's different in enterprise content management, where you might need trees for different products or teams, so that responsibilities are very clear.

Previews should be visible if you browse known file types in Library > Originals:

<img width="818" alt="Screenshot 2020-08-12 at 02 14 21" src="https://user-images.githubusercontent.com/301686/89961304-92142480-dc41-11ea-92a7-5d2d522b1f08.png">

**Comment by corgan2222** [comment]
Thats really really sad to hear. I respect and understand your reasons, but then i cant use it.
Professional Photographer allready must have a nested structure with thousand of folders and millions of pictures. It would take days to set a category for each album. :/

**Comment by lastzero** [comment]
We might do a special release for professional users and enterprise customers later. You can store photos in any folder structure, but we don't think fixed hierarchical trees should be at the heart of our application. Most users probably don't have their files properly sorted yet and want to explore them in multiple dimensions.

**Comment by corgan2222** [comment]
This would be awesome. I understand your point, that the casual user dont have some kind of sorted structure. 
I dont know your code, but why not give the user the choise to choose how the Albums are displayed. It could maybe a manuall switch or a hard to find settings option.  If im loosing the possibility to have a album in different categorys, i would go with it.

Dont get me wrong. Im not crying for code changes only for my needs. Im just looking for a solution that can replace the old Photostation App on my Synology NAS, wich has so many things i dont like.

Maybe i need a complete different solution for my needs. :)

**Comment by lastzero** [comment]
You found the file browser in Library > Originals, right?

If you only use trees, is there not a single photo that should be part of two different albums? For example, I might have many photos that are both in Black & White and in Cats at the same time.

The UX problem with trees is also that it creates namespaces, so the album Berlin might exist 20 times. All our album selectors, eg when uploading, would instantly become useless and must be replaced with a complex tree browser that shows the context. Also difficult to use on a mobile phone.

**Comment by LMSSonos** [comment]
@ corgan2222 not sure if you tested originals now, but you should see all previews in the current version (at least I see them)

**Comment by lastzero** [comment]
Added trees to our FAQ: https://docs.photoprism.org/user-guide/faq/

**Comment by bernsel** [comment]
I do think that many hobby users organize their images in a tree structure these days. When users take thousands of images on their smartphones, and the smartphone's memory gets full, they save them down to their computer hard drive. All  the people I know then at least organize their images in a unique folder by year ("2017", "2018", "2019" etcetera), but most also organize further by month as subfolders, such as "2019-01", "2019-02" etcetera. The reason is that if you keep tens of thousands of images in one folder (say one full year), it gets very slow to scroll. So people do want to keep folders and images manageable by size. Many also go even further, and for example create a folder named "2019-02 Wedding", as a sub-folder to the "2019" folder. 

I second the opinion that navigating by folder structure would be very valuable, just like you can in say digiKam.

**Comment by alexislefebvre** [comment]
@bernsel If you have directories, use [index](https://docs.photoprism.org/user-guide/library/import-vs-index/#index) and you'll be able to browse by folders: https://demo.photoprism.org/library/files

**Comment by bernsel** [comment]
It is great that it's possible to can navigate the images by folder from the Library -> Originals (the index), but from that starting point, it is not possible to View the images one by one and flick through them, or to initiate a slideshow.
As an example: let's say I want to navigate into folder "2019" -> "2019-02 Wedding" and then start viewing these images. I click on one image, but instead of getting a full image view, I get image details. If I click on the image again from the details view, I do get a full view of the image, but I cannot click left and right to see the next or previous image.

**Comment by lastzero** [comment]
True, because these are files and not photos. There may be duplicates, sidecar files, the same photo in different formats,... It's probably best to use a regular file manager to simply view all files (incl duplicates, other file formats, etc) by folder.

This view shows photos by (primary) folder: https://demo.photoprism.org/folders

**Comment by aCuria** [comment]
I am a casual home user, and I have spent a fair amount of time trying to get photoprism to work. So far while the performance has been good...

The usability of the interface is terrible due to being unable to use the folder structure to do simple tasks.

I have 20 years of photos with the following folder structure below.

The "selected" folder is necessary because your mom / wife / so is gonna tell you they dont like how they look in this or that photo, so a copy whatever is deemed kosher is chucked into a "Selected" Folder, and the "Selected" photos are then edited if deemed necessary, which results in an "edited" folder

Now, when its time to share / show off the photos, the "Folder" view is useless because theres a billion "100MSDCF " folders and "selected" folders, and even if you find the corrected "selected" folder, I wont know if theres a "edited" folder within, which I would rather show!

So clearly the solution should be to navigate to Library / Originals / yyyy-mm-dd <Name> Birthday / Selected / Edited, but when you get there I can neither 

- Share said folder
- Start a slideshow
- Play a video
- Do anything at all really



yyyy-mm-dd <Name> Birthday
>100MSDCF // The Originals
> Selected
>> Edited (sometimes have this)
> Raw (rare to have this)
yyyy-mm-dd <Name> Birthday
>102MSDCF // The Originals
> Selected
yyyy-mm-dd Zoo
>101MSDCF // The Originals
> Selected
yyyy-mm-dd <Country> Holiday
>104MSDCF // The Originals
> Selected
yyyy-mm-dd <Name> Christmas
>125MSDCF // The Originals
> Selected

**Comment by lastzero** [comment]
It's a somewhat special work flow. You're right in that we didn't have this in mind mind when developing the UI. It's important to understand that PhotoPrism operates on photos / videos, eg when sharing. Multiple files and multiple folders may belong to a single photo, for example duplicates, edited versions and sidecar files. Sharing files in folders breaks this logic. You can however easily create albums from folders in the file browser. This of course doesn't fit with your work flow where you want stay in the file browser and don't leave it.

**Comment by rondadon** [comment]
Hi there!

I also am structuring Photos into different Folders/Subfolders. I also tried to find a way to put the already available folder structure into an Album. But all the pictures in the structured in Folders and subfolders by theme/date/Camera are put all on the same first layer without any structure.
Would be really nice if we could create custom structures in Albums.

Currently you can sort the pictures in an album by date but there are no visual lines/indicators or anything seperating/clustering the dates/days.

I don't know if custom Album Structures are possible but I think such lines which are seperating the pictures by dates/days would be a nice feature for a little structure in an album.

Thank you and have a nice day! :)

**Comment by lastzero** [comment]
You mean grouping the pictures by day? What if every photo was taken on a different day? Just show one photo per row or page?

**Comment by hess8** [comment]
Yeah, I just tried photoprism, and decided I couldn't use it because there's no way to organize with a tree structure.   It would be great to be able to organize by all the current cool photoprism ways AND by nested structures.

**Comment by graciousgrey** [comment]
@hess8  the originals section already shows you your nested originals folder. We have a ticket for nested albums as well https://github.com/photoprism/photoprism/issues/401.

**Comment by pakosalze** [comment]
I have read the discussion and I would not agree that common user doesn't use directories tree to organize their photos. Even my 70 years old father use this way of photos and documents organization. I had similar discussion with my friends and nobody wants to see global dashboard where hundreds of albums with family photos, travel photos, company or any other albums of photos are mixed all together. It maybe works for dashboard with dozen of albums, but it doesn't work for people who has a plenty of scanned photos from different events from their life. Everybody organize their photos in catalogued way. Human beings are not databases with queries in their minds... Despite of that for showing dozens of albums photoprism is excelent, but not for more... For more I would use Piwigo instead, which has such way of organization and presentation...

**Comment by lastzero** [comment]
We also use folders to store our files. Nobody is questioning that.

However, if you only or mainly care about folders and files, there are better tools to browse your photos - like a simple file manager. Our main focus is search and browsing your photos in multiple dimensions, in addition to just browsing your existing folder structure (see https://github.com/photoprism/photoprism/issues/1536).

Also keep in mind:
- Many apps - like the photos app on my mobile phone which millions of people use - don't support nested albums / folders
- Files that actually belong together (derived from the same original) are often stored in different folders for historic reasons or because duplicates were needed to add a photo to two albums

See https://docs.photoprism.org/user-guide/faq/:

> Except in Library > Originals and for object classification in Labels, PhotoPrism does not support hierarchically organized content for a number of reasons:
>
> First, there are many tools (including Windows Explorer and Mac OS Finder) that already browse folders in such a way.
> 
> A common UX challenge is dealing with namespaces. For example, the album "Berlin" may exist 5 times in different parts of a tree. To avoid ambiguities, simple input fields need to be replaced with a tree browser that shows the complete context. This is especially difficult on mobile screens.
>
> Personal albums can typically be browsed by time, with optional filters for more specific results. This is different in Enterprise asset management, where trees are required to manage responsibilities & permissions. We might do a special release for professional users later.
>
> While you have complete freedom with organizing your original files and folders, we don't think trees should be an integral part of our user interface. Most users won't be able to sort their memories in a strictly hierarchical way and prefer to explore them in multiple dimensions instead.

**Comment by alexislefebvre** [comment]
@pakosalze As an example of what @lastzero described, you can see the folder view on the demo: https://demo.photoprism.org/library/files

**Comment by pakosalze** [comment]
Sure, but...

I installed photoprism and there is tab on the left named "Folders" and it will be fine for me, but it doesnt represent structure of my library - it flatten it. Hovewer entering any of it photoprism allows viewing photos with simple navigation by hitting arrow key. So "Folders" doesnt represents structure in nested way, but allows viewig photos in fine and simple way.

Another mentioned way - "Library" represents structure but when I start viewing photos it started to shows photo as an icon with lot of exif information beside. Arrow key also doesn't allow to navigate between photos. So "Library" represents structure, but doesn't allow viewing photos in fine and simple way.

Becasue of that any of above isn't useful for me, and probably for many others who want to prepair its own nested collection and viewing it at any time, anywhere in simple way. Examples that photos app in mobile phones doesn't support nested albums are not good, because for example if you want not to loose your photos after holidays or party (by loosing the phone at some time) at least for me it is common that when you get back to home you at least make a copy of it to your computer or home nas. Or at least do it from time to time. People always tries to organize their photos, or at least want to do that. With at least by catalogue structure as it is very common for people who use computers these days. And as  the structure of the filesystem of our computer is not flat nor one level of nesting, we as humans are used to it.

I would use OS Finder or Windows Explorer if only they allow to present their structure via the web. But unfortunetly they doesn't :)

I have found dockerized app named "File Manager" what allows of viewing any data (with preview of photos), but it doesn't support all formats nor allow to manipulate on it.

Neverthless it is not the right way of discussion. For me the reason of using such a tools like photoprism or piwigo are to have photos in one place, organized and allowing to view it anywhere at anytime, sharing to family or friends and not having all my data in my mobile phone. I know that mobile phones have more and more storage spaces, but it costs. Also apple or google allows me to have such photo and video libraries in the cloud, but it is also not very cost effective way of storing private photos and videos apart from the fact that they usualy store photos as one big sack.

Don't get me wrong. You do a great job, but if you want to have more users, nested albums with simple way of viewing photos and sharing albums with nested permission is imho the must. If also I would be able to set up landing page it would be perfect for me :) So, keep going with your work - you do it right :). I will have my eye on photoprism, because it is very interesting project with near perfect for me UI design of web app, but not very useful because of that little, described flaws... Till now I used synology Photostation, but when synology migrated it to Photos it starts to be usless. If you will observe discussion of at least Synology users on forums, you will discover that plenty of them are looking for alternative. Why woudn't make Photoprism as the best alternative? There are many of Synology users waiting :) Hope that suddenly, after some time when Watchtower make some upgrade I will be pleasently suprised ;)

**Comment by lastzero** [comment]
That's why we have https://github.com/photoprism/photoprism/issues/1536 which I linked above.

**Comment by graciousgrey** [comment]
> So, keep going with your work - you do it right :)

Thank you :)

We totally understand that displaying the original nested folder structure  is a need for many users that's why we have #1536 

User Management and permissions are coming as well and a default landing page is also planned. (https://github.com/photoprism/photoprism/issues/577)

Feel free to follow the progress of those issues.

**Comment by fcimeson** [comment]
I agree, I think many users use sub-folders. It is a bad assumption to say otherwise.

**Comment by hess8** [comment]
I ended up installing a Lychee photo server which has nested folders.

**Comment by n6ln** [comment]
I finally got photoprism up and running and thought I was doing something wrong when my photo folder structure disappeared.  I have well over 100,000 photos in different folders. I need a structure. Who doesn't? Imagine a book without an index, with the sentences in random order. Or Home Depot without a product structure. Or finding your room in a hotel.  I could go on. This is how human beings think. Heck, aliens on another planet probably think the same way.

I was astounded. Time to spend my time on something else...

**Comment by aCuria** [comment]
"Our main focus is search and browsing your photos in multiple dimensions"

We really think that you have to make the folder structure one of those dimensions.

It is the **MOST** important dimension, as it is the dimension where the data is most likely already labeled by the user

Its crazy that labeled data cannot be displayed properly, and you are trying to use AI to generate labels automatically that will never be as good as the human-labeled ground truth

**Comment by mrmanganese** [comment]
I have my life's media sorted into north of 17,000 folders. Shall I set aside the next 3 years to re-sort into PhotoPrism's album structure? And if I need to reinstall, what then, spend another 3 years to do it again? PhotoPrism is completely unusable without respecting the presentation medium agnostic organization of the file system folder structure. Really unfortunate because it seems great in all other ways.

**Comment by aCuria** [comment]
mrmagenese is absolutely right.

The folder structure IS the ground truth metadata.

Photoprism thinks they can do better with their AI stuff, but they can’t

I have thousands of film scans, all the AI in the world can’t tell what
date the photo was taken, and therefore can’t display them correctly

**Comment by mrmanganese** [comment]
It's comically bad, using the app I have 5 or 6 items on screen at any time and I'm scrolling through seventeen thousand items looking for the right folder. I know exactly how to navigate my structure, and it's set up so there would never be more than a couple dozen items to scroll through at most. Crazy that all the organization we need is right in the file system, but for some reason every developer thinks their own parallel system is going to see tremendous use. Back in reality, nobody wants to commit a ton of time to setting up some proprietary organization system, because they don't know when your app is going to become defunct and leave them completely screwed. "Albums" are functionally useless to someone with a quarter million media files, because it's not worth the massive investment of time it would take to categorize said media into albums. The philosophy behind "one photo can appear in many albums" is irrelevant to this calculus.

**Comment by mrmanganese** [comment]
> Would the file browser in Library > Originals be enough if we show a folder preview instead of just folder icons?
> 
> If you only use trees, is there not a single photo that should be part of two different albums? For example, I might have many photos that are both in Black & White and in Cats at the same time.
> 
> The UX problem with trees is also that it creates namespaces, so the album Berlin might exist 20 times. All our album selectors, eg when uploading, would instantly become useless and must be replaced with a complex tree browser that shows the context. Also difficult to use on a mobile phone.
> 
> PS: I've developed a sharable tree solution with ACLs before for Deutsche Telekom and neither found it very user friendly, fast or easy to explain. I thought we do it different this time. Note that when you share a folder / album (A), also all its sub folders are shared. So you need to develop permission inheritance. Now, there could be another album (B) in between with different permissions (like private). That means you need to merge both to get the final permissions for the album (C) that the user is actually viewing, like `Root > A > B > C`. Would you fully understand this? Could you explain this to the average user? On top you can also add multi-user support using a tree and permission inheritance, see [CERN: ACL, ACE ... Permissions... How to handle File security?](https://espace.cern.ch/winservices-help/NICESecurityAndAntivirus/NICESecurityHowTo/Pages/ManagingACLSettingPermssion.aspx) to get an idea of the mess you might get yourself into :)
> 
> ![](https://camo.githubusercontent.com/ac3a4d524a80c76e22f580d2eb800dc6f80543ac5978952bf7e2c4da15f7f3fd/68747470733a2f2f646c2e70686f746f707269736d2e6f72672f6173736574732f73637265656e73686f74732f6d656469656e63656e7465722f66696c656d616e616765722e6a7067)

@lastzero To answer your question above, the file browser in originals is perfect. It's everything else in originals that's problematic - originals doesn't offer a true media browsing experience, where the media is blown up, videos auto play, and we can scroll or swipe to the next item in the folder. That's all it would take, really.

Also I realize "Gallery for Photo Prism" app is third party, but it exposes "folders" to the user but not "originals." So the main client most people would be using (a phone) is presently unable to consume the originals interface in any way. I can go to the web site for originals, but minor things like hitting the back button will cause the whole site to exit..

**Comment by mrmanganese** [comment]
> Also keep in mind:
> 
> * Many apps - like the photos app on my mobile phone which millions of people use - don't support nested albums / folders

The reason many people are here giving PhotoPrism a try is because those other photos apps are grossly deficient in their organization systems. Google Photos is deplorably bad. This is not a behavior to emulate; it's an opportunity to differentiate from the crowd.

**Comment by graciousgrey** [comment]
Thank you for your feedback! 

As mentioned above we do understand that a hierarchical folder view is important for some users that's why this feature is planned for the future.
