### ISSUE TITLE
RAW: RawTherapee v5.10 doesn't support Sony's latest file format

### ISSUE THREAD

**Issue by xiluJob** [photoprism/photoprism#4564]
I found out in photoprism that the version of rawtherapee  is 5.10, and I am not sure if an upgrade is needed;
I tried installing version 5.11 of rawtherapee locally, as well as rawtherapee-cli, which supports Sony raw files. 
However,I tried using apt upgrade rawtherapee directly in Docker, but returned 5.10 as the latest version, which cannot be updated directly in photoprism terminal;

I hope you can help me verify this issue, thank you very much!

**Comment by lastzero** [comment]
PhotoPrism uses the version of RawTherapee that comes with the Docker image. Since our default Docker image is based on the latest version of Ubuntu, you currently get 5.10-1build4:

- https://packages.ubuntu.com/noble/rawtherapee

RawTherapee v5.11 was released August 25, 2024. So it's pretty new. If you're lucky, you might find a pre-built .deb package that you can install in the Docker image by e.g. opening a terminal and running the necessary commands - see this script we wrote for installing Darktable:

- https://github.com/photoprism/photoprism/blob/develop/scripts/dist/install-darktable.sh

Alternatively, the AppImage they distribute might work in our Docker image (never tested this) or you can build the latest version from source:

- https://rawpedia.rawtherapee.com/Linux

Would you like us to (more explicitly) mention this on docs.photoprism.app? If so, where would you look for this information?

**Comment by xiluJob** [comment]
> PhotoPrism uses the version of RawTherapee that comes with the Docker image. Since our default Docker image is based on the latest version of Ubuntu, you currently get 5.10-1build4:
> 
> * https://packages.ubuntu.com/noble/rawtherapee
> 
> RawTherapee v5.11 was released August 25, 2024. So it's pretty new. If you're lucky, you might find a pre-built .deb package that you can install in the Docker image by e.g. opening a terminal and running the necessary commands - see this script we wrote for installing Darktable:
> 
> * https://github.com/photoprism/photoprism/blob/develop/scripts/dist/install-darktable.sh
> 
> Alternatively, the AppImage they distribute might work in our Docker image (never tested this) or you can build the latest version from source:
> 
> * https://rawpedia.rawtherapee.com/Linux
> 
> Would you like us to (more explicitly) mention this on docs.photoprism.app? If so, where would you look for this information?

ok,thank you for your response  , I would appreciate it if you could mention this on docs.photoprism.app   , and  I will try to  install in the Docker image if I can find a pre-built package . 
 And  it seems that Darktable cannot convert Sony Raw file either,   in the log window, only displays 
 "
2024-10-09T05:40:06.155878553Z [36mINFO[0m[2024-10-09T05:39:57Z] convert: converting DSC04040.ARW to DSC04040.ARW.jpg (darktable-cli)
2024-10-09T05:40:54.468747532Z [36mINFO[0m[2024-10-09T05:40:43Z] convert: converting DSC04041.ARW to DSC04041.ARW.jpg (darktable-cli)
2024-10-09T05:41:51.736545505Z [36mINFO[0m[2024-10-09T05:41:33Z] index: updated 6 files [3m38.563050921s]
2024-10-09T05:41:53.923986271Z [36mINFO[0m[2024-10-09T05:41:34Z] 索引成功，耗时 219 秒
2024-10-09T07:20:38.353144465Z [36mINFO[0m[2024-10-09T07:20:38Z] 索引 119msdcf 中的文件"  

and no other error logs,   but cannot see photos in the folder or library

**Comment by lastzero** [comment]
You may need to enable debug or trace log mode to see the raw converter error message, if any. Since other converters are tried if the first one fails, we do not consider this a hard error that must be logged immediately and permanently. Some files are just not supported and when we log this for potentially millions of files every time the indexer runs, it would cause a flood of error logs – also making it hard to notice any actually unexpected warnings errors that might occur.
