### ISSUE TITLE
Cache Size and Thumbnail configuration

### ISSUE THREAD

**Issue by corgan2222** [photoprism/photoprism#457]
Hello

i have imported a testfolder into photoprism and found out, the appdata/cache Folder is really big for this few images.

Import Folder: 4k Files - 30gb
Cache: 6gb

Thats a factor of 5. If i would import my complete Library with ~30tb (im a fulltime photographer) that would be around 6tb for the index.

I checked the cache folder and found 21 different Thumbnails for each Image. 
How to configure the amount and size of the Thumbs?
Could not find any settings for this.

Im running the Unraid Docker Version.

**Comment by RAYs3T** [comment]
@corgan2222 If you're running it with Docker you can specify these options in the `docker-compose.yml`:

1. You can reduce the size of the thumbnails: (see: https://github.com/photoprism/photoprism/blob/develop/internal/config/flags.go#L284 )
2. Disable thumbnail caching (see: https://github.com/photoprism/photoprism/blob/develop/internal/config/flags.go#L278 and https://github.com/photoprism/photoprism/blob/develop/internal/config/flags.go#L290 )

**Comment by corgan2222** [comment]
thanks! did not found this!

**Comment by lastzero** [comment]
@graciousgrey Need to add a page with the output of `photoprism help` to our docs

**Comment by lastzero** [comment]
See https://docs.photoprism.org/getting-started/config-options/

**Comment by lastzero** [comment]
Any more questions?

Note that high quality thumbs are large, otherwise information gets lost and end up with a Facebook-like experience. When sharing or viewing images on a screen, you'll always use thumbs and not originals.

Some users think they'll see originals when opening a photo and thumbs are only used as previews in search results.

Even if you have a fast internet connection, browsers are not very good in resampling photos so the result will always have bad quality compared to a properly resampled "thumbnail". In addition, browsers typically don't care about image orientation.

**Comment by cthu1hoo** [comment]
While I understand the point about quality being important, I've recently finished importing a 52 GB worth of photos and it generated 42 GB of thumbnails with default settings.

I know that thumbnail size can be reduced but is this really a reasonable default? To me at least it was unexpected to nearly double the required storage for my (luckily smallish) photo archive simply because of thumbnails. For someone with a much larger photo collection this might have more serious implications.

**Comment by lastzero** [comment]
Are your originals RAW or JPEGs? Of course the ratio will look bad for already compressed JPEGs that are only slightly larger than high-quality resampled thumbs. 100 GB are cheap if you use local storage, why go for bad quality instead?

**Comment by alexislefebvre** [comment]
I think that cthu1hoo suggest to use small values for default settings, so that users who don't read the full doc (that happen more often that we hope) or don't change the thumbnails parameters won't have a bad surprise.

**Comment by lastzero** [comment]
Guess the argument goes both ways. I'd suggest using the high-quality setting unless you want your pictures to look like on Facebook. We plan to add a setup assistant that goes through the various options. Didn't get to that yet.

**Comment by lastzero** [comment]
See FAQ: https://docs.photoprism.org/getting-started/faq/#why-is-my-storage-folder-so-large-what-is-in-it
