### ISSUE TITLE
Centralized account management missing (Active Directory / LDAP)

### ISSUE THREAD

**Issue by Expro** [photoprism/photoprism#458]
Any plans to add support for Active Directory, LDAP or other centralized account management options?

**Comment by lastzero** [comment]
Maybe in a future "pro" release or commercial add-on as we expect this to be (primarily) used in business environments. It's not our goal to provide a free enterprise solution.

**Comment by Expro** [comment]
Well, to be honest, using LDAP / AD got nothing to do with business or enterprise - with multiple community driven open source projects running, creating local accounts on every one of them quickly gets out of hand. That's why all popular open source projects supports it, even in community editions, despite having paid support options (to name few: Nextcloud / OwnCloud, Jellyfin / Emby, Organizr, pfSense, FreeNAS).

**Comment by lastzero** [comment]
We'll get in touch with the community once we are ready to implement new features. They will be implemented based on demand / perceived value. So if enough users need this, we'll do it. However, we can't continue to provide everything for free, especially advanced features that could be used in enterprise environments. Not saying you would do this. Thanks for your feedback!

**Comment by lastzero** [comment]
See also [Multi-User Photo Gallery with private and shared photos/albums #98](https://github.com/photoprism/photoprism/issues/98)

**Comment by lastzero** [comment]
I assumed proper "centralized account management" includes support for multiple, completely independent user accounts as discussed in #98. Limiting LDAP support to a single account will be much easier.

If someone has time to implement this, we'll of course merge it given it is well tested and doesn't introduce security or performance issues. Since we don't have a huge team of developers, we're very careful with introducing complexity to the project. That includes features with potentially high security or performance impact and high testing effort that only very few users actually need / use. This in fact was the first time someone asks for LDAP. Should this become a very common use case for the community edition, we can absolutely put it on the todo list.

**Comment by tigattack** [comment]
I understand you don't want to implement a "free enterprise solution", but could you not go with a pricing scheme of "free for home users" with a limitation of, for example, up to 15 users, including "enterprise" features such as LDAP authentication, which would be really appreciated by many, I am sure.

Businesses would then pay for higher plans as they'd have more users, and you'd get the licensing revenue you need whilst keeping home users happy.

**Comment by lastzero** [comment]
We're working something out right now and will move on from there once we have LDAP done :)
