### ISSUE TITLE
specifying an external USB disk on R Pi?

### ISSUE THREAD

**Issue by purplepandapants** [photoprism/photoprism#459]
I would like all the files saved by photoprism to be placed on an external disk and not the sd card. Any ideas on how to do this?

**Comment by lastzero** [comment]
Mount it and change the originals path to point to the external disk in `docker-compose.yml`

**Comment by purplepandapants** [comment]
Thank you for your reply. 

Can you provide an example I can use or a guide I can read?

**Comment by lastzero** [comment]
For example, you can mount an external usb drive like this:

```
volumes:
      - "/mnt/usb:/photoprism/originals" # [local path]:[container $
```

You can also mount multiple drives as folders to the originals path, so that you can have external drives and internal storage.

The Ubuntu docs contain more information on how to mount external drives: https://help.ubuntu.com/community/Mount/USB

You can probably find Pi specific docs if you google a little bit.
