### ISSUE TITLE
Provide means to plug-in GPU to speedup TensorFlow / labeling

### ISSUE THREAD

**Issue by Expro** [photoprism/photoprism#461]
Labeling using computer vision via TensorFlow is excellent feature, but currently it is done on CPU, which is rather slow - to the point where big collection of images is almost impossible to index on anything other than server-grade hardware.. Please consider adding means to plug in GPU for TensorFlow (OpenCL version over CUDA version would be great) to consume, which will dramatically speed up labeling and thumbnail generation.

**Comment by RAYs3T** [comment]
Someone is already working on adding support for CUDA processing see: #232

**Comment by lastzero** [comment]
You can simply replace the existing tensorflow libs with a version that supports your GPU. We did that here for the nvidia jetson: https://dl.photoprism.org/tensorflow/nvidia-jetson/config/tf_configure.bazelrc

Google provides the library as download as well: https://www.tensorflow.org/install/lang_c

Our downloads for Linux: https://dl.photoprism.org/tensorflow/linux/

We're still using TensorFlow 1.15.2, not sure how to get it from Google. Right now, I only see 2.3, last time I checked they said 1.x is all they can provide and it's compatible with 2.x. So maybe we will update soon (when all more important tasks are done). Probably doesn't make a huge difference for our use case, AFAIK 2.x mainly impacts / improves training, not inference.

I'm also not sure if "Linux GPU support" means the libs support all GPUs equally or you still need to compile the libs for modern Nvidia GPUs (to get the best performance). If nothing changed, libs are always compiled for a specific CPU and GPU architecture. That's why we also provide a AVX2 version for modern Intel CPUs.
