### ISSUE TITLE
Best Way to help? SaaS plans?

### ISSUE THREAD

**Issue by tolicodes** [photoprism/photoprism#482]
Hey guys! LOVE what you're doing here :) I started working on my own project a while back for a cloud photo viewer (https://github.com/tolicodes/cloud-photo-viewer). Didn't get very far hehe. 

Your project is amazing. Great code quality, great UI, awesome features.

I was wondering what the best way I can help would be. I'm a Node/React dev (although I wouldn't mind dipping my toes in Go). I am interested in turning this into a SaaS project, so would be great to chat about that. And in general, would love to have a zoom convo to chat about your plans.

Things that I would be interested in working on (if anyone wants to brainstorm/pair on these) below. 

1) Cloud connection: via `rclone` we could connect to dozens of providers. I haven't figured out how to make this work in the cloud. But works great locally. Keeps crashing for me. I specialize in making great UIs, so I'd love to build a nice GUI on top of `rclone` to do the connection and link it up.
2) Hosting service. So basically a SaaS model of photoprism. We host it for you, no coding required. You can migrate away anytime. Great way to sponsor the project. I'd love to make a little K8S infrastructure to get this going. 
3) Linking in Google's Vision API. The TensorFlow setup you guys have is actually not bad but Google's Vision is so much better. You just link up your API key (or hey maybe we can offer it as a service?), and it works
4) A real calendar - https://github.com/jquense/react-big-calendar is awesome and easy to use. Always wanted a calendar view of my photos

**Comment by lastzero** [comment]
Thank you very much for the great feedback!

As mentioned in the other issue, we won't add new features until a stable release is out of the door. It was a huge challenge to get this far without external funding that might interfere with our goals, see https://docs.photoprism.org/funding/.

1. `rclone` should just copy files to a local drive from remote services, in #152 you mention importing / indexing issues. Maybe when you start importing while rclone is still copying files?
2. Offering additional services or a hosted version (either SaaS or private hosting) might be a way to fund (and speed up) development in the future. Would be great to get help with that as soon as our new backend infrastructure is ready.
3. Using Google's Vision API probably means uploading photos to Google, so that they are not really private anymore? It's clear Google internally can do more than us, but then you can just upload all photos to Google Photos right away (unless you just don't like their UI)?
4. The calendar looks great, but seems based on React while PhotoPrism uses VueJS / Vuetify. In fact we should start optimizing our CSS / JS size before adding more packages ;) Then a calendar would be a good idea!

A 3D earth globe like https://www.webglearth.com/#ll=35.14452,33.74538;alt=17013308;t=-0.181 showing where you've been would also be nice :)

For specific questions or a chat, you can also reach us privately via hello@photoprism.org. This week is incredibly busy though.

Bug fixes are most welcome at any time! 👍

**Comment by lastzero** [comment]
Taking a look at frontend UX issues like **Lag when selecting pictures #477** is also most welcome. I'm sure this can be optimized, just wasn't a priority so far.

There are also a bunch of other issues labeled with "help wanted": https://github.com/photoprism/photoprism/labels/help%20wanted

**Comment by imerr** [comment]
> Using Google's Vision API probably means uploading photos to Google, so that they are not really private anymore? It's clear Google internally can do more than us, but then you can just upload all photos to Google Photos right away (unless you just don't like their UI)?

Googles paid api does have a lot better privacy guarantees than their consumer offering as far as I remember, google wouldn't "store" the photo - just temporarily hold it to generate tags
Using a paid api as an optional feature for people who want better tags would be definitely useful depending on how hard it is to switch out the object detection "plugins"

**Comment by lastzero** [comment]
You would still transfer it over the internet... at the end of the day you don't know what happens with your data there or in between. But yes, for some users who are OK with the tradeoffs - why not.

Also keep in mind that remote detection via Internet will probably be a lot slower and generates additional traffic. Hard to say to what extend without performing tests with real data.

Note that paid Google APIs are typically expensive and MAY have limitations. Geodata for example may not be cached, even if you pay for the Google Maps API.

**Comment by blmhemu** [comment]
Nice post OP. I have recently learnt go-lang and am willing to work on a couple of issues. I know you must be busy, but please list out a few tasks which I can attempt to solve.

**Comment by lastzero** [comment]
@blmhemu Thanks for getting in touch! Only confirmed bugs and other major impediments are getting fixed right now so that our final release (hopefully) is free from major issues.

Did you check our existing GitHub issues for tasks that need help? @graciousgrey might also be able to find something for you :)

**Comment by jdaviescoates** [comment]
> see https://docs.photoprism.org/funding/

I just wanted to add that perhaps you should also create a PhotoPrism collective on [Open Collective](https://opencollective.com/) as another venue to collect regular and/ or one-off donations. They are a much nicer company than Patreon, and [fully open source themselves too](https://github.com/opencollective).

**Comment by graciousgrey** [comment]
@blmhemu @tolicodes At the moment unfortunately we are too busy with our stable release to coordinate and review additional issues. 
Help on bugs is always welcome.
 I will close this ticket for now, but we will contact you as soon as we have more capacity.

@jdaviescoates Actually we have an account on open collective https://opencollective.com/photoprism
