### ISSUE TITLE
WebDAV: Support syncing videos

### ISSUE THREAD

**Issue by fabrees** [photoprism/photoprism#504]
I set up the sync with nextcloud over webdav. For images and sidecar files the sync does work. But videos will not be synced. Import of videos via the import folder mechanism does work for me.
Looking at the code, the file internal\workers\sync_refresh.go does not list videos as supported type.

Would it be possible to add videos via webdav/nextcloud sync, too?

Thanks.

**Comment by lastzero** [comment]
You're right. Probably tried to prevent a situation where PhotoPrism downloads complete Hollywood movie collections, just like we don't download business documents.

There should definitely be a file size limit and a setting to disable videos completely. Otherwise, the next issue that pops up will be "WebDAV sync is very slow and requires lots of storage" 🥳

**Comment by lastzero** [comment]
Going to start a new Docker build for testing soon.

**Comment by fabrees** [comment]
@lastzero how can I test this? I checked the latest x64 docker image - is the container already containing the feature?

**Comment by lastzero** [comment]
Yes, we usually start a new build every day. This happens automatically whenever the master branch is updated, so what you see is what you get:

https://github.com/photoprism/photoprism/commits/master

**Comment by fabrees** [comment]
Ok, thanks. Then I have to check why it is not working...

**Comment by lastzero** [comment]
Did you enable RAW / Video Sync in the settings?
