### ISSUE TITLE
Mosaic view only shows around 50 videos

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#507]
**Current behaviour:** In the mosaic view in the video section only around 50 videos are shown. In the other views everything is working as expected.
**Expected behaviour:** In case there are more than 50 videos all MUST be shown in the video section using mosaic view.

**Comment by lastzero** [comment]
Will be deployed for testing with our next Docker image, hopefully later today.

**Comment by lastzero** [comment]
New Docker images available for testing! Note that the password will be reset to its initial state when upgrading. Our Docker images have been optimized for common NAS models. You can now set a specific user and group using the UID and GID environment variables. Feedback welcome.

**Comment by Morl99** [comment]
Thanks for fixing this. I tested it with the same images where I described the issue before, and now it works as expected.
Updating the docker image also was a no-brainer.

I still somehow feel, that the performance of fast scrolling could be improved by preloading a little bit, instead of waiting until the viewport has actually reached the bottom, but this is more of a tweak than a bugfix and has nothing to do with the original issue (so either use it as feedback, or ignore it for the moment).
