### ISSUE TITLE
Dockerfile for linux distros that don't use apt-get

### ISSUE THREAD

**Issue by ScreamingTaco** [photoprism/photoprism#51]
I noticed the Dockerfile depends on apt to work. As someone who uses a distro that does not us apt, it is taking me quite a while to get a working version of photoprism to build. It might be good if multiple dockerfiles are created to support multiple package managers. I'd be willing to help with an Arch Linux version, I just need to know how the Dockerfiles should be organized within the project directory.

**Comment by lastzero** [comment]
All developers should use the same environment, not different distributions. How else do you know it will work for others?

Ideally the final version uses a very minimalistic distribution like Alpine. Docker config in general needs a lot of optimization to reduce container image size and build time.

**Comment by ScreamingTaco** [comment]
Wouldn’t opening up development to other distros be beneficial in that it will allow photoprism to be used on more platforms? I don’t know what your plans are long-term for the project, but it just seems like opening an issue to have people on different distros write dockerfiles (even if it was labeled low-priority) would be a small task that could reap many positives. Like I said, I could probably make one for Arch if you want and I’m sure people on other distros who find this project could contribute too.

But if you don’t want to do it, I understand. Feel free to close the issue if that is the case.

**Comment by lastzero** [comment]
Depends. Developers should use the same environment, because this is how it works best. Otherwise you don't know if you found a bug or it's an issue with your specific environment.

For deployment via Docker, you usually just want the smallest image and you don't care about the distribution. You don't want a full blown Linux distribution in every single docker image because it wastes storage and updated images take much longer to download (not everyone has fast internet).

It is not our goal to exclude anyone, especially not developers. Ideally we also find a way to install PhotoPrism without Docker on any distribution later, but not at this point. We need to work on the core functionality first. Limit work in progress.

**Comment by ScreamingTaco** [comment]
I see. I’ll go ahead and close the issue for now then.
