### ISSUE TITLE
Add tooltips to icons

### ISSUE THREAD

**Issue by m1ga** [photoprism/photoprism#525]
Add tooltips to the icons in the left menu. Especially if you use the small menu it would benefit the user experience. The names are already translated and next to the icons inside a span.

**Comment by lastzero** [comment]
Experimented with that earlier. Tooltips are mostly not useful on mobile, so it might only help in desktop environments where you can easily open the menu or use it in expanded state. If it still provides values, we can revisit this.

**Comment by barrystaes** [comment]
As a first-time user, (last week) i found buttons lack tooltips, i found it not intuitive and even caused some frustration because i did some destructive actions by accident.

**Comment by graciousgrey** [comment]
@barrystaes For which buttons would you suggest adding tooltips? 
What exactly is unintuitive in selecting multiple items and bulk editing? What could improve it in your opinion?

Regarding the import - we explain it in our docs (https://docs.photoprism.org/user-guide/library/import-vs-index/). 
Please let us know if something in there is not clear.

It is hard to put a long documentation into the user interface especially for the mobile view. 
We know, alone from the interface without reading the docs not everything is totally clear. That's why we plan an onboarding wizard that walks a new user through the basics and the first import or index process. 
Knowing what is not clear to our users helps us a lot!

**Comment by zierbeek** [comment]
hi @graciousgrey , 

There is another project which is made with vue that integrates the tooltip beautifully in my opinion :https://mealie-demo.hay-kot.dev 
You should login with the default credentials and go to a recipe.
<img width="241" alt="Schermafbeelding 2021-08-24 om 15 52 20" src="https://user-images.githubusercontent.com/58994651/130629438-efa86c01-667a-4928-b463-f9908e2a7358.png">

**Comment by lastzero** [comment]
When I hover the minimized main navigation on the left hand side, Google Chrome shows tooltips. Is there anything left to do? We currently don't have time for more beautiful styling as everyone is waiting for facial recognition and a ton of other features. We can revisit styling when we upgrade Vuetify - it comes with tooltips, so an extra library is not needed.
