### ISSUE TITLE
Password reset when updating Docker image

### ISSUE THREAD

**Issue by cthu1hoo** [photoprism/photoprism#532]
When updating from 20200921 to 20201005 I was surprised when admin password got reset to default - "photoprism". Is this supposed to happen? My database with photos was still otherwise available so it's not like it got reset.

It seems to me that this could potentially lead to instance takeover if it gets updated automatically by Watchtower or in a similar automated scenario.

I'm using a largely unchanged  `docker-compose.yml` from the official site, with mysql as the backend database.

I've also tried a cycle of `docker-compose down / up` afterwards but admin password wasn't reset.

**Comment by lastzero** [comment]
Yes, you are right. Note that this is still a development version, although pretty stable and complete. We had to change the name of the table from people to users as this provides more clarity when maintaining it later.

See [chat](https://gitter.im/browseyourlife/community) and https://twitter.com/browseyourlife/status/1313005773627240448 for announcement.

**Comment by lastzero** [comment]
**Users should never set `photoprism` as default password, just like the password for Windows should not be `windows`. A database can get lost for a million reasons, but the pictures will still be there!**

That's why there is no default unless in fact you use our current `docker-compose.yml` example. I think we'll create those dynamically in the future so that we can pre-configure a random password.

**Comment by cthu1hoo** [comment]
Ah, my bad, I haven't noticed that default password is specified in the compose YML. Thanks!

**Comment by andir** [comment]
Thanks for clarifying @lastzero. Just my 2cents since I also had this and probably other users might run into this as well:

I had the same issue and after the upgrade ended up with two entries in the `passwords` table. One created at the original date where I deployed photoprism and the other from the point of time of the upgrade. I changed the `hash` field in the `passwords` table to the value from the old uid and my old password started working again.

**Comment by lastzero** [comment]
**Sorry for any inconvenience!** We didn't provide new Docker images for some time so that it at least only happens once.

On the bright side, this will remind users to set a safe default. We should actually push another update that disables login if the password is "photoprism".

Tweeted a second reminder: https://twitter.com/browseyourlife/status/1313171181932085255

**Comment by cthu1hoo** [comment]
>We should actually push another update that disables login if the password is "photoprism".

either that or make container fail to start when its at default value (or blank). 

personally I'd just leave it unset in the template YML so users would have to set it to *something* with no convenient default.

**Comment by lastzero** [comment]
Others would then be able to set a first password when the database fails. Problem is that we can't do email validation since it's self-hosted. We'll have to fight this with good defaults and documentation.

**Comment by RAYs3T** [comment]
@lastzero Just display a huge, red/yellow blinking, pulsating message on the login screen if the default is set to "photoprism" and disable the login. 
User has to change it before you can use the interface at all.

(Maybe just a red text.. :)

**Comment by Morl99** [comment]
I would be voting for the webserver to refuse the startup if there is no password configured (or the default is set), this follows fail fast principles and the admin would still be in the means of configuring the webserver/docker-compose and could quickly fix the issue, at least if the error message clearly states what to do.

**Comment by RAYs3T** [comment]
@Morl99 Would agree but there is one issue that could scare of new users. Whenever you start the docker container, it does not print out a log by default. So you would have to actively look into the log file. I would rather generate a random password if the default is set and print this into the log / a file and still display a message and the (then accessible) login page.

We have to keep in mind that a lot of people who have limited experience with docker may wanna use this and would simply give up on it (if they can't start it).

**Comment by Morl99** [comment]
So if I understand correctly, you are concerned that newbies to Docker (and I fully acknowledge, that there will be lots of those out there, we all were newbies at some point) will be confused, because they start the container (without docker compose?!), and will not see the error, because the container will not log by default?

I am not sure what you need to do to get it to log (I am not doing anything special here, and it logs just fine), but if that is the case, I would strongly advise to change this behavior in a way, that all log is directed to stdout. This seems to be the default for most of the images I have come across, and would solve this concern.

And if I start a container and it quickly errors out with the message 
`You need to set the mandatory environment variable PHOTOPRISM_ADMIN_PASSWORD to something meaningful by specifying it in the docker-compose file or by adding it to docker run with -e PHOTOPRISM_ADMIN_PASSWORD="<strongPasswordHere>. The server startup will abort.`

I believe that this will be a clear and helpful behavior and will not lead to frustration of new docker users.

**Comment by RAYs3T** [comment]
@Morl99 Right, I was referring to deployments for NAS's and other systems that do not use docker-compose. But like you said for the majority it is properly fine if it forces a crash at startup stating this exact message.

A change is required for sure, because otherwise things like #537 will happen a lot more.

**Comment by lastzero** [comment]
New default in our [docker-compose.yml example](https://dl.photoprism.org/docker/docker-compose.yml) is `please-change`. That should be pretty clear. For development, we keep `photoprism`.

Also updated our docs for Docker and Docker Compose accordingly based on a PR by @RAYs3T:
https://docs.photoprism.org/getting-started/docker-compose/
