### ISSUE TITLE
Reducing indexing load

### ISSUE THREAD

**Issue by aureooms** [photoprism/photoprism#545]
I am interested in the usage of photoprism on machines that are not designed to support constant high [load](https://en.wikipedia.org/wiki/Load_(computing)). Using such machines can be a problem during initial indexing of large collections. As I understand it, the indexing load can be reduced by:

  - Disabling automated tagging: `PHOTOPRISM_TENSORFLOW_OFF: "true"`
  - Limiting the number of workers: `PHOTOPRISM_WORKERS: 1`

Additionally, I think the niceness of the indexing processes should be configurable (currently no configuration?).

What does `PHOTOPRISM_WAKEUP_INTERVAL` do? Would there be any way to throttle the indexing process so that the "number" of indexing workers is less than `1`?

**Comment by lastzero** [comment]
You are right, these are the options we provide. In addition:

- You can pre-render less thumbnails but that will cause very high load and memory usage when you open photos / search results later. So probably not good for your use case.
- You may index only one (sub-)directory at a time so that you don't need to index everything at once.

`PHOTOPRISM_WAKEUP_INTERVAL` is for background jobs like webdav sync / backup. If you only index and don't configure remote services, it makes no difference.

**Comment by aureooms** [comment]
Hi @lastzero, to be able to use automated tagging with my setting I think it is necessary to have a way to throttle indexing (in files/s or MB/s). I do not think this can be done at the file system/block device level since originals may be accessed for other purpose than indexing. [It can be done at the process level](https://unix.stackexchange.com/questions/48138/how-to-throttle-per-process-i-o-to-a-max-limit) if there is a way to separate the indexing process from the rest. I also understand that throttling indexing at the application level would increase the complexity of the code base.

**Comment by lastzero** [comment]
So even one worker creates too much load? The only thing I can think of is calling [sleep](https://golang.org/pkg/time/#Sleep) while indexing, so that it is even slower. If file system performance is a general issue, you might also want to try using MariaDB instead of SQLite.

**Comment by aureooms** [comment]
> So even one worker creates too much load?

Yeah...

Problem is not FS performance (and I already use MariaDB). In my case, the problem comes from the CPU overheating. It is a 8-core laptop that somehow goes to a hard-stop if I ask it to index a lot of stuff in one go (even if I enable only one worker)... (*a machine that are not designed to support constant high load*). I could try throttling the CPU depending on the temperature (maybe this is already done but not well enough?). I have to try to see if enabling the GPU somehow improves things (I assume TF will be able to use the GPU in this particular application?).

**Comment by lastzero** [comment]
TensorFlow must be compiled with GPU support, which is not the case with our default Docker image as it must work on all operating systems and CPUs, not just Linux hosts with a certain Nvidia GPU, see https://github.com/photoprism/photoprism/issues/289

Since a GPU also produces a lot of heat, I assume it might not be the best strategy to avoid overheating. Needs to be tested. In fact, it might be best to disable the GPU completely if you don't need it.

**Comment by aureooms** [comment]
Ok. I'll see if I can throttle the CPU in case of overheating. This is needed independently of photoprism indexing anyway...
