### ISSUE TITLE
Strict matching for related files when stacking by sequence is disabled

### ISSUE THREAD

**Issue by CorneliousJD** [photoprism/photoprism#560]
I'm still in the testing phases of getting this application rolled out and I noticed some discrepancies with my imported files count vs what shows up as "photos".

I found these photos as stacks, despite having stacking disabled in the settings before importing.

Example here, the two files are named

20160414_000000_78EA46EC.00003.jpg
20160414_000000_78EA46EC_78ea46ec

These were random screenshots from a really old image sync i had going on many years ago.
While i admidt I need to go clean these up so stupid stuff like this doesn't make it into PhotoPrism, I'm just doing esting for now.

I understand why they got stacked because of their name, but I don't understand why they got stacked with stacking turned off, and why there's no option to unstack these two?  Other files that shared similar names and were part of THIS exact stack let me unstack, but this one just doesn't let me unstack further? I have another example like this too with 2 other files.

![image](https://user-images.githubusercontent.com/724777/96645442-8eafb000-12f8-11eb-95cc-50bf5c1805c9.png)

PS - My "orginals" count is alawys off, always higher than it should be, no idea why?
I can open a new case on that if you wish.

Thanks in advance!

**Comment by lastzero** [comment]
Stacking can't be disabled completely, only stacking by sequential name like "IMG_1234 Copy.jpg" and "IMG_1234 Copy 2.jpg" etc.

Especially sidecar files or RAW & JPEG always need to be stacked: Sidecar files without a main file simply don't make any sense.

You should probably just index your files instead of importing them so that they don't get renamed. For performance reasons, PhotoPrism uses less metadata when importing to make a decision and is more focused on names. It typically works well when importing files from an SD card, but not so much for old, random files.

Your screenshot shows that the remaining file is a sidecar file. This JPEG was automatically created. Probably from a PNG if it mostly affects screenshots. You may delete it, see #435.

**Comment by CorneliousJD** [comment]
Hmm, weird about the JPEG automatically created, because the original file was a jpeg as it stands.

In the original folder that I imported this is how they appear. 

![image](https://user-images.githubusercontent.com/724777/96654793-1356fa00-130a-11eb-910d-c0718e553eea.png)
So they share the same name with a number after it. Which would make sense if stacking was enabled.

![image](https://user-images.githubusercontent.com/724777/96654836-27026080-130a-11eb-81f7-61e8a7e63426.png)

But they are both jpg's already. 

I will likely try to import month by month of my old photos so I can go in and clean them all up first and remove random screenshots and bad naming, but in this instance it seems like they got stacked because of the name. 

Also here is where you can see my originals folder file count vs what PhotoPrism says I have for originals. 
Odd discepancy in the counts here.
![image](https://user-images.githubusercontent.com/724777/96655007-7ba5db80-130a-11eb-9895-7fde953885b1.png)


Sorry for so many questions! If there's a better avenue to ask questions and bounce ideas back and forth bedies GitHub issues let me know. I'd like to just work all my little kinks out of this before I deploy fully at home.

Thanks in advance.

**Comment by lastzero** [comment]
Based on your feedback, we should add a setting that disables finding related files completely except they have the exact same name and only a different extension.

The current code for finding related files is this:

```
matches, err := filepath.Glob(regexp.QuoteMeta(m.AbsPrefix(stripSequence)) + "*")
````

You see that `stripSequence` is only one factor. A sequence like "copy 1" comes before the extension and is part of the actual file name.

As mentioned, import was designed for importing files from SD cards etc... based on the code above, it in fact groups files by name / prefix. Otherwise it would have to index them completely before taking any action. Since it renames the files when they are added to originals, this grouping will persist (also because we don't rename files in originals for a number of reasons).

In general, just copying files to originals or mounting the originals folder directly makes more sense with existing photo collections that have inconsistent naming:

> Most users with existing collections will want to index their originals directly without importing them, so that existing file and directory names stay the same. (https://docs.photoprism.org/user-guide/library/import-vs-index/)

You're welcome to send example files for testing as remote debugging is difficult. We already had the case that the files were named ".jpg" but were in fact PNGs and also the other way.

It probably makes sense to improve our import logic for use cases like yours. Grouping files during import is a bit more complicated than you might assume: Apple for example used to name "edited" files like `IMG_E1234.jpg` which has a sidecar file named `IMG_E1234.aae` and a related original `IMG_1234.jpg`. The indexer would detect they are related based on metadata like time and location, but the importer may only use the name so we added logic for this. Even worse, `IMG_1234.mov` might not belong in this group, which is an open issue as well.

Also watch out for hidden files & directories. The synology moments app creates a subdirectory `@eaDir`, which contains thumbnails that should not be indexed. Note that the count includes photos that are in review.

**Comment by lastzero** [comment]
Matching is stricter now, guess this might work for you:

```Go
var prefix string

if stripSequence {
	// Strip common name sequences like "copy 2" and escape meta characters.
	prefix = regexp.QuoteMeta(m.AbsPrefix(true))
} else {
	// Use strict file name matching and escape meta characters.
	prefix = regexp.QuoteMeta(m.AbsPrefix(false) + ".")
}

// Find related files.
matches, err := filepath.Glob(prefix + "*")
```

Docker builds are running... hopefully this doesn't introduce unexpected issues.

**Comment by CorneliousJD** [comment]
Ok so the new build indexed originals how I expected it to in this instance with stacking disabled. Thank you!

I'm still at a loss for the "Originals" count here though.
I spun up a new container, new database, new origianls folder, etc.
I copied only 96 files into my originals folder, and indexed.
My photos count shows 96, and when browsing and manually counting the origianls via photoprism I see 96 photos. 
Yet the count shows 135. Am I missing something?

Thanks in advance.

![image](https://user-images.githubusercontent.com/724777/96733007-fa405e80-1386-11eb-9f9b-46999abbd3a3.png)

**Comment by lastzero** [comment]
You may have more files than photos e.g. because some files are videos, broken, or duplicates.

**Comment by CorneliousJD** [comment]
> You may have more files than photos e.g. because some files are videos, broken, or duplicates.
> 
> They may also be JPEGs that were automatically created to display [a preview of] PNGs, RAWs, videos, or other non-JPEG file types...

I definately only have 96 files in the origianls folder, all JPEG photos. 
Although as you noted they could be PNGs named as JPEGs due to being screenshots.

If JPEGs are automatically created for the PNGs, they are stored in the /photoprism/storage/ directory if I understand correctly. And THOSE files are being added up and counted as well as the files in /photoprism/originals/ is that correct? 

When I browse to /photoprism/storage/ it's only showing the 96 photo files I put in there still.

**Comment by lastzero** [comment]
You put the files in the storage folder, not originals? Storage is for all other storage except your photo library, for example the index and sidecar files.

The count in the navigation should reflect the number of files you see in the file browser.

**Comment by CorneliousJD** [comment]
> You put the files in the storage folder, not originals? Storage is for all other storage except your photo library, for example the index and sidecar files.
> 
> The count in the navigation should reflect the number of files you see in the file browser.

No I put 96 images in my /photoprism/originals/ and indexed. 
My photo count shows 96
My origianls shows 135 for some reason. 

That's what's so confusing to me is the originals count does NOT match what's in the file browser.

I was just wondering if it was counting files from /storage/ or somesthing then becuase the counts do not add up and do not make sense. I'm nots ure where it's counting an extra 39 files from.

/photoprism/originals/ only has 96 files in it, the exact amount of photos I placed in it.

**Comment by lastzero** [comment]
These are probably sidecar files in the storage sidecar folder. You can see the storage folder in the edit dialog files tab.

**Comment by lastzero** [comment]
It's possible that we hide generated sidecar files in the files browser, but the files tab shows them for sure.

**Comment by CorneliousJD** [comment]
I think that's the reason then, thank you!

I can see a screenshot file that had .jpg as a name, but is classified as PNG and then shows the sidecar file here in the files tab. 
So it must be the PNGs that got converted to JPGs and/or other sidecar files that drive the count up.

![image](https://user-images.githubusercontent.com/724777/96744737-5c9f5c00-1393-11eb-9d47-46662d11312e.png)

I believe this now answers my question, thank you so much!
