### ISSUE TITLE
Labels: Show photo count

### ISSUE THREAD

**Issue by danielo515** [photoprism/photoprism#584]
Hello.
Right now, I have a lot of labels, but very few photos per label.
It will be awesome if, before opening a label, I can see a count of how many images belong to it, so I get an idea if opening it is worth or not. Specially when the count it's 1, it's pointless to open such a label to see something you are already seeing.

Regards

**Comment by lastzero** [comment]
Our API returns the count in the `PhotoCount` field, we just haven't found a nice way to display it yet:

![Screenshot from 2020-11-08 17-31-38](https://user-images.githubusercontent.com/301686/98470770-480ef080-21e8-11eb-970c-134492b9f24d.png)

**Comment by danielo515** [comment]
This is how they do on QuMagie (some inspiration)
![image](https://user-images.githubusercontent.com/2270425/98580462-4a447e00-22c0-11eb-8b30-04da1d9be221.png)

**Comment by hartraft** [comment]
I think the photocount would be nice to have as well. What would be a better preference? 
Option 1: (similar to how albums are shown and translated but more verbose)
![image](https://user-images.githubusercontent.com/788583/126811103-a8b96166-3e65-4a38-a9e6-55690a831cb4.png)

Option 2: (plain and simple number)
![image](https://user-images.githubusercontent.com/788583/126811191-24163cd2-40a6-44e6-85af-52da1ddb6177.png)

**Comment by lastzero** [comment]
Note that label photo counts are currently not updated in real time:

https://github.com/photoprism/photoprism/blob/develop/internal/entity/photo_counts.go#L89

We had been using (automatically updated) views previously, but they were not compatible with all supported databases.

At the moment, counts can be reliably used to hide labels without any result. Counts > 1 may be imprecise at times e.g. while indexing. It may well lead to frustrated users filing bug reports because numbers don't match. Frequently happens for other counts as well. It's understandable as users are afraid of data loss, and bugs in general.

**Comment by fensminger** [comment]
I updated photoprism to last preview. It is working.
![image](https://user-images.githubusercontent.com/1978956/134763225-3d8f0d1e-91dd-43de-8a3a-69d50df10465.png)
