### ISSUE TITLE
UX: Unstacking a file should also unstack related sidecar files

### ISSUE THREAD

**Issue by Darkwolf1515** [photoprism/photoprism#616]
Had some non duplicate photos stack together, I stacked them, their json's remained.

**Comment by lastzero** [comment]
New json files should be created automatically. You currently can't unstack multiple files as a group. Or do you just want to free up the storage?

**Comment by Darkwolf1515** [comment]
It was a photo that had two or 3 stacked within it, after unstacking, the jsons remain.

**Comment by lastzero** [comment]
There should be a button in the files tab to delete them.

**Comment by lastzero** [comment]
Let me know if this works or if it causes any issues. Ideally, you should be able to unstack multiple files at once so that sidecar files are moved as well. Alternatively it might be able to automatically delete generated sidecar files. They should be re-created when the unstacked files is re-added to the index. There's a lot of complexity in this.

**Comment by Darkwolf1515** [comment]
Right, I just didn't wanna delete them as that might leave those photos dataless.

**Comment by lastzero** [comment]
They should be recreated automatically when indexing the next time.

**Comment by lastzero** [comment]
Maybe we should not even add the JSON files to the index. The idea was to let users know they exist, technically indexing them is not really needed.

**Comment by lastzero** [comment]
PhotoPrism doesn't index sidecar JSON files anymore, seems we already changed this a while ago. Are the JSON files directly in your originals folders?
