### ISSUE TITLE
UX / Play video from places view

### ISSUE THREAD

**Issue by swingstate** [photoprism/photoprism#647]
I uploaded a few videos and edited the location. The map view puts them at the right spot, however when I click on the video icon on the map only the preview picture is being opened. 
I would expect that the video can be started in the same view.

**Comment by lastzero** [comment]
Can you start the video when clicking on the video icon at the bottom of the photo viewer?

**Comment by swingstate** [comment]
I can start the video from the album view. 
When I click on the location tag on the video (still in the album view) I get to the map view where the video is pinned to the right location. When I click on the video the preview picture is loaded, which I can zoom in to, but the video does not start. 
Browser: Firefox 83

**Comment by lastzero** [comment]
We love this! Use the `type:video` / `type:live` search filter to find & play videos on the map:

![Screenshot 2020-12-12 at 22 41 32](https://user-images.githubusercontent.com/301686/101995700-632fbd00-3ccc-11eb-813d-fab2b6602812.png)

**Comment by ewumnrr** [comment]
This issue is still there or resurfaced. I have version "Latest" (Build [251130-b3068414c]). Tried both Safari and Chrome. Video playback stays black and busy icon rotates forever. It does work if I zoom out until the video clusters with another item. I can then select the video from the cluster insert, and then it plays correctly.
