### ISSUE TITLE
Converted videos don't show a preview picture

### ISSUE THREAD

**Issue by swingstate** [photoprism/photoprism#648]
I converted some older .avi files to H.264 / .mp4 and uploaded them. So far import works fine, however then in the videos the file is displayed only with a black preview. Locally on the PC where I uploaded the file from the video is displayed with a preview, like movies are displayed. Other converted .mov files show the preview. 

![grafik](https://user-images.githubusercontent.com/73672554/100101649-d16a2800-2e62-11eb-940a-b0b28034090f.png)

**Comment by swingstate** [comment]
This could be related to the original material. I'll test further and edit here.

**Comment by lastzero** [comment]
Maybe the first frames are black? That would also lead to a black preview with our current implementation.

**Comment by axllent** [comment]
It took me a while to find this, and it explains everything - almost all my videos have black thumbnails. It seems that any video taken with mobile phones has a black first frame (or few frames).

Would it be possible to take the 8th or 16th frame instead (.5s or 1s into the video) to prevent this?

![Screenshot_2021-01-22 PhotoPrism Browse Your Life](https://user-images.githubusercontent.com/1463435/105453683-6d8aa100-5ce5-11eb-93f5-466d7b7e0da6.png)

**Comment by StianOby** [comment]
I'm seeing wall of black squares in my installation as well. Perhaps worth reopening this? There are several ways to solve this issue. I can think of a few, with varying levels of complexity:

- Pick preview image from just a few frames into the video file.
- Pick preview image from several (e.g. 3) points into the video file, choose one by default, and then let the user swap that with one of the alternates (i.e. like youtube).
- Pick preview image from just a few frames into the video file, but add a function so that the user can manually pick a timecode/frame to replace the preview image.

**Comment by graciousgrey** [comment]
@StianOby We have a ticket for custom video thumbnails here: https://github.com/photoprism/photoprism/issues/1241 :)

**Comment by StianOby** [comment]
Thanks for pointing me in the right direction! For some reason #1241 didn't appear in my searches. The (principal) solution suggested there sounds perfect.
