### ISSUE TITLE
Feature Request: Android and iOS app.

### ISSUE THREAD

**Issue by DillFrescott** [photoprism/photoprism#702]
This would be sooooo nice to have. Complete with auto upload of course!

**Comment by DillFrescott** [comment]
Nevermind I see thats already being worked on lol

**Comment by DillFrescott** [comment]
So much for my good ideas 😀

**Comment by lastzero** [comment]
You might also want to take a look at Photo Map as a mobile viewer, and PhotoSync for uploads. Standards and APIs are amazing. No need to reinvent the wheel like Google, Apple and Facebook do whenever they come up with a "new" product.

**Comment by DillFrescott** [comment]
Ok. I definitely will! Thank you!

**Comment by DillFrescott** [comment]
> 
> 
> You might also want to take a look at Photo Map as a mobile viewer, and PhotoSync for uploads. Standards and APIs are amazing. No need to reinvent the wheel like Google, Apple and Facebook do whenever they come up with a "new" product.

So I just dump the photos into the /originals/ folder via webdav and photoprism does the rest?

**Comment by lastzero** [comment]
You'll need to manually start indexing for now (or importing if you want PhotoPrism to take care of the file names). This is because it's (almost) impossible to know when users are adding or modifying files. Automatically starting to index while files are being modified is a sure receipt for conflict. We'll find a way to read our users' mind one day though.

**Comment by DillFrescott** [comment]
Got it lol. I'm sorry I'm asking a lot of question s but this is just such an awesome project! Thank you for all the knowledge Michael I really do appreciate it!
