### ISSUE TITLE
Stacked photos grouped by similarity are duplicated

### ISSUE THREAD

**Issue by alexislefebvre** [photoprism/photoprism#715]
When I show _Stacks_ and choose _Group by similarity_, then images are duplicated:

See example from demo:

> ![image](https://user-images.githubusercontent.com/2071331/102374556-c3bb4480-3fc1-11eb-9423-cb269ede19d8.png)

URL: https://demo.photoprism.org/photos?view=cards&order=similar&q=stack%3Atrue&public=true&quality=3

Is it the expected behaviour?

**Comment by lastzero** [comment]
Individual files are not guaranteed to be displayed next to each other (or on top of each other in case of a stack) when grouping by similarity - even if they belong together based on their file name or metadata. Stacks are displayed when files with the same photo id come next to each other in search results. If they don't, they're not getting "stacked" in the UI, but still share the same metadata (like title and description).

Typically this happens due to different contrast, brightness, colors, or other editing (especially when there are many similar images with only slight differences):

![Screenshot 2020-12-16 at 17 33 39](https://user-images.githubusercontent.com/301686/102377821-67f2ba80-3fc5-11eb-8cf5-2d22df697a6a.png)

Now of course you can say our algorithm must be improved because it has a different perception than you - and that's totally true in some cases. Once we can afford paying a full-time developer to work this, expect major improvements.

**Comment by lastzero** [comment]
We specifically use the contrast differences of an image. Now when there are image versions where a corner (or the sky) is just white or has very little contrast, it will get sorted differently than a version with a regular sky (blue, clouds). Should probably ignore contrast in such edge cases.

**Comment by alexislefebvre** [comment]
Thanks for the explanations.

In the demo, the first and third image are the same lot of files: the primary image `demo/20131118-185933-Landscape-Cape-Town-2013-245.jpg` in details of both images. So the contrast, brightness, etc. are identical but the grouping sort of duplicated the results.

**Comment by lastzero** [comment]
Checked it again: Our contrast algorithm works perfectly, but one image version is slightly more blue while the other is slightly more green (nature & sky are both dominant). The ski picture obviously is mostly blue because of the sky. Computers think digital, so either blue or green when you sort it. Not both in a mixed way as the database can't sort that quickly, or even understand what it means.

To solve this, we could set a default color for a stack, independent of how many different files there are (green, blue, black & white,...).

**Comment by lastzero** [comment]
Looks fixed to me - fresh Docker builds available for testing soon:

![fixed](https://user-images.githubusercontent.com/301686/102483028-70e69900-4064-11eb-8db1-93a7f1145cdc.png)

**Comment by alexislefebvre** [comment]
I didn't understood everything but the Cape Town is not duplicated anymore on the demo: https://demo.photoprism.org/photos?view=cards&order=similar&q=stack%3Atrue&public=true&quality=3

Thanks!

**Comment by lastzero** [comment]
You're welcome!
