### ISSUE TITLE
WebDav: reflect folders when syncing

### ISSUE THREAD

**Issue by Ambroisie** [photoprism/photoprism#722]
I have setup two-way sync with NextCloud as explained in the docs, and noticed that  my imported pictures did not appear in folders as they were structured on my NextCloud instance. I think it would be more intuitive to import them as if it were a normal `import` directory.

Am I missing something on how this is supposed to work?

**Comment by lastzero** [comment]
Did you enable the "preserve file names" option?

**Comment by Ambroisie** [comment]
I have.

I also noticed that the `Library` tab does reflect the NextCloud file hierarchy, it seems like I am therefore misinterpreting what `Albums/Folders` mean.

**Comment by lastzero** [comment]
Oh yes, folder albums are not displayed in a nested or otherwise special way, they are listed like other albums in a flat card view... to see files and folders:

https://demo.photoprism.org/library/files

Note that PhotoPrism is not meant to be used as a file explorer, there are better tools for this and we offer WebDAV as well so that you can use your native operating system to browse files and folders within PhotoPrism.

**Comment by lastzero** [comment]
Make sure this is selected BEFORE you sync to preserve remove file and folder names:

![Screenshot 2020-12-19 at 15 37 56](https://user-images.githubusercontent.com/301686/102691909-391c5480-4210-11eb-9d7f-02c651285004.png)

Implemented this a long time ago, so not 100% sure if names can be preserved two-way... in general, I would not recommend syncing back and forth as keeping track or moved and copied files is a pain for every tool, especially via WebDAV. PhotoPrism doesn't contain special magic to avoid these general issues. The best you can probably do is match by attributes so that you don't need to keep distributed file systems in sync.

Consistent distributed data storage is one the most difficult problems in computer science.

Ideally you simply mount the same drive as your other service / server uses. Then you save storage and don't need to sync.

**Comment by Ambroisie** [comment]
Thank you for your answers, I was confused about the difference between album folders and file system folders it seems.

Thank you for your hard work, this is great software!

**Comment by lastzero** [comment]
Thank you 🐳
