### ISSUE TITLE
Shares: cannot reuse (deleted) secrets

### ISSUE THREAD

**Issue by Sherlock1979** [photoprism/photoprism#776]
Hi,

When I try to re-use a share secret token that I already used and deleted before, the share url does not bring up any albums.

1. Create a new album, add a photo.
2. Share the album. Change the secret token (e.g. to mysecret).
3. Check the share url in a new private browser window: https://my-photoprism-site/s/mysecret. It should work as expected (showing the shared album). Close the private browser window.
4. Delete the album.
5. Create a new album, add a photo.
6. Share the album. Change the secret token to the same as above (e.g. mysecret).
7. Check the share url in a new private browser window: https://my-photoprism-site/s/mysecret. It will not show any albums but say: "Couldn't find anything. Try again using other filters or keywords."

Note: the error cannot be reproduced on your demo site - as on the demo site all users who open a share link are granted full access because login is disabled. I have tested it on a standard setup where login username is configured.

Thanks,
David

**Comment by lastzero** [comment]
Thanks for reporting this!

**Comment by lastzero** [comment]
Guess you have your username for a reason :rofl: 

Can confirm this issue when the new album has the **exact same name as the old one**... might fix this by deleting existing share tokens when an album gets deleted... wanted to keep this for future reference, as I didn't expect someone would do this :roll_eyes: 

![bug](https://user-images.githubusercontent.com/301686/103407411-e66f6080-4b5e-11eb-938b-20b335212f39.png)

Otherwise, it's working just fine (if the session is messed up for any reason, you might have to try a second time):

![fruit](https://user-images.githubusercontent.com/301686/103407218-2255f600-4b5e-11eb-862e-86e38e505bd8.jpg)

**Comment by lastzero** [comment]
As it turns out, I saw this coming and disabled it for security reasons. It's allowed now, but note that continuously reusing the same album names and share secrets is **not a safe practice**.

**Comment by lastzero** [comment]
Docker build has been started: https://docs.photoprism.app/getting-started/updates/#development-preview

Please use `photoprism/photoprism:preview` for testing preview builds.
