### ISSUE TITLE
See the reason why an element is in the hidden library

### ISSUE THREAD

**Issue by llompartg** [photoprism/photoprism#791]
Hi

I just finished indexing, and it looks like I have over 4000 hidden files in my library.

As I understand it these files could be either files with an invalid format or files that are duplicated. Is there any way to know what happen for a particular file? 

Also, if the file is considered a duplicate, is there any way to check where the matching file is?

Thanks

**Comment by lastzero** [comment]
> I just finished indexing, and it looks like I have over 4000 hidden files in my library.

What format? Do they have anything obvious in common?
 
> As I understand it these files could be either files with an invalid format or files that are duplicated. Is there any way to know what happen for a particular file?

Duplicated won't show up in hidden. It commonly happens where there are RAW files or movies for which no JPEG preview image could be created.

There might be rare edge cases left e.g. when a preview can be created but it is identical to an existing image so that it is skipped while indexing - leaving the RAW or movie behind without a JPEG preview assigned.

> Also, if the file is considered a duplicate, is there any way to check where the matching file is?

In fact, there might be multiple matching files. We don't have a UI for this yet, but also only reached 3% of our funding goal - fair is fair. You can use any database tool and take a look at the duplicates table. It lists all duplicate files incl their hash. You may join this with files.file_hash to see matching files.

Hope this helps!

**Comment by llompartg** [comment]
Hey thanks for your quick response

> What format? Do they have anything obvious in common?

As far I've seen though there's a lot of GoPro things:

- Some videos which have been stacked with format MP4, LRV and THM
- Time-lapse pictures which are JPEG

Now, regarding the videos at one point I saw an error on indexing because of the file size limit, which I increased to 5000 adding PHOTOPRISM_ORIGINALS_LIMIT: 5000 to my config

The time-lapse pictures are coming from a directory in which I have a .ppignore so I'm not sure why would they even appear there?

Is there any way to query the database for this data? It would be a lot faster to find patterns.

>  You can use any database tool and take a look at the duplicates table. It lists all duplicate files incl their hash. You may join this with files.file_hash to see matching files.

This works great to find the duplicates! I might find time to help develop a UI for this

Thanks

**Comment by lastzero** [comment]
THM files might be an issue, as they are JPEGs but don't count as preview because the resolution typically is pretty bad. I have one video with a THM preview marked as hidden although it technically has a preview, and it is also shown in our UI. What resolution do your THM files have?

To find hidden photos, query the photos table for rows where `photo_quality < 0`

**Comment by llompartg** [comment]
I've had a look and the THM files have a resolution of 160x120

A few things I've realised by querying the data...

First of all there seems to be more photos with quality < 0 than photos in the hidden folder count. I thought this could be due to duplicates, but the duplicates table only returns about 250 rows.

![Capture](https://user-images.githubusercontent.com/5967772/103485992-6a8d4680-4df2-11eb-8513-7f8ef5b85969.PNG)

The vast majority of files come from time-lapse folders which I thought would be excluded from the indexing.
I have a .ppignore inside TimeLapses folder. The file only has two rules

`*.*`

and

`*GOPRO`

Is there any way I can get photoprism to forget about those folders?

**Comment by lastzero** [comment]
You're right, should have been more specific: `photo_quality < 0 AND deleted_at IS NULL`

**Comment by lastzero** [comment]
When photos are getting merged, they are getting soft deleted by setting `photo_quality = -1` and `deleted_at = NOW()`. Can delete them instantly as there might be files in the indexing pipeline still referencing the ID.

**Comment by llompartg** [comment]
Filtering by deleted_at returned the right values

![Capture2](https://user-images.githubusercontent.com/5967772/103486641-26507500-4df7-11eb-8596-6736cb303c27.PNG)

Again most of them are inside that TimeLapses folder which I'd be happy to get rid off. 

> Can delete them instantly as there might be files in the indexing pipeline still referencing the ID.

Not sure what do you mean by that, do you mean deleting the rows from the photos table?

**Comment by lastzero** [comment]
> > Can delete them instantly as there might be files in the indexing pipeline still referencing the ID.
> 
> Not sure what do you mean by that, do you mean deleting the rows from the photos table?

Typo. We do a "soft delete" as we *can't* remove the row (using a regular SQL `DELETE`) instantly. Note that MANY workers may be indexing at the same time. So when one deletes a resource another one is still using, you have a problem.

**Comment by llompartg** [comment]
Does that mean that at the moment there is no way of getting photoprism to forget about them?

**Comment by lastzero** [comment]
I'd rather keep the rows in case there is important data left in there for any reason I'm not aware about right now. Deleting completely is easy. Is this an issue for you right now?

**Comment by llompartg** [comment]
Then I'll keep it as it is, 4476 is my new zero from now on
