### ISSUE TITLE
Account: Add Support for 2-Factor Authentication

### ISSUE THREAD

**Issue by swingstate** [photoprism/photoprism#808]
I am thinking to host my pp instance behind a reverse proxy to allow colleagues etc. to access albums.

However, I think the lack of two-factor authentication is a "minus" for publically hosted / accessible instances. Hence my ask to add this as a near-term feature, at least for 2FA apps such as google authenticator /  Authy (Google agnostic) / FreeOTP / Microsoft Authenticator to name a few. 

Long term support for Authelia should be added to the backlog. 

Security should go first and it would be a big plus for pp to have this on the feature list. :) 

### Screenshots

**Settings > Account**

![account-buttons](https://github.com/photoprism/photoprism/assets/301686/770987c8-1936-4473-be37-a9e784fb4300)

**Login with 2FA**

![login-with-2fa](https://github.com/photoprism/photoprism/assets/301686/f3f738d5-b19c-4849-9886-3d354788ed19)

**Comment by benmccann** [comment]
Another idea might be to support login via OAuth / OpenID providers such as Google, Apple, Microsoft, etc. This would probably be a prerequisite for connecting to the APIs of any of those providers. And it may also be helpful in the case where multi-user support is added as it may be easier to have friends or family login using their existing accounts rather than creating another one (login via local password creates its own challenges such as password reset). Those providers all offer 2FA, so depending on your needs that may accomplish support for 2FA in the process.

**Comment by kris-nova** [comment]
After working on a Go client and building out an auth mechanism - as a security engineer I am willing to put in some free cycles to help out with an OAuth / 2FA implementation in the backend Go code. No idea when I will have time, but I am happy to help/fund if needed :)

**Comment by swingstate** [comment]
$128 donated, hope it helps to bring this feature to life.

**Comment by lastzero** [comment]
Thank you for your kind donation! 💐

As already answered in the chat, additional multi-user features have not been released yet. This is partly because a few unexpected issues like [security vulnerabilities](https://docs.photoprism.app/release-notes/) in Go and Log4j surfaced before Christmas and we have a zero bug policy.

They will be released when we deem them safe and bug-free. Besides providing support and fixing bugs discovered in the stable release, this is currently our highest priority.

When OpenID Connect integration has been released, two-factor authentication can be "enabled" by using a provider that supports it, for example Keycloak or Google.

We may later add a full, standalone user management to PhotoPrism, but don't see enough value in it at this time given the many other feature requests and ready-to-use user management solutions.

**Comment by bestrocker221** [comment]
In my opinion a key plus point of photoprism was the complete detachment from Google/Apple/whatever, so that you can completely be self reliant with no other providers. For many, privacy comes first.
In that way, a 2FA for locally managed accounts would be awesome!

**Comment by avm99963** [comment]
@bestrocker221 You could also use Keycloak (as mentioned by @lastzero) which is open-source and self-managed.

**Comment by NemesisRE** [comment]
or [authentik](https://goauthentik.io/)

**Comment by Kvaksrud** [comment]
In a world of constant security challenges MFA is a must! Get a date set :)

**Comment by swingstate** [comment]
@lastzero what's the likelihood that this feature will make it into one of the (upcomming) 2023 releases?

**Comment by lastzero** [comment]
I think so and agree that this is an important feature. Funding is the top priority right now so I don't have to implement this (and all other feature requests) all by myself.

**Comment by tupyy** [comment]
Hello,
Is someone working on this? If not, I would like to work on this.

**Comment by lastzero** [comment]
We are going to work on this after a short break as we have just released a huge update.

**Comment by swingstate** [comment]
Can you share an update on the progress of this feature? I donated $128 and supported with a monthly payment for a year or two. Thought this would have a bigger impact :) 
My License is back to "Essentials", not a big deal, just a FYI.

**Comment by lastzero** [comment]
@swingstate Feel free to [email us](mailto:membership@photoprism.app) if you have any questions regarding your membership. As [publicly announced](https://floss.social/@photoprism/110618237808416221), we are currently on vacation and have committed to merging the open pull requests before we proceed with implementing more features. Since many users need 2FA and security is a priority for us, it shouldn't take too long once we have some time to focus on it.

**Comment by DmitryNefedov** [comment]
> $128 donated, hope it helps to bring this feature to life.

Seems like a donation is NOT the way to bring the features to life. Pity.

**Comment by leosamuele221** [comment]
up

**Comment by lastzero** [comment]
As a first step, we would like to add 2FA via TOTP, for example based on the https://github.com/pquerna/otp library. We still need to do some research to determine what changes are needed to the existing user management backend and frontend, and to figure out which workflows will work best for us, e.g:

- https://github.com/pquerna/otp#user-enrollment
- https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication

**Comment by DmitrySandalov** [comment]
I appreciate the ongoing effort on 2FA. 

While TOTP for 2FA is a great step, I'd like to suggest considering FIDO2 WebAuthn 2FA as well, in addition to TOTP (e.g. Yubikey). It aligns with modern security standards and offers a user-friendly alternative.

**Comment by lastzero** [comment]
@DmitrySandalov We're also looking into [WebAuthn](https://en.wikipedia.org/wiki/WebAuthn) for password-less authentication. From my understanding, you would still want to use 2FA to [register passkeys](https://en.wikipedia.org/wiki/Passkey_(credential)), so we need TOTP first either way?

**Comment by lastzero** [comment]
A brief update from us regarding the implementation of 2FA, [OpenID Connect #782](https://github.com/photoprism/photoprism/issues/782) and Passkey support:

- We will be [rolling out another service release](https://docs.photoprism.app/release-notes/#november-28-2023) this week that includes updated dependencies and fixes for recently discovered issues, so users affected by these issues won't have to wait any longer.
- As **shown in the screenshot below**, we will then proceed with implementing 2FA by adding a "2-Factor Authentication" button and dialog to the frontend when you navigate to *Settings > Account* (or click on the user avatar at the bottom of the sidebar)
- For 2FA, **Time-Based One-Time Passwords (TOTP)** will be supported along with a random 16-digit recovery passcode, for example `QBsk-nyUb-sdWU-mMco`, in case your Authenticator app fails (it should not be used for anything else as using it will disable 2FA so you can set it up again with a new Authenticator app and recovery passcode).
- In addition, users will be able to **generate a random 16-digit passcode for WebDAV access** and probably also for connecting native apps like *Gallery for PhotoPrism* and *Photo Map*, see https://www.photoprism.app/partners (these should have restricted access to avoid abuse, i.e. you will not be able to change the main account password with them, and with the WebDAV password you should only be able to use WebDAV and not the UI). We could also consider other authentication methods like HTTPS client certificates. However, this would require changes in the mobile applications and might be too complicated for some users.
- Once this is done, we will release another stable version before adding support for [OpenID Connect](https://github.com/photoprism/photoprism/issues/782) and Passkeys (we don't know in which order yet).

If you have any concerns or special requirements in this regard, now would be a great time to let us know :)

![2fa](https://github.com/photoprism/photoprism/assets/301686/c527cd55-2676-4040-9a70-bd4bb5ece16a)

**Comment by swingstate** [comment]
I appreciate the long breath and dedication you bring to this.

**Comment by tribut** [comment]
Thanks for the update!

This may be a language problem, but I'm assuming the random 16-**digit** passcodes will not only consist of numbers? That would seem very little entropy.

**Comment by lastzero** [comment]
@tribut I agree that the wording can be misunderstood. Since we have little time to come up with our own word creations, I've stole this from Google:

![Screenshot 2023-11-28 at 21 14 02](https://github.com/photoprism/photoprism/assets/301686/4cb758e7-dd93-4dbe-8368-a7c347118fa0)
*Source: https://support.google.com/accounts/answer/185833?hl=en*

Why didn't we just say "characters"? Because the passcode is separated by 3 dashes for better readability, so the actual length is 19 characters, but only 16 characters contribute to entropy. Here's an example:

```
QBsk-nyUb-sdWU-mMco
```

Since Google only uses lowercase letters and numbers, the entropy of our passcodes is much higher than theirs... assuming their randomness is not significantly better than ours. See the commit referenced above for details.

**Comment by lastzero** [comment]
For an overview of today's progress in adding more authentication options, see this recently merged PR:

- https://github.com/photoprism/photoprism/pull/3730#issuecomment-1847651427

My local development build now supports generic bearer token authentication headers and there is a new `auth_clients` database table that allows you to add API clients independent of user accounts, but optionally also linked to specific accounts.

This could be used to implement app access to the API when 2FA is enabled and would allow finer control than the original concept of two app passwords, one for general API access and one for WebDAV.

**Comment by lastzero** [comment]
Initial support for authentication with [OAuth2 Client Credentials](https://github.com/photoprism/photoprism/issues/3943) is now implemented to protect the [new Prometheus-compatible metrics](https://github.com/photoprism/photoprism/issues/213) API endpoint. We also consider using it in combination with 2FA to allow mobile apps and WebDAV clients to access the API when 2FA is enabled.

Specific options for this would be:
- (a) creating an (expiring or non-expiring) access token through the UI or command line interface that can be configured in apps instead of the username/password,
- (b) creating a client_id and client_secret and using them in apps instead of the regular username/password (the app still needs to request an access token afterwards), or
- (c) implementing a flow where apps redirect to your PhotoPrism instance, you grant permission to connect the app, and then are redirected back to the app with an authorization code that allows it to create an (expiring or non-expiring) access token.

Note that method (c) additionally requires the registration of a URI scheme in iOS/Android for the redirect back to an app to work. Also, from what I know, PhotoSync and most other WebDAV clients just support a regular username/password for authentication, which only seems to be compatible with methods (a) and (b) e.g. when you use the client secret or access token as password.

**We welcome feedback and any help with testing so that we can improve the implementation if necessary before releasing it! ✨**

If you would like to test the new `POST /api/v1/oauth/token` endpoint, you can use the [photoprism/photoprism:test](https://hub.docker.com/r/photoprism/photoprism/tags?page=1&name=test) image available on Docker Hub and, for example, run this in a terminal to create a new access token:

    curl -Ss -X POST http://localhost:2342/api/v1/oauth/token \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    -d 'grant_type=client_credentials&scope=metrics&client_id=ID&client_secret=SECRET'

Simply replace `ID` and `SECRET` with the actual client ID and secret created using the new `photoprism clients add` command and make sure the base URL is correct, i.e. you may also need to change `http://localhost:2342/`.

**Comment by lastzero** [comment]
After speaking with @Radiokot, one of the [mobile app](https://play.google.com/store/apps/details?id=ua.com.radiokot.photoprism) maintainers, we will probably allow users to create access tokens for apps through the user interface, just like many popular websites/services do.

This corresponds to option (a) and seems to be the easiest to implement in order to replace authentication with a user's username/password when 2FA is enabled. The best solution to allow WebDAV access with 2FA has yet to be determined.

**If you have any other preferences, questions, or concerns, please let us know!** 🤗

**Comment by lastzero** [comment]
With the commits referenced above, you can now create personal access tokens for authentication with our API without having to first register an OAuth2 client application, e.g. by running the following command in a terminal:

```
photoprism auth add --name MyApp --user admin
```

To see all supported command flags:

```
photoprism auth add --help
```

Note that there is no updated development preview for testing yet. So if you want to try this, you will need to build from source until we feel it has been tested enough to make it available to everyone.

**Comment by lastzero** [comment]
Today's changes ensure that existing mobile apps will continue to work until maintainers have had time to update their API client implementations to use one of the new authentication options.

Anyone who wants to help with testing can now use the updated `photoprism/photoprism:test` image. We welcome early feedback so that we can release these improvements as quickly as possible.

**Comment by Radiokot** [comment]
I'd like to test the changes, but can't find the updated images. Docker Hub reports that the latest `preview` and `test` images are almost a month old:
<img src="https://github.com/photoprism/photoprism/assets/5675681/17e6bb5b-47a0-4564-88d6-6a0e1b0994f4" width=500 />

**Comment by lastzero** [comment]
@Radiokot Thanks for letting me know! The image had been built, but I needed to manually push the `:test` tag. It should be available now :)

**Comment by Radiokot** [comment]
@lastzero 
I've tested the image with the gallery app, here are the results:
- Legacy sign in is working, which is a big relief;
- Access tokens created from CLI can be used to access API endpoints with `X-Auth-Token` header;
- Automatic sign in when opening the web app from the gallery is broken – I'll investigate what new values need to be put to the local storage to make it work.

**Comment by lastzero** [comment]
@Radiokot  That was quick :)

> Access tokens created from CLI can be used to access API endpoints with X-Auth-Token header;

Glad you found the new `X-Auth-Token` header which replaces `X-Session-ID`:
- The old header name will be deprecated with the next stable release, but continues to work for now.
- This is to avoid ambiguity, as the actual value remains the same (see below for more details).

Note that using a standard Bearer-Authorization header is also supported. However, there are some folks who run our software behind a proxy with Basic Auth enabled, which makes use of the same header.

So, based on my understanding, using Bearer and Basic authentication at the same time could lead to problems. Our frontend therefore sends the auth token in the `X-Auth-Token` header by default (if anyone has actually tried this and knows more about it, please let us know).

> Automatic sign in when opening the web app from the gallery is broken – I'll investigate what new values need to be put to the local storage to make it work.

Instead of `session_id`, our frontend now uses `sessionId` and `authToken` for the API credentials:

https://github.com/photoprism/photoprism/blob/f8e0615cc86f9c9eb0e8276d0995f74e6996dc78/frontend/src/common/session.js#L58-L59

Note that the value that was previously stored in `session_id` is the same as now stored in `authToken`, while `sessionId` is actually new (currently the SHA256 hash of the `authToken`).

This gives us a unique session identifier and allows for all kinds of auth tokens to be used without having them stored unencrypted and/or showing up in request logs, which is a big security improvement (depending on your server environment, e.g. who else has access to your logs and database...).

**Comment by Radiokot** [comment]
Good point on Basic auth. Indeed, you can't simultaneously have Basic on your proxy and Bearer in the app, as you can't fit two values into one `Authorization` header.
Based on implementation details you sent, I fixed the automatic sign in script, thank you. Really like session ID derivation from the auth token through hashing.

**Comment by lastzero** [comment]
Here's another brief update on the implementation of 2FA, OAuth2, and OIDC:

- I just pushed a fresh `photoprism/photoprism:test` image to Docker Hub so that anyone interested can test the new [OAuth2 Authentication](https://github.com/photoprism/photoprism/issues/3943) options and API endpoints after today's refactoring.
- Next, we will try to add support for auth token headers to the WebDAV API (in addition to Basic Auth, which is not very secure and should be avoided when possible).
- Once that's done, we can start working on the UI and see what else is needed to also support [OpenID Connect (OIDC)](https://github.com/photoprism/photoprism/issues/782).

**Comment by lastzero** [comment]
WebDAV authentication with access tokens and app passwords has been implemented. Run the following command to create a new personal access token that can only be used for WebDAV:

```
photoprism auth add -s webdav [username]
```

Note that you can also use the access token as password in WebDAV clients that do not support bearer authentication headers. If the client also requires a user name, set it to "access-token".

It's working for me, but we still need to test it with a range of clients. The `photoprism/photoprism:test` image has been updated for this! 🤞

**Comment by Radiokot** [comment]
WebDAV authentication with "access-token" username works in the Autosync Android app as well as in the WinSCP Windows program. Native Windows connection (add network drive, add network location, open the path in explorer) doesn't work, although it never did 🤷🏻‍♂️

**Comment by lastzero** [comment]
@Radiokot Thanks again for testing! If the server does not use HTTPS or has an invalid certificate, you may need to change the basic authentication level in the Windows registry:

- https://docs.photoprism.app/getting-started/troubleshooting/windows/#connecting-via-webdav

We also have the following step-by-step guide for Windows users, as Microsoft has made the setup really complicated:

- https://docs.photoprism.app/user-guide/sync/webdav/#__tabbed_1_2

It would be interesting to know which clients also work with a blank username? PhotoSync, for example, seems to accept it, but then doesn't save the password you enter (which is how I came up with the "access-token" username that you can use instead).

**Comment by lastzero** [comment]
With the latest `photoprism/photoprism:test` image, you can continue to use your regular username when authenticating with our WebDAV API using a token as password.

As an additional verification step, the username entered (in the basic authentication form) is compared to the user assigned to the token. It is still possible to enter a blank username (can be changed in the final version, depending on your feedback).

Note that our personal access tokens are now based on this function, which generates shorter, more human-friendly tokens:

https://github.com/photoprism/photoprism/blob/e8ca9b8db2e07e03c59d60c87e02ee829cae475d/pkg/rnd/auth.go#L42-L43

Standard auth tokens for use by the UI and OAuth2 clients are generated with `rnd.AuthToken()`, for example:

```
9fa8e562564dac91b96881040e98f6719212a1a364e0bb25
```

These cannot be used instead of a password in combination with basic authentication and only work if you send them with one of the supported headers.

We could implement other "app passwords" (for the regular API) in a similar way?

**Comment by lastzero** [comment]
Happy to report that an updated `photoprism/photoprism:test` image is available on Docker Hub. It allows you to use the shorter, more human-friendly access tokens as password replacement when the `*` or `sessions` scope is set and it belongs to the same user. To create one, you can e.g. run this command in a terminal (if you omit the scope flag, it will ask):

```
photoprism auth add -s '*' admin
```

Note that the personal access tokens accepted by the API and generated by this command are now slightly longer and include a checksum character to detect typos without needing to perform a request first, for example:

```
OXiV72-wTtiL9-d04jO7-X7XP4p
```

If you use these personal access tokens or "app passwords" for authentication, external applications cannot e.g. manage users and sessions through the API or perform other actions outside the configured scope, even if the token belongs to an admin. This is an important difference to sharing your actual account password and allows us to maintain compatibility with existing apps and clients while improving overall security.

I've additionally reworked our server API over the past two days to further improve caching, performance and security in combination [with a CDN](https://github.com/photoprism/photoprism/issues/3931).

This all looks pretty clean now, so we should be able to move forward with implementing 2FA next! 🥳 🔐

**Comment by lastzero** [comment]
We now have an OTP library and database table/model in place to generate and store TOTP two-factor authentication keys for users who have 2FA enabled:

- We could encrypt these, but the risk is that the encryption key gets lost (or intentionally deleted), which would render one or all 2FA keys useless, effectively locking all users out of their accounts, or alternatively bypassing the need for two-factor authentication in the first place.
- Both seems pretty bad, and an admin with access to the database tables could disable 2FA and/or change a user's password anyway...

So what shall we do? Encrypt or not encrypt? Any preferences? 🤔

**Comment by lastzero** [comment]
We have just updated the `photoprism/photoprism:test` image on Docker Hub to include the latest changes and improvements. When updating, it is best to reset the sessions table to force a re-login of currently authenticated users and clients by running the `photoprism auth reset` command in a terminal:

```
docker compose exec photoprism photoprism auth reset -y
```

While you cannot enable 2FA with this version yet, you can manage OAuth2 client credentials and app passwords for user accounts, e.g. with just the `webdav` scope, so that webdav clients/sync apps do not get more privileges than they need:

```
docker compose exec photoprism photoprism auth add --scope webdav --name WebDAV admin
```

Run the following to see all currently authenticated users and clients:

```
docker compose exec photoprism photoprism auth ls
```

In addition, you can use this command to [create credentials](https://github.com/photoprism/photoprism/issues/3943) for use with the [`POST /api/v1/oauth/token`](https://demo.photoprism.app/.well-known/oauth-authorization-server) endpoint:

```
docker compose exec photoprism photoprism client add
```

**Please note that I will be away most of next week to celebrate my birthday with the family, so work on 2FA won't continue for the next few days. This should give enough time for you to test what we already have and provide feedback. Thank you very much!** :heart:

**Comment by lastzero** [comment]
In addition to fixing issues found during QA, we also started working on the UI today by adding buttons to configure 2FA and App passwords under Settings > Account (they remain disabled until the dialogs are fully implemented):

![account](https://github.com/photoprism/photoprism/assets/301686/608870d2-94e0-4df5-bf19-2c2522f1747b)

Edit: Our public demo at https://demo.photoprism.app/library/settings/account and the `photoprism/photoprism:test` image available on Docker Hub have been updated to include the latest changes and improvements.

**Comment by adutta98** [comment]
I was just wondering if I update to the test image, would there be a way to go back to a stable image? 

2FA is something very big for me, and I have been using an Authelia front end to expose photoprism to the internet. I also don't want to regenerate thumbnails and compatible movie clips again. Perhaps I'll spin up a 2nd docker instance using the data from the first one and then move to test on that one to test it out. 

I'd request to consider allowing integration with Authelia etc as well, currently I use Authelia with totp client like DUO, which I can also migrate with me if I have a device change, very convenient overall. Thanks for all the good work.

**Comment by lastzero** [comment]
@adutta98 Sorry for not getting back to you any sooner! We've just updated our backend with [new geodata](https://floss.social/@photoprism/111913372297506731), [new map tiles](https://maps.photoprism.app/), and new hardware. That's all done now, so we'll now add what's missing to get 2FA released.

As for your question: it might work, although I wouldn't bet on it... the database schema is updated and not all changes might be fully backwards compatible.

**Comment by lastzero** [comment]
Here is a preview of the 2FA setup dialog:

![2fa-enable](https://github.com/photoprism/photoprism/assets/301686/1d32e707-ba98-40f5-845f-5f3fa5529160)

Once the wording is final, we will push it to the repository so you can test it and contributors can start translating the text into all the currently supported UI languages.

**Comment by lastzero** [comment]
This screenshot shows the QR code (and alternatively the text key) that can be used to set up 2FA with code generator apps such as Google or Microsoft Authenticator:

![2fa-confirm](https://github.com/photoprism/photoprism/assets/301686/943d16a4-f7d1-4462-b0d0-3c032711cbf9)

**Comment by lastzero** [comment]
The final step required to activate 2FA is to copy the recovery code and confirm that you will keep it in a safe place:

![2fa-recovery-code](https://github.com/photoprism/photoprism/assets/301686/6658db27-f90f-4fdb-864d-0e02d4a1b32b)

All that is missing now is a workflow to deactivate 2FA once it has been activated. Just like when activating 2FA, your password will be required for confirmation:

![2fa-disable](https://github.com/photoprism/photoprism/assets/301686/0368c741-5bf4-4cdf-91cf-e6992d76a64c)

**Comment by lastzero** [comment]
Two-factor authentication with TOTP passcodes is now fully implemented and can be tested using the `photoprism/photoprism:test` image on Docker Hub (or by building from source):

- The "Apps & Devices" dialog for managing app passwords from the user interface is still missing, so the corresponding button is disabled in this test version and cannot be activated by any user actions.
- If needed, you can manage app passwords and client credentials for using the API with the terminal commands described above.
 
Note that this build is meant for QA testing and may still contain a few bugs. However, it should generally work and be relatively safe to use.

**Once the app password management is also implemented in the user interface, we will continue to release official development preview builds in preparation for the upcoming stable release:**
- #4114

**Comment by per2jensen** [comment]
Hey @lastzero - wonderful with 2FA enabled on the test build "Build 240322-d01804029".

I have enabled it and started using it.
Setup worked right out of the gate on Firefox v123.

Observation:
When typing in the 6-digit number from Google Authenticator, both Firefox v123 and Chrome v122 asks if the password should be updated. I will at some point click the "yes" button and erroneously update the password with the 2FA code.

Suggestion:
Make webbrowser not try to update the password after giving the 2FA 6-digit number

**Comment by lastzero** [comment]
@per2jensen Thanks for testing it! I'll do my best to prevent this once I can reproduce it on my local dev environment by either renaming the input fields or following this advice to use `autocomplete="one-time-code"` as attribute:
- https://stackoverflow.com/questions/15738259/disabling-chrome-autofill

**Comment by lastzero** [comment]
@per2jensen Based on the following reference, I've added the proper autocomplete attributes to all authentication-related fields and pushed a new [photoprism/photoprism:test](https://hub.docker.com/r/photoprism/photoprism/tags?page=1&name=test) build so you can test these changes:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

As before, Chrome 123.0.6312.58 (Linux/AMD64) offered me to automatically fill in my saved password, but it didn't ask me to update it after I entered the one-time code and clicked the "Sign In" button.

**Comment by per2jensen** [comment]
@lastzero - I have downloaded PP Build 240324-d126d4d85 and re-tested.
1)
Chrome version 122.0.6261.57 on linux: does not offer to update password, so problem fixed
2)
Firefox version 123.0 (Ubuntu Snap): still offers to update password.
I will fiddle around with Firefox to see if it is a setting which interferes. Also perhaps an extention trips something up.

**Comment by lastzero** [comment]
@per2jensen Excellent, thanks for testing it again! Firefox does not yet support `autocomplete="one-time-code"`:
- https://caniuse.com/?search=one-time-code

Also, Firefox probably uses different heuristics than Chrome. Hopefully there is a way to prevent both browsers from updating the saved password. Any help with finding a solution is much appreciated.

**Comment by lastzero** [comment]
We further improved the user interface yesterday by changing the icons and order of the account management buttons. If 2FA is not enabled (but could be enabled for your account), you will see a shield with an exclamation mark. Once 2FA has been successfully enabled, it becomes a shield with a checkmark:

![Screenshot 2024-03-27 at 08 41 33](https://github.com/photoprism/photoprism/assets/301686/58861e9b-3e8f-4e6f-b8b1-fabb97eaadc5)

In addition, we are working to improve the usability of the login screen by adding hints and attempting to resolve remaining issues with password managers:

![2fa-login-verification](https://github.com/photoprism/photoprism/assets/301686/2099a6b7-63aa-4b97-b299-825e5bf739ce)

**Comment by lastzero** [comment]
@per2jensen Would you be able to test this again with our latest preview build?

- https://docs.photoprism.app/release-notes/#development-preview
- https://docs.photoprism.app/getting-started/updates/#development-preview

As you can [see in the screenshot above](https://github.com/photoprism/photoprism/issues/808#issuecomment-2022135231), we removed the username input field when asking for the verification code, so there is a chance that Firefox no longer interprets it as your account password. :thinking:

**Comment by lastzero** [comment]
Note that creating app passwords is also possible using terminal commands, while we are still working on a UI for this:
- #4114 

For example, you can run the following to create a WebDAV app password for the *admin* account, so that compatible clients can use the WebDAV API even if 2FA is enabled for the user account:

```bash
photoprism auth add -s webdav admin
```

**Comment by lastzero** [comment]
Below is a preview of the "Apps and Devices" dialog, which will let you create, edit, and delete app-specific passwords (we may later extend it so you can also manage apps connected via OAuth2):

![apps-and-devices](https://github.com/photoprism/photoprism/assets/301686/f6072a77-189e-4805-8848-391e97291093)

**Comment by lastzero** [comment]
In order to release 2FA more quickly, we could use some help translating the user interface into other languages:
- https://translate.photoprism.app/projects/photoprism/
- https://docs.photoprism.app/developer-guide/translations-weblate/

Thank you very much! :heart:

**Comment by lastzero** [comment]
@per2jensen I've changed the name of the verification code input field from `passcode` to `code`, hoping that this keeps all the password managers out there from updating the saved password...

**Comment by lastzero** [comment]
Here's a screenshot of the [newly added app password dialog](https://github.com/photoprism/photoprism/issues/4114), which is now fully functional, except for an overview that allows you to view and delete existing app authorizations (should be ready by the end of this week):

![copy-app-password](https://github.com/photoprism/photoprism/assets/301686/fa3ec3b7-a4a2-4abf-b8c6-5dd87d181429)

Once that's done, we need to check the open bug reports to make sure everything is fixed. Finally, QA testing will take a few more days before we can release this! :tada:

**Comment by lastzero** [comment]
The **Apps and Devices** dialog in our [updated preview](https://docs.photoprism.app/getting-started/updates/#development-preview) build now also lets you [view and delete](https://github.com/photoprism/photoprism/issues/4114) app passwords:

![apps-and-devices](https://github.com/photoprism/photoprism/assets/301686/5357ff16-a363-4466-aee8-689288cf46ad)

![apps-confirm](https://github.com/photoprism/photoprism/assets/301686/fa225ac6-312f-4942-9957-085a8a96dbd3)

There are still some tests we need to add. We also wanted to **increase the session lifetime** when 2FA is enabled, so you don't need to re-login as often (since this takes longer with 2FA and accounts seem less likely to be abused). Should there be any other opinions, now would be a good time to let us know! :right_anger_bubble:

**Comment by lastzero** [comment]
An [updated preview build](https://docs.photoprism.app/getting-started/updates/#development-preview) is now available [on Docker Hub](https://hub.docker.com/r/photoprism/photoprism/tags?name=preview) for final testing:

- https://docs.photoprism.app/getting-started/updates/#development-preview
- https://docs.photoprism.app/release-notes/#development-preview

**Any help with that is much appreciated!** :tada:

**Comment by swingstate** [comment]
Finally. :) Great to see this has made it into the product!
