### ISSUE TITLE
Collect file samples for popular camera brands and models

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#81]
**As a developer, I want an archive with JPEG and RAW file samples for different camera brands and models so that I can test properly.**

You can get an account for uploading to https://dl.photoprism.org/samples/, please ask.

Maybe we can copy some from https://www.rawsamples.ch/, please check copyright and terms & conditions.
--> The images provided there are under the [Creative Commons License 4.0 ](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode) so I assume we can use those for testing

Acceptance Criteria:
- [ ] We only need samples for the most popular brands and models right now.
- [ ] Please document any research you do in our Wiki e.g. when you try to figure out what brands and models are popular. https://github.com/photoprism/photoprism/wiki/Samples
- [ ] Don't violate any copyright or terms & conditions.
- [ ] There should be no humans / faces on the photos (unless they gave explicit approval for worldwide free use for anything). Animals are OK!

**Comment by twatzl** [comment]
I can contribute photos from Nikon (D90/D610), Sony ILCE 5100, Panasonic Lumix TZ5 and GoPro if needed. Both in RAW and JPG (gopro only jpg). I might also be able to get some more from other models and brands (esp. Canon).

**Comment by lastzero** [comment]
Our current samples: https://dl.photoprism.org/samples/

You're welcome to send us a link for download e.g. via Google Drive or Dropbox.

**Comment by dmag** [comment]
I added a link in the Wiki to Flickr data on camera use. (I'm not sure I fully trust it, but I think it's important that it shows a lot of smartphones in use). I assert that photographers buying cameras from Nikon/Sony are a dying breed. Most people don't buy cameras anymore, they just use their smartphones. So we should also ask for smartphone pictures too.

**Comment by twatzl** [comment]
Well my guess would be there are 3 (or 4) groups of people in general:
1. "ordinary people" who use just their smartphone for taking photos ocasionally
2. people who might (additionally) use compact cameras at some special occasions like skiing or hiking
3. Hobby photographers who use one or more DSLRs and eventually also shoot in RAW
4. Professional photographers of all kinds

The biggest number of pictures will of course come from group 1 since everybody owns a smartphone. Group 2 is getting smaller as smartphones are getting better at taking pictures. 
Groups 3 and 4 will stay at system cameras or dslrs I think, but of course those people are only a small fraction. 

The interesting/important question is: Which of those people are potential users of photoprism?
My guess would be that until there is a hosted version it will probably be mainly group 3. 

Also I am not sure if the other people would even use a tool like photoprism since at least most of the people I know hardly move the photos from their smartphones to a PC.

To which wiki page exactly did you add it?

@lastzero Sorry. I did not forget but was pretty busy. I will try to collect samples this weekend.

**Comment by lastzero** [comment]
Done that, see https://dl.photoprism.org/samples/
