### ISSUE TITLE
UI: Prefix routes with /library/... so that 404 can be returned for non-existing assets

### ISSUE THREAD

**Issue by benmccann** [photoprism/photoprism#840]
During development I was requesting a JS file that did not exist. However, it took me a very long time to figure this out because the browser was returning a 200. I thought I had Babel configured wrong or something because it kept telling me I had a malformed JS file. In reality it was returning HTML inside my JS

**Comment by lastzero** [comment]
Routing is performed on the client. There is no simple way the server may know what routes exist in JS - and we can't afford to add much more complexity right now.

We may of course implement a 404 page in JS saying "No found, click here to return to home" instead of redirecting to home straight away. Not sure how much value this provides to our users though.

**Comment by benmccann** [comment]
Ah, that makes sense. While we can't do it for a generic route, we might be to implement a 404 just for non-existent `.js` and `.css` files

**Comment by benmccann** [comment]
It looks like this would be handled here:

https://github.com/photoprism/photoprism/blob/a747cca962fd8ea77ad81e6728b2d16e3ae8f60b/internal/server/routes.go#L151

**Comment by lastzero** [comment]
Nobody complained so far, so I'll move ahead and close this as done!
