### ISSUE TITLE
UX: Simplify playing videos in the photo viewer

### ISSUE THREAD

**Issue by jakobroehrl** [photoprism/photoprism#932]
It was hard to find this button for me:
![image](https://user-images.githubusercontent.com/24530680/105185485-d8df4200-5b30-11eb-97ee-14e7a32366d9.png)

Maybe a onmouseover Play Button would be easier to find

**Comment by trho** [comment]
Just wanted to open a similar issue, but since the topic matches with my idea I put my suggestion here.

It would be great, if you could combine playing videos with the slideshow feature. 
Starting the slideshow (play button in the header) plays the video. Once the video ends, the next photo/video is shown. 
If the next file is a video it is auto-played.
Ideally the video is resized to the surrounding view (in full screen mode to full screen).

This would reflect the way Emby and Plex are handling videos in slideshows and is a great way to view mixed video/photo libraries.

**Comment by lastzero** [comment]
Happy to develop a combined photo / video lightbox when we reach our [funding goal](https://github.com/sponsors/photoprism) 🌈

**Comment by lastzero** [comment]
The photo viewer uses play button now with a "Play" tooltip on mouse over - does that work for now?

**Comment by jakobroehrl** [comment]
looks much better, thanks for this rapid implementation 👍 

![image](https://user-images.githubusercontent.com/24530680/105356005-215f3400-5bf3-11eb-9f5c-ec4f5ea87f7e.png)
