### ISSUE TITLE
PHOTOPRISM_SITE_URL does not affect static resources and JavaScript

### ISSUE THREAD

**Issue by Weltraumschaf** [photoprism/photoprism#946]
I need to get Photoprism work behind a reverse proxy (Traefik). It is required that Photoprism runs under http://domain/photos. I configred PHOTOPRISM_SITE_URL=http://domain/photos, but this does not add the context root "photo" to all necessary parts of the application: static resources, JavaScript API calls, websocket connections and also the location rewrites in the browser.

**Comment by Rodionc** [comment]
Same issue, with Apache as proxy :(

**Comment by lastzero** [comment]
Installing photoprism in sub directories is not supported.

**Comment by Weltraumschaf** [comment]
Ok, I'll look for better software.

**Comment by lastzero** [comment]
Enjoy 👍

**Comment by alexislefebvre** [comment]
> Installing photoprism in sub directories is not supported.

Could a PR that add this support be accepted?

**Comment by lastzero** [comment]
In theory yes, in practice there are 177 open issues and 20 open pull requests already. I honestly don't know when to do it the next couple of months - and you don't want me to merge a high impact PR like this blindly.

Apps like PhotoPrism use their own domain because:

1. It's less effort, less complexity and less testing. Note, that we have LIMITED resources and provide this for FREE.
2. Browser connections, routing and related resources don't need to be shared with other apps, so it's faster and easier to configure. Note that cloud photo apps typically use multiple sub domains for faster loading - it's the exact opposite.
3. It's easier for the user to clear the cache, or use other browser settings like turning off ad blockers.
4. The same origin policy generally works on the (sub-)domain level, so it may be insecure to host multiple apps on the same domain (although modern browsers may provide additional ways to fix this, which I really don't have time to study in detail right now - see open issues and limited resources). I'd rather disappoint @Weltraumschaf than be responsible for an unsafe app.

Just because you get PhotoPrism for free doesn't mean it's OK to show no respect and keep asking for more - especially when there are very good reasons and you're not a sponsor or contributor like @Weltraumschaf 👍

**Comment by lastzero** [comment]
Added this question to our FAQs:

https://docs.photoprism.org/getting-started/faq/#can-i-deploy-photoprism-on-a-shared-domain-like-httpsexamplecomphotoprism
