### ISSUE TITLE
Allow mass unstacking.

### ISSUE THREAD

**Issue by Darkwolf1515** [photoprism/photoprism#964]
None of the images that got stacked are duplicates, but the only way to unstack is to go through each one, hand by hand. A mass unstack button would be great, even if I have to select them all by hand.

**Comment by lastzero** [comment]
Why did they got stacked? Did you see the config options in Settings > Library?

**Comment by Darkwolf1515** [comment]
Hm, yeah I now see it as an option, doesn't seem to unstack already stacked photos, oh well, had to do a mass remport anyways, thanks!

**Comment by lastzero** [comment]
PhotoPrism is fast, but it can't recursively rescan and re/unstack your complete photo library (sometimes 500k+ files) whenever you click a checkbox 😉

**Comment by Darkwolf1515** [comment]
> 
> 
> PhotoPrism is fast, but it can't recursively rescan and re/unstack your complete photo library (sometimes 500k+ files) whenever you click a checkbox 😉

Its not a big deal, I had to finally really make the final move from google photos today, and a full redo was easier.

**Comment by lukasgabriel** [comment]
> PhotoPrism is fast, but it can't recursively rescan and re/unstack your complete photo library (sometimes 500k+ files) whenever you click a checkbox 😉

In my opinion, it would not need to be fast, it just needs to be better than sitting there for tens of hours, clicking the same button hundreds of thousands of times. Indexing for me took about two weeks, and because of a misunderstanding of the "stacking" feature, many thousands of photos are now wrongfully stacked. Anything short of re-indexing everything would be an improvement in this scenario.

**Comment by lukasgabriel** [comment]
Unfortunately, I'm unfamiliar with Go, so I can't be much help with this directly. But I might make a Selenium Script to automate a browser that does the unstacking in the background. I will post it here when it's done, if anyone is interested.

**Comment by lastzero** [comment]
A Selenium script would be very inefficient and probably not very reliable. In most cases, it is best to follow the advice in our documentation and start again with a fresh index if you don't want to have any stacks at all (unless files have exactly the same name).

**Comment by lastzero** [comment]
Note that unstacking requires re-indexing, except that the process is triggered every time you press the button. The result also depends on the order in which you perform the operation.

We get that a few users may not notice that their files have been stacked and continue editing metadata/albums for weeks. Now they want to keep their changes and but have all files unstacked at once. Later, they may realize that this is not perfect either, so they want to revert some of it...

Anyway, the current implementation is what we have in store right now. Everyone is welcome to support our work so that we can eventually grow our team, which might allow us to work on solutions for such edge cases :)

**Comment by lukasgabriel** [comment]
> A Selenium script would be very inefficient and probably not very reliable. In most cases, it is best to follow the advice in our documentation and start again with a fresh index if you don't want to have any stacks at all (unless files have exactly the same name).

You're definitely right that it would be inefficient. I didn't know that the "button press" was essentially the same thing as re-indexing those files. In that case, my script would obviously not make much sense.

I'm running my Photoprism Instance on a Synology NAS in a Docker container - which is more than fine for viewing, but indexing takes ages. Any tips for running the indexing on my Desktop PC and moving it over to my NAS once it's finished?  :)

**Comment by lastzero** [comment]
It's basically the same as creating and restoring a backup, which should include the `storage` and `originals` folders if your intention is to save time (otherwise you have to recreate thumbs etc). There is a command to create a database dump for the metadata:

```
docker-compose exec -T photoprism photoprism backup -i - > photoprism-db.sql
```

There is also a restore command, our docs can be improved but cover the basics. Use the search field in the upper right corner.

**Comment by lukasgabriel** [comment]
> It's basically the same as creating and restoring a backup, which should include the `storage` and `originals` folders if your intention is to save time (otherwise you have to recreate thumbs etc). There is a command to create a database dump for the metadata:
> 
> ```
> docker-compose exec -T photoprism photoprism backup -i - > photoprism-db.sql
> ```
> 
> There is also a restore command, our docs can be improved but cover the basics. Use the search field in the upper right corner.

Thank you! That helps a lot.
